INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_ESTADO)
VALUES (13, 0, 941000, 0, 'Activo');

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_ESTADO)
VALUES (13, 941001, 1381000, 10, 'Activo');

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_ESTADO)
VALUES (13, 1381001, 2423000, 15, 'Activo');

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_ESTADO)
VALUES (13, 2423001, 4845000, 20, 'Activo');

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_ESTADO)
VALUES (13, 4845001, 999999999, 25, 'Activo');

COMMIT;

SELECT 'Rangos insertados!' AS MSG FROM DUAL;
SELECT ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE 
FROM ACS_TIPO_MOV_RANGO 
WHERE ATM_ID = 13
ORDER BY ATMR_RANGO_MIN;
