networks:
  oracle-net:
    driver: bridge

services:
  oracle-primary:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    platform: linux/amd64
    container_name: oracle_primary
    hostname: oracle-primary
    ports:
      - "1523:1521"  # Primary
      - "8080:5500"  # Enterprise Manager
    environment:
      - ORACLE_PWD=admin123
      - ORACLE_SID=ORCL
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=enterprise
    volumes:
      - ./data/primary:/opt/oracle/oradata
      - ./scripts/primary:/opt/oracle/scripts/setup:ro
      - ./data/shared:/opt/oracle/shared
    networks:
      - oracle-net
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -s sys/admin123@//localhost:1521/ORCL as sysdba <<< 'SELECT 1 FROM dual;' | grep -q '1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  oracle-standby:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    platform: linux/amd64
    container_name: oracle_standby
    hostname: oracle-standby
    ports:
      - "1524:1521"  # Standby
      - "8081:5500"  # Enterprise Manager
    environment:
      - ORACLE_PWD=admin123
      - ORACLE_SID=STBY
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=enterprise
    volumes:
      - ./data/standby:/opt/oracle/oradata
      - ./scripts/standby:/opt/oracle/scripts/setup:ro
      - ./data/shared:/opt/oracle/shared
    networks:
      - oracle-net
    depends_on:
      oracle-primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -s sys/admin123@//localhost:1521/STBY as sysdba <<< 'SELECT 1 FROM dual;' | grep -q '1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
