/*
CREATED: 21/08/2025
MODIFIED: 25/09/2025
PROJECT: ADMINISTRACIÓN DE CENTROS DE SALUD ( ACS )
MODEL: ORACLE 19C
COMPANY: UNA
AUTHOR: EGRANADOS - JCAMACHO - FMORA
VERSION: 1.0
DATABASE: ORACLE 19C
*/


-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE ACS_PUESTO_MEDICO

CREATE TABLE "ACS_PUESTO_MEDICO"(
  "APM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APM_NOMBRE" VARCHAR2(150 ) NOT NULL,
  "APM_DESCRIPCION" VARCHAR2(255 ),
  "APM_ESTADO" VARCHAR2(10 ) NOT NULL,
  CONSTRAINT "CHK_APM_ESTADO" CHECK (APM_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PUESTO_MEDICO

ALTER TABLE "ACS_PUESTO_MEDICO" ADD CONSTRAINT "PK_ACS_PUESTO_MEDICO" PRIMARY KEY ("APM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PUESTO_MEDICO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS PUESTOS MEDICOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_ID" IS 'ID UNICO DE CADA PUESTO MEDICO
'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_NOMBRE" IS 'NOMBRE UNICO DEL PUESTO MEDICO'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_DESCRIPCION" IS 'DESCRIPCIÓN DEL PUESTO MEDICO'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_ESTADO" IS 'CAMPO PARA VALIDAR EN QUE ESTADO SE ENCUENTRA EL PUESTO MEDICO
'
/

-- TABLE ACS_CENTRO_MEDICO

CREATE TABLE "ACS_CENTRO_MEDICO"(
  "ACM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACM_NOMBRE" VARCHAR2(150 ) NOT NULL,
  "ACM_UBICACION" VARCHAR2(255 ),
  "ACM_TELEFONO" VARCHAR2(50 ),
  "ACM_EMAIL" VARCHAR2(150 ),
  "ACM_ESTADO" VARCHAR2(10 ) NOT NULL,
  CONSTRAINT "CHK_ACM_ESTADO" CHECK (ACM_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_CENTRO_MEDICO

ALTER TABLE "ACS_CENTRO_MEDICO" ADD CONSTRAINT "PK_ACS_CENTRO_MEDICO" PRIMARY KEY ("ACM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_CENTRO_MEDICO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS CENTROS DE SALUD QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_ID" IS 'ID UNICO DE CADA CENTRO DE SALUD DEL SISTEMA'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_NOMBRE" IS 'NOMBRE UNICO DE CADA UNO DE LOS CENTROS DE SALUD DEL SISTEMA'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_UBICACION" IS 'UBICACIÓN EXACTA Y DETALLADA DEL CENTRO DE SALUD'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_TELEFONO" IS 'TELEFONO PARA CONTACTAR AL CENTRO DE SALUD'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_EMAIL" IS 'EMIAL PROPIO DEL CENTRO DE SALUD'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_ESTADO" IS 'CAMPO PARA VALIDAR EN QUE ESTADO SE ENCUENTRA EL CENTRO MEDICO
'
/

-- TABLE ACS_TURNO

CREATE TABLE "ACS_TURNO"(
  "ATU_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATU_NOMBRE" VARCHAR2(30 ) NOT NULL,
  "ATU_HORA_INICIO" TIMESTAMP(6) NOT NULL,
  "ATU_HORA_FIN" TIMESTAMP(6) NOT NULL,
  "ATU_TIPO_PAGO" VARCHAR2(10 ) NOT NULL,
  "ATU_COSTO" NUMBER NOT NULL,
  "ATU_PAGO" NUMBER NOT NULL,
  "ATU_ESTADO" VARCHAR2(10 ) NOT NULL,
  "APM_ID" NUMBER,
  "AME_ID" NUMBER,
  CONSTRAINT "CHK_ATU_ESTADO" CHECK (ATU_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_APU_TIPO_PAGO" CHECK (APT_TIPO_PAGO IN ('TURNO', 'HORAS'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_TURNO

ALTER TABLE "ACS_TURNO" ADD CONSTRAINT "PK_ACS_TURNO" PRIMARY KEY ("ATU_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_TURNO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS TURNOS MEDICOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_ID" IS 'ID UNICO DE CADA TURNO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_NOMBRE" IS 'NOMBRE UNICO DEL TURNO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_HORA_INICIO" IS 'HORA DE INICIO DEL TURNO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_HORA_FIN" IS 'HORA DE FINALIZACIÓN DEL TURNO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_TIPO_PAGO" IS 'CAMPO PARA DEFINIR SI SE PAGA POR HORA O POR TURNO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_COSTO" IS 'COSTO QUE SUPONE PARA EL CENTRO MEDICO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_PAGO" IS 'PAGO QUE SE LE HACE AL MEDICO'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA EL TURNO'
/

-- TABLE ACS_MEDICO

CREATE TABLE "ACS_MEDICO"(
  "AME_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AME_ESTADO" VARCHAR2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_AME_ESTADO" CHECK (AME_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_MEDICO

ALTER TABLE "ACS_MEDICO" ADD CONSTRAINT "PK_ACS_MEDICO" PRIMARY KEY ("AME_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_MEDICO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR MEDICOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_MEDICO"."AME_ID" IS 'ID UNICO DE CADA MEDICO
'
/
COMMENT ON COLUMN "ACS_MEDICO"."AME_ESTADO" IS 'ESTADO: ACTIVO, INACTIVO. PARA VISIBILIDAD '
/
COMMENT ON COLUMN "ACS_MEDICO"."AUS_ID" IS 'ID QUE RELACIONA AL MEDICO CON EL USUARIO '
/

-- TABLE ACS_PROCEDIMIENTO

CREATE TABLE "ACS_PROCEDIMIENTO"(
  "APD_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APD_NOMBRE" VARCHAR2(100 ) NOT NULL,
  "APD_DESCRIPCION" VARCHAR2(255 ),
  "APD_ESTADO" VARCHAR2(10 ) NOT NULL,
  CONSTRAINT "CHK_APD_ESTADO" CHECK (APD_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PROCEDIMIENTO

ALTER TABLE "ACS_PROCEDIMIENTO" ADD CONSTRAINT "PK_ACS_PROCEDIMIENTO" PRIMARY KEY ("APD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PROCEDIMIENTO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS PROCEDIMIENTOS MEDICOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_ID" IS 'ID UNICO DE CADA PROCEDIMIENTO '
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_NOMBRE" IS 'NOMBRE UNICO DEL PROCEDIMIENTO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_DESCRIPCION" IS 'DESCRIPCIÓN DEL PROCEDIMIENTO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA EL PROCEDIMIENTO
'
/

-- TABLE ACS_PROC_APLICADO

CREATE TABLE "ACS_PROC_APLICADO"(
  "APA_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APA_FECHA" TIMESTAMP(6) NOT NULL,
  "APA_COSTO" NUMBER NOT NULL,
  "APA_PAGO" NUMBER NOT NULL,
  "APA_ESTADO" VARCHAR2(10 ) NOT NULL,
  "AME_ID" NUMBER NOT NULL,
  "APD_ID" NUMBER NOT NULL,
  "ACM_ID" NUMBER,
  CONSTRAINT "CHK_APA_ESTADO" CHECK (APA_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_PROC_APLICADO

CREATE INDEX "IDX_AME_ID (APA)" ON "ACS_PROC_APLICADO" ("AME_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "IDX_ACM_ID" ON "ACS_PROC_APLICADO" ("ACM_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "IDX_AME_ID_X_ACM_ID" ON "ACS_PROC_APLICADO" ("AME_ID","ACM_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_PROC_APLICADO

ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "PK_ACS_PROC_APLICADO" PRIMARY KEY ("APA_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PROC_APLICADO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS PROCEDIMIENTOS APLICADOS QUE HAY EN EL SISTEMA, YA QUE UN MEDICO PUEDE HCAER MUCHOS PROCEDIMIENTOS Y UN PROCEDIMIENTO PUEDE HACERSE VARIAS VECES PERO POR DIFERENTES MEDICOS'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_ID" IS 'ID UNICO DEL PROCEDIMIENTO APLICADO'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_FECHA" IS 'FECHA EN LA QUE SE APLICÓ EL PROCEDIMIENTO'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_COSTO" IS 'COSTO REAL UNA VEZ EL PROCEDIMIENTO FUE APLICADO'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_PAGO" IS 'PRECIOA REAL A PAGARLE AL MEDICO POR EL PROCEDIMIENTO'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_ESTADO" IS 'ESTADO EN QUE SE ENCUENTRA EL PROCECIMIENTO APLICADO'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."AME_ID" IS 'ID DEL MEDICO RELACIONADO'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APD_ID" IS 'ID DEL PROCEDIMINETO RELACIONADO'
/

-- TABLE ACS_ESCALA_MENSUAL

CREATE TABLE "ACS_ESCALA_MENSUAL"(
  "AEM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AEM_MES" NUMBER NOT NULL,
  "AEM_ANIO" NUMBER NOT NULL,
  "AEM_ESTADO" VARCHAR2(20 ) NOT NULL,
  "ACM_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_AEM_ESTADO" CHECK (AEM_ESTADO IN ('CONSTRUCCION', 'VIGENTE', 'EN REVISION', 'LISTA PARA PAGO', 'PROCESADA')),
  CONSTRAINT "CHK_AEM_MES" CHECK (AEM_MES BETWEEN 1 AND 12),
  CONSTRAINT "CHK_AEM_ANIO" CHECK (AEM_ANIO >= 2000)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_ESCALA_MENSUAL

ALTER TABLE "ACS_ESCALA_MENSUAL" ADD CONSTRAINT "PK_ACS_ESCALA_MENSUAL" PRIMARY KEY ("AEM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_ESCALA_MENSUAL" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LAS ESCALAS MENSUALES QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_ID" IS 'ID UNICO DE CADA ESCALA MENSUAL
'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_MES" IS 'MES EXACTO DE LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_ANIO" IS 'AÑO EXACTO DE LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."ACM_ID" IS 'ID DEL CENTRO RELACIONADO A LA ESCALA MENSUAL'
/

-- TABLE ACS_DETALLE_MENSUAL

CREATE TABLE "ACS_DETALLE_MENSUAL"(
  "ADM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADM_OBSERVACIONES" VARCHAR2(255 ),
  "ADM_FECHA" TIMESTAMP(6) NOT NULL,
  "ADM_ESTADO_TURNO" VARCHAR2(15 ) NOT NULL,
  "ADM_HR_INICIO" TIMESTAMP(9) NOT NULL,
  "ADM_HR_FIN" TIMESTAMP(9) NOT NULL,
  "ADM_ESTADO" VARCHAR2(10 ) NOT NULL,
  "AEM_ID" NUMBER NOT NULL,
  "AME_ID" NUMBER NOT NULL,
  "APM_ID" NUMBER NOT NULL,
  "ATU_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_ADM_ESTADO" CHECK (ADM_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_AMD_ESTADO_TURNO" CHECK (ADM_ESTADO_TURNO IN ('CUMPLIDO','FALTA','CANCELADO','REEMPLAZADO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_DETALLE_MENSUAL

CREATE UNIQUE INDEX "UQ_AEM_ID_X_ATU_ID_X_APM_ID_X_AME_ID_X_ADM_FECHA" ON "ACS_DETALLE_MENSUAL" ("ATU_ID","APM_ID","AME_ID","AEM_ID","ADM_FECHA")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "IDX_AME_ID (ADM)" ON "ACS_DETALLE_MENSUAL" ("AME_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_DETALLE_MENSUAL

ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "PK_ACS_DETALLE_MENSUAL" PRIMARY KEY ("ADM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_DETALLE_MENSUAL" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS DETALLES DE LAS ESCALAS MENSUALES QUE HAY EN EL SISTEMA, ESTE ES UN PUNTO QUE REUNE MEDICOS, CENTROS, PUESTOS, TURNOS Y DEMÁS, ESTO SE MANEJA ASÍ YA QUE PUEDEN HABER MUCHOS CAMBIOS Y SE REQUIERE FLEXIBILIDAD EN ESOS CAMPOS, POR ESO NO SE RELACIONAN ENTRE ELLOS SI NO QUE SE JUNTA EN UNA TABLA '
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_ID" IS 'ID UNICO DEL DETALLE DE LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_OBSERVACIONES" IS 'OBSERVACIONES DEL DETALLE MENSUAL'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_FECHA" IS 'FECHA ESPECIFICA DEL DETALLE'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_ESTADO_TURNO" IS 'CAMPO PARA SABER EN QUE ESTÁ RELAMENTE QUEDÓ EL TURNO'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_HR_INICIO" IS 'HORA REAL EN LA QUE INICIÓ'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_HR_FIN" IS 'HORA REAL EN LA QUE FINALIZÓ'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA EL DETALLE MENSUAL'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."AEM_ID" IS 'ID DE REFERENCIA CON LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."AME_ID" IS 'ID DE REFERENCIA CON EL MEDICO 
'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."APM_ID" IS 'ID DE REFERENCIA CON EL PUESTO MEDICO 
'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ATU_ID" IS 'ID DEL TURNO RELACIONADO '
/

-- TABLE ACS_AUDITORIA_DETALLE_MENSUAL

CREATE TABLE "ACS_AUDITORIA_DETALLE_MENSUAL"(
  "AUM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AUM_OBSERVACIONES" VARCHAR2(255 ),
  "AUM_FECHA" TIMESTAMP(6) NOT NULL,
  "AUM_ESTADO_TURNO" VARCHAR2(15 ),
  "AUM_HR_INICIO" TIMESTAMP(9),
  "AUM_HR_FIN" TIMESTAMP(9),
  "AUM_ESTADO" VARCHAR2(10 ) NOT NULL,
  "AUM_USUARIO" VARCHAR2(50 ) NOT NULL,
  "AUM_CAMBIOS" VARCHAR2(100 ),
  "AUM_ACCION" VARCHAR2(10 ),
  "AEM_ID" NUMBER,
  "AME_ID" NUMBER,
  "APM_ID" NUMBER,
  "ATU_ID" NUMBER,
  "ADM_ID" NUMBER,
  CONSTRAINT "CHK_ADM_ESTADO (AUM)" CHECK (AUM_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_AMD_ESTADO_TURNO (AUM)" CHECK (AUM_ESTADO_TURNO IN ('CUMPLIDO','FALTA','CANCELADO','REEMPLAZADO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_AUDITORIA_DETALLE_MENSUAL

ALTER TABLE "ACS_AUDITORIA_DETALLE_MENSUAL" ADD CONSTRAINT "PK_ACS_AUDITORIA_DETALLE_MENSUAL" PRIMARY KEY ("AUM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_AUDITORIA_DETALLE_MENSUAL" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENARR LOS DETALLES DE LAS ESCALAS MENSUALES QUE HAY EN EL SISTEMA, ESTE ES UN PUNTO QUE REUNE MEDICOS, CENTROS, PUESTOS, TURNOS Y DEMÁS, ESTO SE MANEJA ASÍ YA QUE PUEDEN HABER MUCHOS CAMBIOS Y SE REQUIERE FLEXIBILIDAD EN ESOS CAMPOS, POR ESO NO SE RELACIONAN ENTRE ELLOS SI NO QUE SE JUNTA EN UNA TABLA '
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ID" IS 'ID UNICO DEL DETALLE DE LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_OBSERVACIONES" IS 'OBSERVACIONES DEL DETALLE MENSUAL'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_FECHA" IS 'FECHA ESPECIFICA DEL DETALLE'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ESTADO_TURNO" IS 'CAMPO PARA SABER EN QUE ESTÁ RELAMENTE QUEDÓ EL TURNO'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_HR_INICIO" IS 'HORA REAL EN LA QUE INICIÓ'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_HR_FIN" IS 'HORA REAL EN LA QUE FINALIZÓ'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA EL DETALLE MENSUAL'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_USUARIO" IS 'USUARIO QUE REALIZÓ EL CAMBIO'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_CAMBIOS" IS 'PARA SABER QUÉ CAMPOS CAMBIARON'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ACCION" IS 'INSERT, UPDATE, DELETE'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AEM_ID" IS 'ID DE REFERENCIA CON LA ESCALA MENSUAL'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AME_ID" IS 'ID DE REFERENCIA CON EL MEDICO 
'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."APM_ID" IS 'ID DE REFERENCIA CON EL PUESTO MEDICO 
'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."ATU_ID" IS 'ID DEL TURNO RELACIONADO '
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."ADM_ID" IS 'ID DE REFERENCIA AL DETALLE DE ESCALA MENSUAL'
/

-- TABLE ACS_DOCUMENTO_USUARIO

CREATE TABLE "ACS_DOCUMENTO_USUARIO"(
  "ADU_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADU_URL" VARCHAR2(1000 ) NOT NULL,
  "ADU_COMENTARIOS" VARCHAR2(400 ),
  "ADU_ESTADO" VARCHAR2(10 ) DEFAULT 'PENDIENTE' NOT NULL,
  "ADU_FECHA_CREACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "ADU_FECHA_ACTUALIZACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "ATD_ID" NUMBER NOT NULL,
  "AUS_ID" NUMBER NOT NULL,
  "APF_ID" NUMBER,
  CONSTRAINT "CHK_ADU_ESTADO" CHECK (ADU_ESTADO IN ('PENDIENTE', 'APROBADO', 'RECHAZADO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_DOCUMENTO_USUARIO

CREATE UNIQUE INDEX "UQ_AUS_ID_X_ATD_ID" ON "ACS_DOCUMENTO_USUARIO" ("AUS_ID","ATD_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "ADU_X_APF" ON "ACS_DOCUMENTO_USUARIO" ("APF_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_DOCUMENTO_USUARIO

ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "PK_ACS_DOCUMENTO_USUARIO" PRIMARY KEY ("ADU_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_DOCUMENTO_USUARIO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR DOCUMENTOS DE LOS USUARIOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_ID" IS 'ID UNICO DEL DOCUMENTO'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_URL" IS 'URL DEL DOCUMENTO ADJUNTO'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_COMENTARIOS" IS 'DESCRIPCION PROPIA DEL DOCUMENTO'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_ESTADO" IS '(''PENDIENTE'', ''APROBADO'', ''RECHAZADO'')
'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_FECHA_CREACION" IS 'AUTOMATICO'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_FECHA_ACTUALIZACION" IS 'AUTOMATICO'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."AUS_ID" IS 'ID DEL USUARIO RELACIONADO AL DOCUMENTO'
/

-- TABLE ACS_USUARIO

CREATE TABLE "ACS_USUARIO"(
  "AUS_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AUS_ESTADO" VARCHAR2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_FECHA_CREACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "APE_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_AUS_ESTADO" CHECK (AUS_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_USUARIO

ALTER TABLE "ACS_USUARIO" ADD CONSTRAINT "PK_ACS_USUARIO" PRIMARY KEY ("AUS_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_USUARIO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR USUARIOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_ID" IS 'ID UNICO DE CADA USUARIO DEL SISTEMA
'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_ESTADO" IS 'ESTADO: ACTIVO, INACTIVO. PARA VISIBILIDAD Y GESTION DE PERFILES DE USUARIO'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_FECHA_CREACION" IS 'AUTOMATICO
'
/
COMMENT ON COLUMN "ACS_USUARIO"."APE_ID" IS 'FK'
/

-- TABLE ACS_ADMINISTRATIVO

CREATE TABLE "ACS_ADMINISTRATIVO"(
  "AAD_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AAD_ESTADO" VARCHAR2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_AAD_ESTADO" CHECK (AAD_ESTADO IN ('ACTIVO', 'INACTIVO', 'ARCHIVADO', 'SUSPENDIDO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_ADMINISTRATIVO

ALTER TABLE "ACS_ADMINISTRATIVO" ADD CONSTRAINT "PK_ACS_ADMINISTRATIVO" PRIMARY KEY ("AAD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_ADMINISTRATIVO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR ADMINISTRATIVOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_ADMINISTRATIVO"."AAD_ID" IS 'ID UNICO DE CADA ADMINISTRATIVO'
/
COMMENT ON COLUMN "ACS_ADMINISTRATIVO"."AAD_ESTADO" IS 'ESTADO: ACTIVO, INACTIVO. PARA VISIBILIDAD '
/
COMMENT ON COLUMN "ACS_ADMINISTRATIVO"."AUS_ID" IS 'ID DEL USUARIO RELACIONADO CON EL ADMINISTRATIVO'
/

-- TABLE ACS_CUENTA_BANCARIA

CREATE TABLE "ACS_CUENTA_BANCARIA"(
  "ACB_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACB_NUMERO_CUENTA" VARCHAR2(50 ) NOT NULL,
  "ACB_ES_PRINCIPAL" VARCHAR2(2 ) DEFAULT 'NO' NOT NULL,
  "ACB_TIPO_CUENTA" VARCHAR2(10 ) NOT NULL,
  "ACB_ESTADO" VARCHAR2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_ID" NUMBER NOT NULL,
  "ABA_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_ACB_ESTADO" CHECK (ACB_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ACB_TIPO_CUENTA" CHECK (ACB_TIPO_CUENTA IN ('AHORRO', 'CORRIENTE')),
  CONSTRAINT "CHK_ACB_ES_PRINCIPAL" CHECK (ACB_ES_PRINCIPAL IN ('SI', 'NO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_CUENTA_BANCARIA

CREATE UNIQUE INDEX "UQ_ACB_ES_PRINCIPAL_USUARIO" ON "ACS_CUENTA_BANCARIA" ((CASE WHEN ACB_ES_PRINCIPAL = 'SI' THEN AUS_ID END))
TABLESPACE "TBS_ACS_INDICES"
/

CREATE UNIQUE INDEX "UQ_ACB_NUMERO_CUENTA" ON "ACS_CUENTA_BANCARIA" ("ACB_NUMERO_CUENTA")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_CUENTA_BANCARIA

ALTER TABLE "ACS_CUENTA_BANCARIA" ADD CONSTRAINT "PK_ACS_CUENTA_BANCARIA" PRIMARY KEY ("ACB_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_CUENTA_BANCARIA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR CUENTAS BANCARIAS DE LOS USUARIOS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_ID" IS 'ID UNICO DE CADA CUENTA BANCARIA'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_NUMERO_CUENTA" IS 'NUMERO PROPIO Y UNICO DE LA CUENTA BANCARIA'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_ES_PRINCIPAL" IS 'SI, NO'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_TIPO_CUENTA" IS 'CORRIENTE O DE AHORRO'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_ESTADO" IS 'ESTADO: ACTIVO, INACTIVO. PARA VISIBILIDAD '
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."AUS_ID" IS 'ID DEL USUARIO RELACIONADO A LA CUENTA BANCARIA'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ABA_ID" IS 'ID DEL BANCO RELACIONADO A LA CUENTA BANCARIA'
/

-- TABLE ACS_BANCO

CREATE TABLE "ACS_BANCO"(
  "ABA_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ABA_NOMBRE" VARCHAR2(100 ) NOT NULL,
  "ABA_TELEFONO" VARCHAR2(20 ),
  "ABA_ESTADO" VARCHAR2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT "CHK_ABA_ESTADO" CHECK (ABA_ESTADO IN ('ACTIVO', 'INACTIVO', 'ARCHIVADO', 'SUSPENDIDO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_BANCO

CREATE UNIQUE INDEX "UQ_ABA_NOMBRE" ON "ACS_BANCO" ("ABA_NOMBRE")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_BANCO

ALTER TABLE "ACS_BANCO" ADD CONSTRAINT "PK_ACS_BANCO" PRIMARY KEY ("ABA_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_BANCO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR BAMCO QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_ID" IS 'ID UNICO DE CADA BANCO'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_NOMBRE" IS 'NOMBRE PROPIO Y UNICO DE CADA BANCO'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_TELEFONO" IS '+506 8888 8888'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_ESTADO" IS 'ESTADO: ACTIVO, INACTIVO. PARA VISIBILIDAD '
/

-- TABLE ACS_PERSONA

CREATE TABLE "ACS_PERSONA"(
  "APE_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APE_CEDULA" VARCHAR2(20 ) NOT NULL,
  "APE_NOMBRE" VARCHAR2(200 ) NOT NULL,
  "APE_P_APELLIDO" VARCHAR2(100 ) NOT NULL,
  "APE_S_APELLIDO" VARCHAR2(100 ),
  "APE_FECHA_NACIMIENTO" TIMESTAMP(6) NOT NULL,
  "APE_SEXO" VARCHAR2(10 ),
  "APE_ESTADO_CIVIL" VARCHAR2(15 ),
  "APE_NACIONALIDAD" VARCHAR2(10 ),
  "APE_TIPO_USUARIO" VARCHAR2(15 ) NOT NULL,
  "APE_ESTADO_REGISTRO" VARCHAR2(10 ) NOT NULL,
  "APE_EMAIL" VARCHAR2(255 ) NOT NULL,
  "APE_TELEFONO" VARCHAR2(20 ),
  "APE_RESIDENCIA" VARCHAR2(255 ),
  "APE_DIRECION_CASA" VARCHAR2(255 ),
  "APE_DIRECCION_TRABAJO" VARCHAR2(255 ),
  "APE_FECHA_CREACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "APE_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  CONSTRAINT "CHK_APE_ESTADO_REGISTRO" CHECK (APE_ESTADO_REGISTRO IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
  CONSTRAINT "CHK_APE_SEXO" CHECK (APE_SEXO IN ('MASCULINO', 'FEMENINO')),
  CONSTRAINT "CHK_APE_ESTADO_CIVIL" CHECK (APE_ESTADO_CIVIL IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO', 'UNION LIBRE')),
  CONSTRAINT "CHK_APE_NACIONALIDAD" CHECK (APE_NACIONALIDAD IN ('NACIONAL', 'EXTRANJERO')),
  CONSTRAINT "CHK_APE_TIPO_USUARIO" CHECK (APE_TIPO_USUARIO IN ('MEDICO', 'ADMINISTRATIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_PERSONA

CREATE INDEX "IDX_APE_NOMBRE" ON "ACS_PERSONA" ("APE_NOMBRE","APE_P_APELLIDO","APE_S_APELLIDO")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE UNIQUE INDEX "UQ_APE_CEDULA" ON "ACS_PERSONA" ("APE_CEDULA")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE UNIQUE INDEX "UQ_APE_EMAIL" ON "ACS_PERSONA" ("APE_EMAIL")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_PERSONA

ALTER TABLE "ACS_PERSONA" ADD CONSTRAINT "PK_ACS_PERSONA" PRIMARY KEY ("APE_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PERSONA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR PERSONAL QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_CEDULA" IS 'UNICO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_NOMBRE" IS 'REQUERIDO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_P_APELLIDO" IS 'REQUERIDO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_S_APELLIDO" IS 'OPCIONAL'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_FECHA_NACIMIENTO" IS 'REQUERIDO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_SEXO" IS 'MASCULINO, FEMENINO, OTRO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_TIPO_USUARIO" IS 'EVALUA PARA QUE PUESTO APLICA EL USUARIO, NO CAMBIA UNA VEZ DEFINIDO
VALORES: MEDICO, ADMINISTRATIVO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_ESTADO_REGISTRO" IS 'ESTADO PARA SABER EL TIPO DE ESTADO DE PERSONA, SI ESTA ACEPTADO NO SE BORRA. VALORES: PENDIENTE, ACEPTADO, RECHAZADO
'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_EMAIL" IS 'UNICO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_TELEFONO" IS '+506 8888 8888'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_RESIDENCIA" IS 'LUGAR DONDE VIVE'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_DIRECION_CASA" IS 'DIRECCION EXACTA DONDE VIVE'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_DIRECCION_TRABAJO" IS 'DIRECCION EXACTA DEL LUGAR DE TRABAJO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_FECHA_CREACION" IS 'AUTOMATICO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_FECHA_ACTUALIZACION" IS 'AUTOMATICO'
/

-- TABLE ACS_PERMISO

CREATE TABLE "ACS_PERMISO"(
  "APR_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APR_PANTALLA" VARCHAR2(100 ) NOT NULL,
  "APR_LEER" NUMBER NOT NULL,
  "APR_CREAR" NUMBER NOT NULL,
  "APR_EDITAR" NUMBER NOT NULL,
  "APR_BORRAR" NUMBER NOT NULL,
  CONSTRAINT "CHK_APR_PERMISO_LEER" CHECK (APR_LEER IN (0, 1)),
  CONSTRAINT "CHK_APR_PERMISO_CREAR" CHECK (APR_CREAR IN (0, 1)),
  CONSTRAINT "CHK_APR_PERMISO_EDITAR" CHECK (APR_EDITAR IN (0, 1)),
  CONSTRAINT "CHK_APR_PERMISO_BORRAR" CHECK (APR_BORRAR IN (0, 1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_PERMISO

CREATE UNIQUE INDEX "UQ_APR_PAN_TIU" ON "ACS_PERMISO" ("APR_PANTALLA")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_PERMISO

ALTER TABLE "ACS_PERMISO" ADD CONSTRAINT "PK_ACS_PERMISO" PRIMARY KEY ("APR_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PERMISO" IS 'TABLA PARA DETALLAR LOS PERMISOS QUE PUEDE TENER UN USUARIO EN LAS DIFERENTES PANTALLAS'
/

-- TABLE ACS_CLAVE

CREATE TABLE "ACS_CLAVE"(
  "ACL_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACL_CLAVE" VARCHAR2(500 ) NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_CLAVE

ALTER TABLE "ACS_CLAVE" ADD CONSTRAINT "PK_ACS_CLAVE" PRIMARY KEY ("ACL_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE ACS_TIPO_DOCUMENTO

CREATE TABLE "ACS_TIPO_DOCUMENTO"(
  "ATD_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATD_TIPO_USUARIO" VARCHAR2(15 ) NOT NULL,
  "ATD_DOCUMENTO_REQUERIDO" VARCHAR2(200 ) NOT NULL,
  "ATD_ESTADO" VARCHAR2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT "CHK_ATD_ESTADO" CHECK (ATD_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ATD_TIPO_USUARIO" CHECK (ATD_TIPO_USUARIO IN ('MEDICO', 'ADMINISTRATIVO', 'TODOS'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_TIPO_DOCUMENTO

CREATE UNIQUE INDEX "UQ_ATD_TIPO_U_X_ATD_DOCU_R" ON "ACS_TIPO_DOCUMENTO" ("ATD_TIPO_USUARIO","ATD_DOCUMENTO_REQUERIDO")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_TIPO_DOCUMENTO

ALTER TABLE "ACS_TIPO_DOCUMENTO" ADD CONSTRAINT "PK_ACS_TIPO_DOCUMENTO" PRIMARY KEY ("ATD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_TIPO_DOCUMENTO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR TIPO DE DOCUMENTO QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_TIPO_DOCUMENTO"."ATD_TIPO_USUARIO" IS 'MEDICO, ADMINISTRATIVO, TODOS'
/
COMMENT ON COLUMN "ACS_TIPO_DOCUMENTO"."ATD_DOCUMENTO_REQUERIDO" IS 'NOMBRE DOCUEMNTO SOLICITADO'
/
COMMENT ON COLUMN "ACS_TIPO_DOCUMENTO"."ATD_ESTADO" IS 'ESTADO: ACTIVO, INACTIVO. PARA VISIBILIDAD '
/

-- TABLE ACS_PUESTOXCENTRO

CREATE TABLE "ACS_PUESTOXCENTRO"(
  "APC_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACM_ID" NUMBER NOT NULL,
  "APM_ID" NUMBER NOT NULL,
  "APC_ESTADO" VARCHAR2(10 ) NOT NULL,
  CONSTRAINT "CHK_APC_ESTADO" CHECK (APC_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PUESTOXCENTRO

ALTER TABLE "ACS_PUESTOXCENTRO" ADD CONSTRAINT "PK_ACS_PUESTOXCENTRO" PRIMARY KEY ("APC_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PUESTOXCENTRO" IS 'TABLA PARA RELACIONAR LOS CENTROS DE SALUD CON EL PUESTO MEDICO, YA QUE UN CENTRO PUEDE TENER MUCHOS PUESTOS Y UN PUESTO PUEDE ESTAR EN MUCHO CENTROS'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."APC_ID" IS 'ID PROPIO DE LA TABLA INTERMEDIA'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."ACM_ID" IS 'ID DE RELACIÓN CON EL CENTRO MEDICO
'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."APM_ID" IS 'ID DE RELACIÓN CON EL PUESTO MEDICO
'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."APC_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA LA RELACIÓN DE PUESTO CON EL CENTRO MEDICO'
/

-- TABLE ACS_PROCEDIMIENTOXCENTRO

CREATE TABLE "ACS_PROCEDIMIENTOXCENTRO"(
  "APRC_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APRC_COSTO" NUMBER NOT NULL,
  "APRC_PAGO" NUMBER NOT NULL,
  "APRC_ESTADO" VARCHAR2(30 ) NOT NULL,
  "ACM_ID" NUMBER NOT NULL,
  "APD_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_APRC_ESTADO" CHECK (APRC_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PROCEDIMIENTOXCENTRO

ALTER TABLE "ACS_PROCEDIMIENTOXCENTRO" ADD CONSTRAINT "PK_ACS_PROCEDIMIENTOXCENTRO" PRIMARY KEY ("APRC_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PROCEDIMIENTOXCENTRO" IS 'TABLA PARA RELACIONAR LOS CENTROS DE SALUD CON UN LOS PROCEDIMIENTOS MEDICOS, YA QUE UN CENTRO PUEDE TENER MUCHOS PROCEDIMIENTOS Y UN PROCEDIMIENTO PUEDE REALIZARCE EN MUCHO CENTROS'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_ID" IS 'ID PROPIO DE LA TABLA INTERMEDIA'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_COSTO" IS 'COSTO QUE SUPONE PARA EL CENTRO MEDICO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_PAGO" IS 'PAGO QUE SE LE HACE AL MEDICO
'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA EL PRODECIMIENTO APLICADO EN EL CENTRO MEDICO
'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."ACM_ID" IS 'ID DE RELACIÓN CON EL CENTRO MEDICO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APD_ID" IS 'ID DE RELACIÓN CON EL PROCEDIMIENTO
'
/

-- TABLE ACS_PERSONAL_TIPO_PLANILLA

CREATE TABLE "ACS_PERSONAL_TIPO_PLANILLA"(
  "APTP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APTP_ACTIVO" NUMBER NOT NULL,
  "APTP_FECHA_ASIGNACION" TIMESTAMP(6) NOT NULL,
  "AUS_ID" NUMBER NOT NULL,
  "ATP_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_APTP_ACTIVO" CHECK (APTP_ACTIVO IN (0,1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PERSONAL_TIPO_PLANILLA

ALTER TABLE "ACS_PERSONAL_TIPO_PLANILLA" ADD CONSTRAINT "PK_ACS_PERSONAL_TIPO_PLANILLA" PRIMARY KEY ("APTP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PERSONAL_TIPO_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR PERSONAL DEL TIPO DE PLANILLA QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."APTP_ID" IS 'IDENTIFICADOR ÚNICO DE LA ASIGNACIÓN'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."APTP_ACTIVO" IS 'INDICA SI LA ASIGNACIÓN ESTÁ ACTIVA'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."APTP_FECHA_ASIGNACION" IS 'FECHA DE ASIGNACIÓN'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."AUS_ID" IS 'USUARIO ASIGNADO AL TIPO DE PLANILLA'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."ATP_ID" IS 'TIPO DE PLANILLA ASIGNADO'
/

-- TABLE ACS_BITACORA_PLANILLA

CREATE TABLE "ACS_BITACORA_PLANILLA"(
  "ABP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ABP_ACCION" VARCHAR2(30 ) NOT NULL,
  "ABP_DETALLE" VARCHAR2(30 ),
  "ABP_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "APL_ID" NUMBER NOT NULL,
  "AUS_ID" NUMBER
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_BITACORA_PLANILLA

ALTER TABLE "ACS_BITACORA_PLANILLA" ADD CONSTRAINT "PK_ACS_BITACORA_PLANILLA" PRIMARY KEY ("ABP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_BITACORA_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR BITACORA DE PLANILLA QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_ID" IS 'IDENTIFICADOR DE BITÁCORA'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_ACCION" IS 'ACCIÓN (CREAR, APROBAR, ETC.)'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_DETALLE" IS 'OBSERVACIONES'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_FECHA_CREACION" IS 'FECHA DE CREACIÓN DEL REGISTRO'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."APL_ID" IS 'PLANILLA RELACIONADA'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."AUS_ID" IS 'USUARIO QUE EJECUTÓ LA ACCIÓN'
/

-- TABLE ACS_ENVIO_COMP

CREATE TABLE "ACS_ENVIO_COMP"(
  "AEC_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AEC_EMAIL" VARCHAR2(30 ) NOT NULL,
  "AEC_FECHA_ENVIO" TIMESTAMP(6) NOT NULL,
  "AEC_ERROR" VARCHAR2(30 ),
  "APD_ID" NUMBER NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_ENVIO_COMP

ALTER TABLE "ACS_ENVIO_COMP" ADD CONSTRAINT "PK_ACS_ENVIO_COMP" PRIMARY KEY ("AEC_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_ENVIO_COMP" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR ENVIOS DE COMPROBANTES QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_ID" IS 'IDENTIFICADOR'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_EMAIL" IS 'EMAIL DESTINO'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_FECHA_ENVIO" IS 'FECHA DE ENVÍO'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_ERROR" IS 'ERROR EN EL ENVÍO SI APLICA'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."APD_ID" IS 'DETALLE DE PLANILLA NOTIFICADO'
/

-- TABLE ACS_MOVIMIENTO_PLANILLA

CREATE TABLE "ACS_MOVIMIENTO_PLANILLA"(
  "AMP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AMP_FUENTE" VARCHAR2(20 ) NOT NULL,
  "AMP_MONTO" NUMBER NOT NULL,
  "AMP_OBS" VARCHAR2(255 ),
  "AMP_CALC" NUMBER NOT NULL,
  "AMP_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "APD_ID" NUMBER NOT NULL,
  "ATM_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_AMP_FUENTE" CHECK (AMP_FUENTE IN ('AUTOMATICO', 'MANUAL'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_MOVIMIENTO_PLANILLA

ALTER TABLE "ACS_MOVIMIENTO_PLANILLA" ADD CONSTRAINT "PK_ACS_MOVIMIENTO_PLANILLA" PRIMARY KEY ("AMP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_MOVIMIENTO_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR MOVIMIENTOS DE PLANILLAS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_ID" IS 'IDENTIFICADOR'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_FUENTE" IS 'FUENTE (AUTOMATICO O MANUAL)'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_MONTO" IS 'MONTO APLICADO'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_OBS" IS 'OBSERVACIÓN'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_CALC" IS 'TRAZA DE CÁLCULO'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."APD_ID" IS 'DETALLE DE PLANILLA AL QUE APLICA EL MOVIMIENTO'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."ATM_ID" IS 'TIPO DE MOVIMIENTO'
/

-- TABLE ACS_TIPO_MOV

CREATE TABLE "ACS_TIPO_MOV"(
  "ATM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATM_COD" VARCHAR2(40 ) NOT NULL,
  "ATM_NOMBRE" VARCHAR2(120 ) NOT NULL,
  "ATM_NATURALEZA" VARCHAR2(20 ) NOT NULL,
  "ATM_APLICA_A" VARCHAR2(20 ) NOT NULL,
  "ATM_MODO" VARCHAR2(20 ) NOT NULL,
  "ATM_BASE" VARCHAR2(20 ) NOT NULL,
  "ATM_PORC" NUMBER,
  "ATM_MONTO_FIJO" NUMBER,
  "ATM_ES_AUTOMATICO" NUMBER NOT NULL,
  "ATM_PRIORIDAD" NUMBER NOT NULL,
  "ATM_ESTADO" VARCHAR2(10 ) NOT NULL,
  "ATM_REGLA" CLOB,
  "ATM_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "ATM_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  CONSTRAINT "CHK_ATM_APLICA_A" CHECK (ATM_APLICA_A IN ('MEDICO', 'ADMINISTRATIVO', 'AMBOS')),
  CONSTRAINT "CHK_ATM_BASE" CHECK (ATM_BASE IN ('BRUTO', 'SALARIO_BASE', 'HORAS', 'PROCEDIMIENTOS', 'PERSONALIZADA')),
  CONSTRAINT "CHK_ATM_ES_AUTOMATICO" CHECK (ATM_ES_AUTOMATICO IN (0,1)),
  CONSTRAINT "CHK_ATM_ESTADO" CHECK (ATM_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ATM_MODO" CHECK (ATM_MODO IN ('FIJO', 'PORCENTAJE')),
  CONSTRAINT "CHK_ATM_NATURALEZA" CHECK (ATM_NATURALEZA IN ('INGRESO', 'DEDUCCION'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_TIPO_MOV

ALTER TABLE "ACS_TIPO_MOV" ADD CONSTRAINT "PK_ACS_TIPO_MOV" PRIMARY KEY ("ATM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_TIPO_MOV" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR TIPOS DE MOVIMIENTO QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_ID" IS 'IDENTIFICADOR DE MOVIMIENTO'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_COD" IS 'CÓDIGO CORTO (RENTA, CAJA, ETC.)'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_NOMBRE" IS 'NOMBRE COMPLETO'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_NATURALEZA" IS 'NATURALEZA: INGRESO/DEDUCCION'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_APLICA_A" IS 'APLICA A (MEDICO/ADMIN/AMBOS)'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_MODO" IS 'FIJO O PORCENTAJE'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_BASE" IS 'BASE DE CÁLCULO'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_PORC" IS 'PORCENTAJE SI APLICA'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_MONTO_FIJO" IS 'MONTO FIJO SI APLICA'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_ES_AUTOMATICO" IS 'AUTOMÁTICO (1) O MANUAL (0)'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_PRIORIDAD" IS 'ORDEN DE APLICACIÓN'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_ESTADO" IS 'ESTADO DEL TIPO DE MOVIMIENTO.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_REGLA" IS 'REGLAS JSON COMPLEJAS PARA TRAMOS.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_FECHA_ACTUALIZACION" IS 'FECHA DE ÚLTIMA ACTUALIZACIÓN'
/

-- TABLE ACS_DETALLE_PLANILLA

CREATE TABLE "ACS_DETALLE_PLANILLA"(
  "ADP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADP_TIPO_PERSONA" VARCHAR2(30 ) NOT NULL,
  "ADP_SALARIO_BASE" NUMBER NOT NULL,
  "ADP_BRUTO" NUMBER NOT NULL,
  "ADP_DED" NUMBER NOT NULL,
  "APD_NETO" NUMBER NOT NULL,
  "ADP_FECHA_NOTIFICACION" TIMESTAMP(6),
  "ADP_EMAIL_ENV" NUMBER NOT NULL,
  "ADP_COMPROBANTE_HTML" CLOB,
  "ADP_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  "ADP_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "APL_ID" NUMBER NOT NULL,
  "AUS_ID" NUMBER,
  "ACB_ID" NUMBER,
  CONSTRAINT "CHK_ADP_TIPO_PERSONA" CHECK (ADP_TIPO_PERSONA IN ('MEDICO', 'ADMINISTRATIVO')),
  CONSTRAINT "CHL_ADP_EMAIL_ENV" CHECK (ADP_EMAIL_ENV IN (0,1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_DETALLE_PLANILLA

ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "PK_ACS_DETALLE_PLANILLA" PRIMARY KEY ("ADP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_DETALLE_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR DETALLES DE PLANILLAS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_ID" IS 'IDENTIFICADOR DEL DETALLE'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_TIPO_PERSONA" IS 'TIPO DE PERSONAL (MEDICO/ADMIN)'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_SALARIO_BASE" IS 'SALARIO BASE (ADMINS)'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_BRUTO" IS 'BRUTO GENERADO'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_DED" IS 'TOTAL DEDUCCIONES'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."APD_NETO" IS 'NETO A PAGAR'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_FECHA_NOTIFICACION" IS 'FECHA DE NOTIFICACIÓN'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_EMAIL_ENV" IS 'INDICADOR SI SE ENVIÓ COMPROBANTE'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_COMPROBANTE_HTML" IS 'COMPROBANTE HTML'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_FECHA_ACTUALIZACION" IS 'FECHA DE ÚLTIMA ACTUALIZACIÓN'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."APL_ID" IS 'PLANILLA A LA QUE PERTENECE EL DETALLE'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."AUS_ID" IS 'IDENTIFICADOR DEL USUARIO'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ACB_ID" IS 'CUENTA BANCARIA PRINCIPAL PARA DEPÓSITO'
/

-- TABLE ACS_PLANILLA

CREATE TABLE "ACS_PLANILLA"(
  "APL_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APL_ANIO" NUMBER NOT NULL,
  "APL_MES" NUMBER NOT NULL,
  "APL_ESTADO" VARCHAR2(20 ) NOT NULL,
  "APL_FEC_GEN" TIMESTAMP(6),
  "APL_FEC_APR" TIMESTAMP(6),
  "APL_FEC_PRO" TIMESTAMP(6),
  "APL_FEC_NOT" TIMESTAMP(6),
  "APL_TOT_BRUTO" NUMBER NOT NULL,
  "APL_TOT_DED" NUMBER NOT NULL,
  "APL_TOT_NETO" NUMBER NOT NULL,
  "APL_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "APL_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  "ATP_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_APL_ANIO" CHECK (APL_ANIO >= 2000),
  CONSTRAINT "CHK_APL_ESTADO" CHECK (APL_ESTADO IN ('CONSTRUCCION', 'APROBADA', 'PROCESADA', 'NOTIFICADA')),
  CONSTRAINT "CHK_APL_MES" CHECK (APL_MES BETWEEN 1 AND 12)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PLANILLA

ALTER TABLE "ACS_PLANILLA" ADD CONSTRAINT "PK_ACS_PLANILLA" PRIMARY KEY ("APL_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR PLANILLAS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_ID" IS 'IDENTIFICADOR DE LA PLANILLA'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_ANIO" IS 'AÑO DE LA PLANILLA'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_MES" IS 'MES DE LA PLANILLA'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_ESTADO" IS 'ESTADO DEL CICLO'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_GEN" IS 'FECHA DE GENERACIÓN'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_APR" IS 'FECHA DE APROBACIÓN'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_PRO" IS 'FECHA DE PROCESADO'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_NOT" IS 'FECHA DE NOTIFICACIÓN'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_TOT_BRUTO" IS 'TOTAL BRUTO'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_TOT_DED" IS 'TOTAL DEDUCCIONES'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_TOT_NETO" IS 'TOTAL NETO'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FECHA_ACTUALIZACION" IS 'FECHA DE ÚLTIMA ACTUALIZACIÓN'
/
COMMENT ON COLUMN "ACS_PLANILLA"."ATP_ID" IS 'TIPO DE PLANILLA RELACIONADA'
/

-- TABLE ACS_TIPO_PLANILLA

CREATE TABLE "ACS_TIPO_PLANILLA"(
  "ATP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATP_NOMBRE" VARCHAR2(80 ) NOT NULL,
  "ATP_APLICA_A" VARCHAR2(20 ) NOT NULL,
  "ATP_DESC" VARCHAR2(255 ) NOT NULL,
  "ATP_ESTADO" VARCHAR2(10 ) NOT NULL,
  "ATP_DESCRIPCION" VARCHAR2(255 ),
  CONSTRAINT "CHK_ATP_APLICA_A" CHECK (ATP_APLICA_A IN ('MEDICO', 'ADMINISTRATIVO', 'AMBOS')),
  CONSTRAINT "CHL_ATP_ESTADO" CHECK (ATP_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_TIPO_PLANILLA

ALTER TABLE "ACS_TIPO_PLANILLA" ADD CONSTRAINT "PK_ACS_TIPO_PLANILLA" PRIMARY KEY ("ATP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_TIPO_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR TIPOS DE PLANILLA QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_ID" IS 'ID DE LA PLANILLA'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_NOMBRE" IS 'NOMBRE DE LA PLANILLA'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_APLICA_A" IS 'A QUIÉN APLICA (MEDICO/ADMIN/AMBOS)'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_DESC" IS 'DESCRIPCIÓN OPCIONAL'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_ESTADO" IS 'ESTADO DEL REGISTRO'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_DESCRIPCION" IS 'DESCRIPCIÓN DE LA PLANILLA.'
/

-- TABLE ACS_TURNO_PLANILLA

CREATE TABLE "ACS_TURNO_PLANILLA"(
  "ATRP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATRP_HORAS" NUMBER NOT NULL,
  "ATRP_MONTO_COBRADO_CENTRO" NUMBER NOT NULL,
  "ATRP_MONTO_PAGADO_MEDICO" NUMBER NOT NULL,
  "ATRP_PROCESADO" NUMBER NOT NULL,
  "ATRP_FECHA_PROCESAMIENTO" TIMESTAMP(6),
  "ADP_ID" NUMBER NOT NULL,
  "ADM_ID" NUMBER NOT NULL,
  CONSTRAINT "CHK_ATRP_PROCESADO" CHECK (ATRP_PROCESADO IN (0,1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_TURNO_PLANILLA

ALTER TABLE "ACS_TURNO_PLANILLA" ADD CONSTRAINT "PK_ACS_TURNO_PLANILLA" PRIMARY KEY ("ATRP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_TURNO_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR TURNOS DE PLANILLAS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_ID" IS 'IDENTIFICADOR ÚNICO DEL TURNO PROCESADO EN PLANILLA'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_HORAS" IS 'HORAS TRABAJADAS'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_MONTO_COBRADO_CENTRO" IS 'MONTO COBRADO AL CENTRO DE SALUD'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_MONTO_PAGADO_MEDICO" IS 'MONTO PAGADO AL MÉDICO'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_PROCESADO" IS 'INDICA SI FUE PROCESADO'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_FECHA_PROCESAMIENTO" IS 'FECHA DE PROCESAMIENTO'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ADP_ID" IS 'DETALLE DE PLANILLA ASOCIADO'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ADM_ID" IS 'TURNO MENSUAL REGISTRADO'
/

-- TABLE ACS_PROCEDIMIENTO_PLANILLA

CREATE TABLE "ACS_PROCEDIMIENTO_PLANILLA"(
  "APRP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADP_ID" NUMBER NOT NULL,
  "APA_ID" NUMBER NOT NULL,
  "ACM_ID" NUMBER,
  "APRP_CANTIDAD" NUMBER NOT NULL,
  "APRP_MONTO_COBRADO" NUMBER NOT NULL,
  "APRP_MONTO_PAGADO_MEDICO" NUMBER NOT NULL,
  "APRP_ESTADO" VARCHAR2(10 ) NOT NULL,
  "APRP_PROCESADO" NUMBER NOT NULL,
  "APRP_FECHA_PROCESAMIENTO" TIMESTAMP(6),
  CONSTRAINT "CHK_APRP_PROCESADO" CHECK (APRP_PROCESADO IN (0,1)),
  CONSTRAINT "CHK_APRP_ESTADO" CHECK (APRP_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PROCEDIMIENTO_PLANILLA

ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "PK_ACS_PROCEDIMIENTO_PLANILLA" PRIMARY KEY ("APRP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PROCEDIMIENTO_PLANILLA" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR PROCEDIMIENTO DE PLANILLA QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_ID" IS 'IDENTIFICADOR ÚNICO DEL PROCEDIMIENTO PROCESADO EN PLANILLA'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."ADP_ID" IS 'DETALLE DE PLANILLA ASOCIADO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APA_ID" IS 'PROCEDIMIENTO APLICADO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."ACM_ID" IS 'CENTRO MÉDICO RELACIONADO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_CANTIDAD" IS 'CANTIDAD DE PROCEDIMIENTOS'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_MONTO_COBRADO" IS 'MONTO COBRADO AL CENTRO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_MONTO_PAGADO_MEDICO" IS 'MONTO PAGADO AL MÉDICO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_ESTADO" IS 'ESTADO EN EL QUE SE ENCUENTRA '
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_PROCESADO" IS 'INDICA SI FUE PROCESADO'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_FECHA_PROCESAMIENTO" IS 'FECHA PROCESAMIENTO.'
/

-- TABLE ACS_ASIENTO_FINANCIERO

CREATE TABLE "ACS_ASIENTO_FINANCIERO"(
  "AAF_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AAF_TIPO" VARCHAR2(10 ) NOT NULL,
  "AAF_FUENTE" VARCHAR2(30 ) NOT NULL,
  "AAF_FECHA" TIMESTAMP(6) NOT NULL,
  "AAF_PERIODO_ANIO" NUMBER NOT NULL,
  "AAF_PERIODO_MES" NUMBER NOT NULL,
  "AAF_MONTO" NUMBER NOT NULL,
  "AAF_REFERENCIA_ID" NUMBER,
  "AAF_DETALLE" VARCHAR2(255 ),
  "AAF_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "AAF_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  "ACM_ID" NUMBER,
  CONSTRAINT "CHK_AAF_FUENTE" CHECK (AAF_FUENTE IN ('TURNO', 'PROCEDIMIENTO', 'PLANILLA_ADMINISTRATIVA', 'PLANILLA_MEDICA', 'AJUSTE')),
  CONSTRAINT "CHK_AAF_PERIODO_MES" CHECK (AAF_PERIODO_MES BETWEEN 1 AND 12),
  CONSTRAINT "CHK_AAF_TIPO" CHECK (AAF_TIPO IN ('INGRESO', 'GASTO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_ASIENTO_FINANCIERO

ALTER TABLE "ACS_ASIENTO_FINANCIERO" ADD CONSTRAINT "PK_ACS_ASIENTO_FINANCIERO" PRIMARY KEY ("AAF_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_ASIENTO_FINANCIERO" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR ASIENTOS FINANCIEROS QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_ID" IS 'IDENTIFICADOR ÚNICO DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_TIPO" IS 'NATURALEZA DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FUENTE" IS 'ORIGEN DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FECHA" IS 'FECHA Y HORA DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_PERIODO_ANIO" IS 'AÑO CONTABLE DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_PERIODO_MES" IS 'MES CONTABLE DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_MONTO" IS 'MONTO DEL ASIENTO (POSITIVO)'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_REFERENCIA_ID" IS 'IDENTIFICADOR DE REFERENCIA AL ORIGEN '
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_DETALLE" IS 'DESCRIPCIÓN BREVE DEL ASIENTO'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FECHA_ACTUALIZACION" IS 'FECHA DE ÚLTIMA ACTUALIZACIÓN'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."ACM_ID" IS 'CENTRO DE SALUD ASOCIADO '
/

-- TABLE ACS_RESUMEN_FIN_MENSUAL

CREATE TABLE "ACS_RESUMEN_FIN_MENSUAL"(
  "ARM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ARM_PERIODO_ANIO" NUMBER NOT NULL,
  "ARM_PERIODO_MES" NUMBER NOT NULL,
  "ARM_INGRESOS" NUMBER NOT NULL,
  "ARM_GASTOS" NUMBER NOT NULL,
  "ARM_UTILIDAD" NUMBER NOT NULL,
  "ARM_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "ARM_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  CONSTRAINT "CHK_ARM_PERIODO_ANIO" CHECK (ARM_PERIODO_ANIO >= 2000),
  CONSTRAINT "CHK_ARM_PERIODO_MES" CHECK (ARM_PERIODO_MES BETWEEN 1 AND 12)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_RESUMEN_FIN_MENSUAL

ALTER TABLE "ACS_RESUMEN_FIN_MENSUAL" ADD CONSTRAINT "PK_ACS_RESUMEN_FIN_MENSUAL" PRIMARY KEY ("ARM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_RESUMEN_FIN_MENSUAL" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR LOS RESUMENES DE FIN DE MES QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_ID" IS 'IDENTIFICADOR DEL RESUMEN MENSUAL'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_PERIODO_ANIO" IS 'AÑO DEL RESUMEN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_PERIODO_MES" IS 'MES DEL RESUMEN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_INGRESOS" IS 'TOTAL DE INGRESOS DEL MES'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_GASTOS" IS 'TOTAL DE GASTOS DEL MES'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_UTILIDAD" IS 'INGRESOS − GASTOS'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_FECHA_ACTUALIZACION" IS 'FECHA DE ÚLTIMA ACTUALIZACIÓN'
/

-- TABLE ACS_RESUMEN_FIN_CENTRO_MES

CREATE TABLE "ACS_RESUMEN_FIN_CENTRO_MES"(
  "ARCM_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ARCM_PERIODO_ANIO" NUMBER NOT NULL,
  "ARCM_PERIODO_MES" NUMBER NOT NULL,
  "ARCM_INGRESOS" NUMBER NOT NULL,
  "ARCM_GASTOS" NUMBER NOT NULL,
  "ARCM_UTILIDAD" NUMBER NOT NULL,
  "ARCM_FECHA_CREACION" TIMESTAMP(6) NOT NULL,
  "ARCM_FECHA_ACTUALIZACION" TIMESTAMP(6) NOT NULL,
  "ACM_ID" NUMBER,
  CONSTRAINT "CHK_ARCM_PERIODO_ANIO" CHECK (ARCM_PERIODO_ANIO >= 2000),
  CONSTRAINT "CHK_ARCM_PERIODO_MES" CHECK (ARCM_PERIODO_MES BETWEEN 1 AND 12)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_RESUMEN_FIN_CENTRO_MES

ALTER TABLE "ACS_RESUMEN_FIN_CENTRO_MES" ADD CONSTRAINT "PK_ACS_RESUMEN_FIN_CENTRO_MES" PRIMARY KEY ("ARCM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_RESUMEN_FIN_CENTRO_MES" IS 'TABLA PARA REPRESENTA, MANEJAR Y ALMACENAR LOS RESUMENES FINALES DE CENTROS MENSUALES QUE HAY EN EL SISTEMA'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_ID" IS 'IDENTIFICADOR DEL RESUMEN POR CENTRO'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_PERIODO_ANIO" IS ' AÑO DEL RESUMEN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_PERIODO_MES" IS 'MES DEL RESUMEN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_INGRESOS" IS 'TOTAL DE INGRESOS DEL CENTRO EN EL MES'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_GASTOS" IS 'TOTAL DE GASTOS DEL CENTRO EN EL MES'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_UTILIDAD" IS 'GASTOS DEL CENTRO, INGRESOS.'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_FECHA_CREACION" IS 'FECHA DE CREACIÓN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_FECHA_ACTUALIZACION" IS 'FECHA DE ÚLTIMA ACTUALIZACIÓN'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ACM_ID" IS 'CENTRO DE SALUD'
/

-- TABLE ACS_AUDITORIA_CENTRAL

CREATE TABLE "ACS_AUDITORIA_CENTRAL"(
  "AUD_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AUD_OBJETO" VARCHAR2(100 ) NOT NULL,
  "AUD_OBJ_ID" VARCHAR2(4000 ) NOT NULL,
  "AUD_CAMPO" VARCHAR2(100 ) NOT NULL,
  "AUD_VALOR_ANTERIOR" CLOB,
  "AUD_VALOR_NUEVO" CLOB,
  "AUD_USUARIO" VARCHAR2(100 ),
  "AUD_OPERACION" VARCHAR2(15 ) NOT NULL,
  "AUD_FECHA_CAMBIO" TIMESTAMP(6) NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_AUDITORIA_CENTRAL

ALTER TABLE "ACS_AUDITORIA_CENTRAL" ADD CONSTRAINT "PK_ACS_AUDITORIA_CENTRAL" PRIMARY KEY ("AUD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_AUDITORIA_CENTRAL" IS 'TABLA DE AUDITORÍA GENERAL PARA TENER UN MANEJO DE QUE SE CAMBIÓ, QUIEN LO HIZO Y CUANDO LO HIZO'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_ID" IS 'ID PROPIO DEL REGISTRO'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_OBJETO" IS 'NOMBRE DE LA TABLA AFECTADA'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_OBJ_ID" IS 'ID DEL REGISTRO AFECTADO '
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_CAMPO" IS 'CAMPO QUE CAMBIÓ'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_VALOR_ANTERIOR" IS 'VALOR ANTERIOR (CLOB PARA SOPORTAR TEXTOS LARGOS)'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_VALOR_NUEVO" IS 'VALOR NUEVO'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_USUARIO" IS 'USUARIO QUE HIZO EL CAMBIO'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_OPERACION" IS '''INSERT'', ''UPDATE'', ''DELETE'' ...'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_FECHA_CAMBIO" IS 'FECHA EN LA QUE SE REALIZÓ EL CAMBIO'
/

-- TABLE ACS_PADRON

CREATE TABLE "ACS_PADRON"(
  "APN_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APN_CEDULA" VARCHAR2(9 ) NOT NULL,
  "APN_CODELEC" VARCHAR2(6 ) NOT NULL,
  "APN_RELLENO" VARCHAR2(1 ) NOT NULL,
  "APN_FECHA_CADUC" TIMESTAMP(6) NOT NULL,
  "APN_JUNTA" VARCHAR2(30 ) NOT NULL,
  "APN_NOMBRE" VARCHAR2(30 ) NOT NULL,
  "APN_P_APELLIDO" VARCHAR2(30 ) NOT NULL,
  "APN_S_APELLIDO" VARCHAR2(30 ) NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- ADD KEYS FOR TABLE ACS_PADRON

ALTER TABLE "ACS_PADRON" ADD CONSTRAINT "PK_ACS_PADRON" PRIMARY KEY ("APN_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE AND COLUMNS COMMENTS SECTION

COMMENT ON TABLE "ACS_PADRON" IS 'TABLA DE PADRON PARA PODER TENER UN LISTADO DE USUARIOS '
/
COMMENT ON COLUMN "ACS_PADRON"."APN_ID" IS 'ID PROPIO DEL REGISTRO'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_CEDULA" IS 'CEDULA DEL CIUDADANO '
/
COMMENT ON COLUMN "ACS_PADRON"."APN_CODELEC" IS 'CODIGO ELECTORAL DONDE EST  INSCRITO'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_RELLENO" IS 'CAMPO QUE CAMBIÓ'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_FECHA_CADUC" IS 'FECHA VENCIMIENTO DE LA CEDULA'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_JUNTA" IS 'JUNTA RECEPTORA DE VOTOS'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_NOMBRE" IS 'NOMBRE COMPLETO DEL CIUDADANO'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_P_APELLIDO" IS 'PRIMER APELLIDO'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_S_APELLIDO" IS 'SEGUNDO APELLIDO'
/

-- TABLE ACS_PERFIL

CREATE TABLE "ACS_PERFIL"(
  "APF_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APF_NOMBRE" CHAR(100 ) NOT NULL,
  "APF_DESCRIPCION" CHAR(400 ),
  "APF_PADRE_ID" NUMBER
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_PERFIL

CREATE UNIQUE INDEX "UQ_APF_NOMBRE" ON "ACS_PERFIL" ("APF_NOMBRE")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "APF_X_APF" ON "ACS_PERFIL" ("APF_PADRE_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_PERFIL

ALTER TABLE "ACS_PERFIL" ADD CONSTRAINT "PK_ACS_PERFIL" PRIMARY KEY ("APF_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- TABLE ACS_PERFIL_PERMISO

CREATE TABLE "ACS_PERFIL_PERMISO"(
  "APP_ID" NUMBER GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APR_ID" NUMBER NOT NULL,
  "APF_ID" NUMBER NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- CREATE INDEXES FOR TABLE ACS_PERFIL_PERMISO

CREATE INDEX "APP_X_APR" ON "ACS_PERFIL_PERMISO" ("APR_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "APP_X_APF" ON "ACS_PERFIL_PERMISO" ("APF_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- ADD KEYS FOR TABLE ACS_PERFIL_PERMISO

ALTER TABLE "ACS_PERFIL_PERMISO" ADD CONSTRAINT "PK_ACS_PERFIL_PERMISO" PRIMARY KEY ("APP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/


-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION ------------------------------------------------- 

ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "APA_X_APD" FOREIGN KEY ("APD_ID") REFERENCES "ACS_PROCEDIMIENTO" ("APD_ID")
/



ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "APA_X_AME" FOREIGN KEY ("AME_ID") REFERENCES "ACS_MEDICO" ("AME_ID")
/



ALTER TABLE "ACS_ESCALA_MENSUAL" ADD CONSTRAINT "AEM_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_AEM" FOREIGN KEY ("AEM_ID") REFERENCES "ACS_ESCALA_MENSUAL" ("AEM_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_APM" FOREIGN KEY ("APM_ID") REFERENCES "ACS_PUESTO_MEDICO" ("APM_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_ATU" FOREIGN KEY ("ATU_ID") REFERENCES "ACS_TURNO" ("ATU_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_AME" FOREIGN KEY ("AME_ID") REFERENCES "ACS_MEDICO" ("AME_ID")
/



ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "ADU_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_CUENTA_BANCARIA" ADD CONSTRAINT "ACB_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_CUENTA_BANCARIA" ADD CONSTRAINT "ACB_X_ABA" FOREIGN KEY ("ABA_ID") REFERENCES "ACS_BANCO" ("ABA_ID")
/



ALTER TABLE "ACS_PUESTOXCENTRO" ADD CONSTRAINT "APC_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PUESTOXCENTRO" ADD CONSTRAINT "APC_X_APM" FOREIGN KEY ("APM_ID") REFERENCES "ACS_PUESTO_MEDICO" ("APM_ID")
/



ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "ADU_X_ATD" FOREIGN KEY ("ATD_ID") REFERENCES "ACS_TIPO_DOCUMENTO" ("ATD_ID")
/



ALTER TABLE "ACS_USUARIO" ADD CONSTRAINT "AUS_X_APE" FOREIGN KEY ("APE_ID") REFERENCES "ACS_PERSONA" ("APE_ID")
/



ALTER TABLE "ACS_ADMINISTRATIVO" ADD CONSTRAINT "AAD_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_MEDICO" ADD CONSTRAINT "AME_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_BITACORA_PLANILLA" ADD CONSTRAINT "ABP_X_APL" FOREIGN KEY ("APL_ID") REFERENCES "ACS_PLANILLA" ("APL_ID")
/



ALTER TABLE "ACS_PLANILLA" ADD CONSTRAINT "APL_X_ADP" FOREIGN KEY ("ATP_ID") REFERENCES "ACS_TIPO_PLANILLA" ("ATP_ID")
/



ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "ADP_X_APL" FOREIGN KEY ("APL_ID") REFERENCES "ACS_PLANILLA" ("APL_ID")
/



ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "ADP_X_ACB" FOREIGN KEY ("ACB_ID") REFERENCES "ACS_CUENTA_BANCARIA" ("ACB_ID")
/



ALTER TABLE "ACS_MOVIMIENTO_PLANILLA" ADD CONSTRAINT "AMP_X_ADP" FOREIGN KEY ("APD_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_MOVIMIENTO_PLANILLA" ADD CONSTRAINT "ATM_X_AMP" FOREIGN KEY ("ATM_ID") REFERENCES "ACS_TIPO_MOV" ("ATM_ID")
/



ALTER TABLE "ACS_ENVIO_COMP" ADD CONSTRAINT "AEC_X_ADP" FOREIGN KEY ("APD_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_BITACORA_PLANILLA" ADD CONSTRAINT "AUS_X_ABP" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_PERSONAL_TIPO_PLANILLA" ADD CONSTRAINT "APTP_X_ATP" FOREIGN KEY ("ATP_ID") REFERENCES "ACS_TIPO_PLANILLA" ("ATP_ID")
/



ALTER TABLE "ACS_PERSONAL_TIPO_PLANILLA" ADD CONSTRAINT "APTP_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_TURNO_PLANILLA" ADD CONSTRAINT "ATRP_X_ADP" FOREIGN KEY ("ADP_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_TURNO_PLANILLA" ADD CONSTRAINT "ATRP_X_ADM" FOREIGN KEY ("ADM_ID") REFERENCES "ACS_DETALLE_MENSUAL" ("ADM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "APRP_X_ADP" FOREIGN KEY ("ADP_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "APRP_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "APRP_X_APA" FOREIGN KEY ("APA_ID") REFERENCES "ACS_PROC_APLICADO" ("APA_ID")
/



ALTER TABLE "ACS_ASIENTO_FINANCIERO" ADD CONSTRAINT "AAF_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "ADP_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_RESUMEN_FIN_CENTRO_MES" ADD CONSTRAINT "ARM_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "APA_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTOXCENTRO" ADD CONSTRAINT "APRC_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTOXCENTRO" ADD CONSTRAINT "APRC_X_APD" FOREIGN KEY ("APD_ID") REFERENCES "ACS_PROCEDIMIENTO" ("APD_ID")
/



ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "ADU_X_APF" FOREIGN KEY ("APF_ID") REFERENCES "ACS_PERFIL" ("APF_ID")
/



ALTER TABLE "ACS_PERFIL_PERMISO" ADD CONSTRAINT "APP_X_APR" FOREIGN KEY ("APR_ID") REFERENCES "ACS_PERMISO" ("APR_ID")
/



ALTER TABLE "ACS_PERFIL_PERMISO" ADD CONSTRAINT "APP_X_APF" FOREIGN KEY ("APF_ID") REFERENCES "ACS_PERFIL" ("APF_ID")
/



ALTER TABLE "ACS_PERFIL" ADD CONSTRAINT "APF_X_APF" FOREIGN KEY ("APF_PADRE_ID") REFERENCES "ACS_PERFIL" ("APF_ID")
/



ALTER TABLE "ACS_TURNO" ADD CONSTRAINT "ATU_X_APM" FOREIGN KEY ("APM_ID") REFERENCES "ACS_PUESTO_MEDICO" ("APM_ID")
/



ALTER TABLE "ACS_TURNO" ADD CONSTRAINT "ATU_X_AME" FOREIGN KEY ("AME_ID") REFERENCES "ACS_MEDICO" ("AME_ID")
/



-- CREATE ROLES SECTION -------------------------------------------------

CREATE ROLE "MEDICO"
/
CREATE ROLE "ADMINISTRATIVO"
/
CREATE ROLE "ADMINISTRADOR"
/

-- GRANT PERMISSIONS SECTION -------------------------------------------------


GRANT SELECT ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT UPDATE ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT INSERT ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT DELETE ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT READ ON "ACS_USUARIO" TO "ADMINISTRADOR"
/

