-- * PROCEDIMIENTOS GLOBALES

-- PROCEDIMIENTO DE ENVIO DE CORREO NOTIFICADOR
CREATE OR REPLACE PROCEDURE ACS_PRC_CORREO_NOTIFICADOR (
    P_DESTINATARIO IN VARCHAR2,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2
) 
IS
DECLARE
    -- COSTANTES
    CRLF CONSTANT VARCHAR2(2) := UTL_TCP.CRLF;
    -- CONEXION
    MAIL_CONN UTL_SMTP.CONNECTION;
    -- VARIABLES
    V_REMITENTE VARCHAR2(100);
    V_SMTP_HOST VARCHAR2(100);
    V_SMTP_PORT NUMBER;
BEGIN
    -- OBTENER PARAMETROS
    V_REMITENTE := ACS_FN_OBTENER_PARAMETRO('SMTP_CORREO');
    V_SMTP_HOST := ACS_FN_OBTENER_PARAMETRO('SMTP_HOST');
    V_SMTP_PORT := TO_NUMBER(ACS_FN_OBTENER_PARAMETRO('SMTP_PORT'));
    -- CONECTAR CON HMAILSERVER, LOCAL SIN TLS
    MAIL_CONN := UTL_SMTP.OPEN_CONNECTION(V_SMTP_HOST, V_SMTP_PORT);
    UTL_SMTP.HELO(MAIL_CONN, V_SMTP_HOST);
    -- DE: REMITENTE  A DESTINATARIO
    UTL_SMTP.MAIL(MAIL_CONN, V_REMITENTE);
    UTL_SMTP.RCPT(MAIL_CONN, P_DESTINATARIO);
    -- CONTENIDO DEL CORREO
    UTL_SMTP.OPEN_DATA(MAIL_CONN);
    UTL_SMTP.WRITE_DATA(MAIL_CONN, 
        'From: ' || V_REMITENTE || CRLF ||
        'To: ' || P_DESTINATARIO || CRLF ||
        'Subject: ' || P_ASUNTO || CRLF ||
        'Content-Type: text/html; charset=UTF-8' || CRLF ||
        CRLF ||
        P_MENSAJE);
    UTL_SMTP.CLOSE_DATA(MAIL_CONN);
    UTL_SMTP.QUIT(MAIL_CONN);
    DBMS_OUTPUT.PUT_LINE('Correo enviado correctamente a ' || P_DESTINATARIO);
EXCEPTION
    WHEN OTHERS THEN
        BEGIN
            IF MAIL_CONN IS NOT NULL THEN
                UTL_SMTP.QUIT(MAIL_CONN);
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
        DBMS_OUTPUT.PUT_LINE('Error al enviar correo (ACS_PRC_CORREO_NOTIFICADOR): ' || SQLERRM);
        RAISE_APPLICATION_ERROR(-20001, 'Error al enviar correo (ACS_PRC_CORREO_NOTIFICADOR): ' || SQLERRM);
END;
/

/*
!CAPTURA DEL ERROR AL LLAMAR EL PROCEDIMIENTO, PARA PROCESARLO SEGUN SEA EL CASO.
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20001 THEN
            DBMS_OUTPUT.PUT_LINE('Error específico: ' || SQLERRM);
        ELSE
            DBMS_OUTPUT.PUT_LINE('Otro error: ' || SQLERRM);
        END IF;
*/
