/*
Created: 21/8/2025
Modified: 2/11/2025
Project: Administración de Centros de Salud ( ACS )
Model: Oracle 19c
Company: UNA
Author: EGRANADOS - JCAMACHO - FMORA
Version: 1.0
Database: Oracle 19c
*/


-- Create tables section -------------------------------------------------

-- Table ACS_PUESTO_MEDICO

CREATE TABLE "ACS_PUESTO_MEDICO"(
  "APM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APM_NOMBRE" Varchar2(150 ) NOT NULL,
  "APM_DESCRIPCION" Varchar2(255 ),
  "APM_ESTADO" Varchar2(10 ) NOT NULL,
  CONSTRAINT "CHK_APM_ESTADO" CHECK (APM_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PUESTO_MEDICO

ALTER TABLE "ACS_PUESTO_MEDICO" ADD CONSTRAINT "PK_ACS_PUESTO_MEDICO" PRIMARY KEY ("APM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PUESTO_MEDICO" IS 'Tabla para representa, manejar y almacenarr los puestos medicos que hay en el sistema'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_ID" IS 'ID unico de cada puesto medico
'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_NOMBRE" IS 'Nombre unico del puesto medico'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_DESCRIPCION" IS 'Descripción del puesto medico'
/
COMMENT ON COLUMN "ACS_PUESTO_MEDICO"."APM_ESTADO" IS 'Campo para validar en que estado se encuentra el puesto medico
'
/

-- Table ACS_CENTRO_MEDICO

CREATE TABLE "ACS_CENTRO_MEDICO"(
  "ACM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACM_NOMBRE" Varchar2(150 ) NOT NULL,
  "ACM_UBICACION" Varchar2(255 ),
  "ACM_TELEFONO" Varchar2(50 ),
  "ACM_EMAIL" Varchar2(150 ),
  "ACM_ESTADO" Varchar2(10 ) NOT NULL,
  CONSTRAINT "CHK_ACM_ESTADO" CHECK (ACM_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_CENTRO_MEDICO

ALTER TABLE "ACS_CENTRO_MEDICO" ADD CONSTRAINT "PK_ACS_CENTRO_MEDICO" PRIMARY KEY ("ACM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_CENTRO_MEDICO" IS 'Tabla para representa, manejar y almacenarr los centros de salud que hay en el sistema'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_ID" IS 'ID unico de cada centro de salud del sistema'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_NOMBRE" IS 'Nombre unico de cada uno de los centros de salud del sistema'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_UBICACION" IS 'Ubicación exacta y detallada del centro de salud'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_TELEFONO" IS 'Telefono para contactar al centro de salud'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_EMAIL" IS 'Emial propio del centro de salud'
/
COMMENT ON COLUMN "ACS_CENTRO_MEDICO"."ACM_ESTADO" IS 'Campo para validar en que estado se encuentra el centro medico
'
/

-- Table ACS_TURNO

CREATE TABLE "ACS_TURNO"(
  "ATU_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATU_NOMBRE" Varchar2(30 ) NOT NULL,
  "ATU_HORA_INICIO" Timestamp(6) NOT NULL,
  "ATU_HORA_FIN" Timestamp(6) NOT NULL,
  "ATU_TIPO_PAGO" Varchar2(10 ) NOT NULL,
  "ATU_COSTO" Number NOT NULL,
  "ATU_PAGO" Number NOT NULL,
  "ATU_ESTADO" Varchar2(10 ) NOT NULL,
  "APM_ID" Number,
  "AME_ID" Number,
  CONSTRAINT "CHK_ATU_ESTADO" CHECK (ATU_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ATU_TIPO_PAGO" CHECK (ATU_TIPO_PAGO IN ('TURNO', 'HORAS'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_TURNO

ALTER TABLE "ACS_TURNO" ADD CONSTRAINT "PK_ACS_TURNO" PRIMARY KEY ("ATU_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_TURNO" IS 'Tabla para representa, manejar y almacenarr los turnos medicos que hay en el sistema'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_ID" IS 'ID unico de cada turno'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_NOMBRE" IS 'Nombre unico del turno'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_HORA_INICIO" IS 'Hora de inicio del turno'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_HORA_FIN" IS 'Hora de finalización del turno'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_TIPO_PAGO" IS 'Campo para definir si se paga por hora o por turno'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_COSTO" IS 'Costo que supone para el centro medico'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_PAGO" IS 'Pago que se le hace al medico'
/
COMMENT ON COLUMN "ACS_TURNO"."ATU_ESTADO" IS 'Estado en el que se encuentra el turno'
/

-- Table ACS_MEDICO

CREATE TABLE "ACS_MEDICO"(
  "AME_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AME_ESTADO" Varchar2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_ID" Number NOT NULL,
  CONSTRAINT "CHK_AME_ESTADO" CHECK (AME_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_MEDICO

ALTER TABLE "ACS_MEDICO" ADD CONSTRAINT "PK_ACS_MEDICO" PRIMARY KEY ("AME_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_MEDICO" IS 'Tabla para representa, manejar y almacenar medicos que hay en el sistema'
/
COMMENT ON COLUMN "ACS_MEDICO"."AME_ID" IS 'ID unico de cada medico
'
/
COMMENT ON COLUMN "ACS_MEDICO"."AME_ESTADO" IS 'Estado: ACTIVO, INACTIVO. Para visibilidad '
/
COMMENT ON COLUMN "ACS_MEDICO"."AUS_ID" IS 'ID que relaciona al medico con el usuario '
/

-- Table ACS_PROCEDIMIENTO

CREATE TABLE "ACS_PROCEDIMIENTO"(
  "APD_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APD_NOMBRE" Varchar2(100 ) NOT NULL,
  "APD_DESCRIPCION" Varchar2(255 ),
  "APD_ESTADO" Varchar2(10 ) NOT NULL,
  CONSTRAINT "CHK_APD_ESTADO" CHECK (APD_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PROCEDIMIENTO

ALTER TABLE "ACS_PROCEDIMIENTO" ADD CONSTRAINT "PK_ACS_PROCEDIMIENTO" PRIMARY KEY ("APD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PROCEDIMIENTO" IS 'Tabla para representa, manejar y almacenarr los procedimientos medicos que hay en el sistema'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_ID" IS 'ID unico de cada procedimiento '
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_NOMBRE" IS 'Nombre unico del procedimiento'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_DESCRIPCION" IS 'Descripción del procedimiento'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO"."APD_ESTADO" IS 'Estado en el que se encuentra el procedimiento
'
/

-- Table ACS_PROC_APLICADO

CREATE TABLE "ACS_PROC_APLICADO"(
  "APA_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APA_FECHA" Timestamp(6) NOT NULL,
  "APA_COSTO" Number NOT NULL,
  "APA_PAGO" Number NOT NULL,
  "APA_ESTADO" Varchar2(10 ) NOT NULL,
  "AME_ID" Number NOT NULL,
  "APD_ID" Number NOT NULL,
  "ACM_ID" Number,
  CONSTRAINT "CHK_APA_ESTADO" CHECK (APA_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_PROC_APLICADO

CREATE INDEX "IDX_AME_ID (APA)" ON "ACS_PROC_APLICADO" ("AME_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "IDX_ACM_ID" ON "ACS_PROC_APLICADO" ("ACM_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "IDX_AME_ID_X_ACM_ID" ON "ACS_PROC_APLICADO" ("AME_ID","ACM_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_PROC_APLICADO

ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "PK_ACS_PROC_APLICADO" PRIMARY KEY ("APA_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PROC_APLICADO" IS 'Tabla para representa, manejar y almacenarr los procedimientos aplicados que hay en el sistema, ya que un medico puede hcaer muchos procedimientos y un procedimiento puede hacerse varias veces pero por diferentes medicos'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_ID" IS 'ID unico del procedimiento aplicado'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_FECHA" IS 'Fecha en la que se aplicó el procedimiento'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_COSTO" IS 'Costo REAL una vez el procedimiento fue aplicado'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_PAGO" IS 'Precioa REAL a pagarle al medico por el procedimiento'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APA_ESTADO" IS 'Estado en que se encuentra el procecimiento aplicado'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."AME_ID" IS 'ID del medico relacionado'
/
COMMENT ON COLUMN "ACS_PROC_APLICADO"."APD_ID" IS 'ID del procedimineto relacionado'
/

-- Table ACS_ESCALA_MENSUAL

CREATE TABLE "ACS_ESCALA_MENSUAL"(
  "AEM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AEM_MES" Number NOT NULL,
  "AEM_ANIO" Number NOT NULL,
  "AEM_ESTADO" Varchar2(20 ) NOT NULL,
  "ACM_ID" Number NOT NULL,
  CONSTRAINT "CHK_AEM_ESTADO" CHECK (AEM_ESTADO IN ('CONSTRUCCION', 'VIGENTE', 'EN REVISION', 'LISTA PARA PAGO', 'PROCESADA')),
  CONSTRAINT "CHK_AEM_MES" CHECK (AEM_MES BETWEEN 1 AND 12),
  CONSTRAINT "CHK_AEM_ANIO" CHECK (AEM_ANIO >= 2000)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_ESCALA_MENSUAL

ALTER TABLE "ACS_ESCALA_MENSUAL" ADD CONSTRAINT "PK_ACS_ESCALA_MENSUAL" PRIMARY KEY ("AEM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_ESCALA_MENSUAL" IS 'Tabla para representa, manejar y almacenarr las escalas mensuales que hay en el sistema'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_ID" IS 'ID unico de cada escala mensual
'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_MES" IS 'Mes exacto de la escala mensual'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_ANIO" IS 'Año exacto de la escala mensual'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."AEM_ESTADO" IS 'Estado en el que se encuentra la escala mensual'
/
COMMENT ON COLUMN "ACS_ESCALA_MENSUAL"."ACM_ID" IS 'ID del centro relacionado a la escala mensual'
/

-- Table ACS_DETALLE_MENSUAL

CREATE TABLE "ACS_DETALLE_MENSUAL"(
  "ADM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADM_OBSERVACIONES" Varchar2(255 ),
  "ADM_FECHA" Timestamp(6) NOT NULL,
  "ADM_ESTADO_TURNO" Varchar2(15 ) NOT NULL,
  "ADM_HR_INICIO" Timestamp(9) NOT NULL,
  "ADM_HR_FIN" Timestamp(9) NOT NULL,
  "ADM_ESTADO" Varchar2(10 ) NOT NULL,
  "AEM_ID" Number NOT NULL,
  "AME_ID" Number NOT NULL,
  "APM_ID" Number NOT NULL,
  "ATU_ID" Number NOT NULL,
  CONSTRAINT "CHK_ADM_ESTADO" CHECK (ADM_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_AMD_ESTADO_TURNO" CHECK (ADM_ESTADO_TURNO IN ('CUMPLIDO','FALTA','CANCELADO','REEMPLAZADO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_DETALLE_MENSUAL

CREATE UNIQUE INDEX "UQ_AEM_ID_X_ATU_ID_X_APM_ID_X_AME_ID_X_ADM_FECHA" ON "ACS_DETALLE_MENSUAL" ("ATU_ID","APM_ID","AME_ID","AEM_ID","ADM_FECHA")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "IDX_AME_ID (ADM)" ON "ACS_DETALLE_MENSUAL" ("AME_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_DETALLE_MENSUAL

ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "PK_ACS_DETALLE_MENSUAL" PRIMARY KEY ("ADM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_DETALLE_MENSUAL" IS 'Tabla para representa, manejar y almacenarr los detalles de las escalas mensuales que hay en el sistema, este es un punto que reune medicos, centros, puestos, turnos y demás, esto se maneja así ya que pueden haber muchos cambios y se requiere flexibilidad en esos campos, por eso no se relacionan entre ellos si no que se junta en una tabla '
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_ID" IS 'ID unico del detalle de la escala mensual'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_OBSERVACIONES" IS 'Observaciones del detalle mensual'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_FECHA" IS 'Fecha especifica del detalle'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_ESTADO_TURNO" IS 'Campo para saber en que está relamente quedó el turno'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_HR_INICIO" IS 'Hora real en la que inició'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_HR_FIN" IS 'Hora real en la que finalizó'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ADM_ESTADO" IS 'Estado en el que se encuentra el detalle mensual'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."AEM_ID" IS 'ID de referencia con la escala mensual'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."AME_ID" IS 'ID de referencia con el medico 
'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."APM_ID" IS 'ID de referencia con el puesto medico 
'
/
COMMENT ON COLUMN "ACS_DETALLE_MENSUAL"."ATU_ID" IS 'ID del turno relacionado '
/

-- Table ACS_AUDITORIA_DETALLE_MENSUAL

CREATE TABLE "ACS_AUDITORIA_DETALLE_MENSUAL"(
  "AUM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 0) NOT NULL,
  "AUM_OBSERVACIONES" Varchar2(255 ),
  "AUM_FECHA" Timestamp(6) NOT NULL,
  "AUM_ESTADO_TURNO" Varchar2(15 ),
  "AUM_HR_INICIO" Timestamp(9),
  "AUM_HR_FIN" Timestamp(9),
  "AUM_ESTADO" Varchar2(10 ) NOT NULL,
  "AUM_USUARIO" Varchar2(50 ) NOT NULL,
  "AUM_CAMBIOS" Varchar2(100 ),
  "AUM_ACCION" Varchar2(10 ),
  "AEM_ID" Number,
  "AME_ID" Number,
  "APM_ID" Number,
  "ATU_ID" Number,
  "ADM_ID" Number,
  CONSTRAINT "CHK_ADM_ESTADO (AUM)" CHECK (AUM_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_AMD_ESTADO_TURNO (AUM)" CHECK (AUM_ESTADO_TURNO IN ('CUMPLIDO','FALTA','CANCELADO','REEMPLAZADO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_AUDITORIA_DETALLE_MENSUAL

ALTER TABLE "ACS_AUDITORIA_DETALLE_MENSUAL" ADD CONSTRAINT "PK_ACS_AUDITORIA_DETALLE_MENSUAL" PRIMARY KEY ("AUM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_AUDITORIA_DETALLE_MENSUAL" IS 'Tabla para representa, manejar y almacenarr los detalles de las escalas mensuales que hay en el sistema, este es un punto que reune medicos, centros, puestos, turnos y demás, esto se maneja así ya que pueden haber muchos cambios y se requiere flexibilidad en esos campos, por eso no se relacionan entre ellos si no que se junta en una tabla '
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ID" IS 'ID unico del detalle de la escala mensual'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_OBSERVACIONES" IS 'Observaciones del detalle mensual'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_FECHA" IS 'Fecha especifica del detalle'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ESTADO_TURNO" IS 'Campo para saber en que está relamente quedó el turno'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_HR_INICIO" IS 'Hora real en la que inició'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_HR_FIN" IS 'Hora real en la que finalizó'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ESTADO" IS 'Estado en el que se encuentra el detalle mensual'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_USUARIO" IS 'Usuario que realizó el cambio'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_CAMBIOS" IS 'para saber qué campos cambiaron'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AUM_ACCION" IS 'INSERT, UPDATE, DELETE'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AEM_ID" IS 'ID de referencia con la escala mensual'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."AME_ID" IS 'ID de referencia con el medico 
'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."APM_ID" IS 'ID de referencia con el puesto medico 
'
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."ATU_ID" IS 'ID del turno relacionado '
/
COMMENT ON COLUMN "ACS_AUDITORIA_DETALLE_MENSUAL"."ADM_ID" IS 'ID de referencia al detalle de escala mensual'
/

-- Table ACS_DOCUMENTO_USUARIO

CREATE TABLE "ACS_DOCUMENTO_USUARIO"(
  "ADU_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADU_URL" Varchar2(1000 ) NOT NULL,
  "ADU_COMENTARIOS" Varchar2(400 ),
  "ADU_ESTADO" Varchar2(10 ) DEFAULT 'PENDIENTE' NOT NULL,
  "ADU_FECHA_CREACION" Timestamp(6) DEFAULT SYSDATE NOT NULL,
  "ADU_FECHA_ACTUALIZACION" Timestamp(6) DEFAULT SYSDATE NOT NULL,
  "ATD_ID" Number NOT NULL,
  "AUS_ID" Number NOT NULL,
  "APF_ID" Number,
  CONSTRAINT "CHK_ADU_ESTADO" CHECK (ADU_ESTADO IN ('PENDIENTE', 'APROBADO', 'RECHAZADO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_DOCUMENTO_USUARIO

CREATE UNIQUE INDEX "UQ_AUS_ID_X_ATD_ID" ON "ACS_DOCUMENTO_USUARIO" ("AUS_ID","ATD_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "ADU_X_APF" ON "ACS_DOCUMENTO_USUARIO" ("APF_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_DOCUMENTO_USUARIO

ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "PK_ACS_DOCUMENTO_USUARIO" PRIMARY KEY ("ADU_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_DOCUMENTO_USUARIO" IS 'Tabla para representa, manejar y almacenar documentos de los usuarios que hay en el sistema'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_ID" IS 'ID unico del documento'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_URL" IS 'URL del documento adjunto'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_COMENTARIOS" IS 'Descripcion propia del documento'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_ESTADO" IS '(''PENDIENTE'', ''APROBADO'', ''RECHAZADO'')
'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_FECHA_CREACION" IS 'automatico'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."ADU_FECHA_ACTUALIZACION" IS 'automatico'
/
COMMENT ON COLUMN "ACS_DOCUMENTO_USUARIO"."AUS_ID" IS 'ID del usuario relacionado al documento'
/

-- Table ACS_USUARIO

CREATE TABLE "ACS_USUARIO"(
  "AUS_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AUS_ESTADO" Varchar2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_FECHA_CREACION" Timestamp(6) DEFAULT SYSDATE NOT NULL,
  "AUS_ULTIMO_ACCESO" Timestamp(6) DEFAULT SYSDATE NOT NULL,
  "APE_ID" Number NOT NULL,
  CONSTRAINT "CHK_AUS_ESTADO" CHECK (AUS_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_USUARIO

ALTER TABLE "ACS_USUARIO" ADD CONSTRAINT "PK_ACS_USUARIO" PRIMARY KEY ("AUS_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_USUARIO" IS 'Tabla para representa, manejar y almacenar usuarios que hay en el sistema'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_ID" IS 'ID unico de cada usuario del sistema
'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_ESTADO" IS 'Estado: ACTIVO, INACTIVO. Para visibilidad y gestion de perfiles de usuario'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_FECHA_CREACION" IS 'Automatico
'
/
COMMENT ON COLUMN "ACS_USUARIO"."AUS_ULTIMO_ACCESO" IS 'Automatico/trigger'
/
COMMENT ON COLUMN "ACS_USUARIO"."APE_ID" IS 'Fk'
/

-- Table ACS_ADMINISTRATIVO

CREATE TABLE "ACS_ADMINISTRATIVO"(
  "AAD_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AAD_ESTADO" Varchar2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_ID" Number NOT NULL,
  CONSTRAINT "CHK_AAD_ESTADO" CHECK (AAD_ESTADO IN ('ACTIVO', 'INACTIVO', 'ARCHIVADO', 'SUSPENDIDO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_ADMINISTRATIVO

ALTER TABLE "ACS_ADMINISTRATIVO" ADD CONSTRAINT "PK_ACS_ADMINISTRATIVO" PRIMARY KEY ("AAD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_ADMINISTRATIVO" IS 'Tabla para representa, manejar y almacenar administrativos que hay en el sistema'
/
COMMENT ON COLUMN "ACS_ADMINISTRATIVO"."AAD_ID" IS 'ID unico de cada administrativo'
/
COMMENT ON COLUMN "ACS_ADMINISTRATIVO"."AAD_ESTADO" IS 'Estado: ACTIVO, INACTIVO. Para visibilidad '
/
COMMENT ON COLUMN "ACS_ADMINISTRATIVO"."AUS_ID" IS 'ID del usuario relacionado con el administrativo'
/

-- Table ACS_CUENTA_BANCARIA

CREATE TABLE "ACS_CUENTA_BANCARIA"(
  "ACB_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACB_NUMERO_CUENTA" Varchar2(50 ) NOT NULL,
  "ACB_ES_PRINCIPAL" Varchar2(2 ) DEFAULT 'NO' NOT NULL,
  "ACB_TIPO_CUENTA" Varchar2(10 ) NOT NULL,
  "ACB_ESTADO" Varchar2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  "AUS_ID" Number NOT NULL,
  "ABA_ID" Number NOT NULL,
  CONSTRAINT "CHK_ACB_ESTADO" CHECK (ACB_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ACB_TIPO_CUENTA" CHECK (ACB_TIPO_CUENTA in ('AHORRO', 'CORRIENTE')),
  CONSTRAINT "CHK_ACB_ES_PRINCIPAL" CHECK (ACB_ES_PRINCIPAL IN ('SI', 'NO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_CUENTA_BANCARIA

CREATE UNIQUE INDEX "UQ_ACB_ES_PRINCIPAL_USUARIO" ON "ACS_CUENTA_BANCARIA" ((CASE WHEN ACB_ES_PRINCIPAL = 'SI' THEN AUS_ID END))
TABLESPACE "TBS_ACS_INDICES"
/

CREATE UNIQUE INDEX "UQ_ACB_NUMERO_CUENTA" ON "ACS_CUENTA_BANCARIA" ("ACB_NUMERO_CUENTA")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_CUENTA_BANCARIA

ALTER TABLE "ACS_CUENTA_BANCARIA" ADD CONSTRAINT "PK_ACS_CUENTA_BANCARIA" PRIMARY KEY ("ACB_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_CUENTA_BANCARIA" IS 'Tabla para representa, manejar y almacenar cuentas bancarias de los usuarios que hay en el sistema'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_ID" IS 'ID unico de cada cuenta bancaria'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_NUMERO_CUENTA" IS 'Numero propio y unico de la cuenta bancaria'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_ES_PRINCIPAL" IS 'SI, NO'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_TIPO_CUENTA" IS 'CORRIENTE o de AHORRO'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ACB_ESTADO" IS 'Estado: ACTIVO, INACTIVO. Para visibilidad '
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."AUS_ID" IS 'ID del usuario relacionado a la cuenta bancaria'
/
COMMENT ON COLUMN "ACS_CUENTA_BANCARIA"."ABA_ID" IS 'ID del banco relacionado a la cuenta bancaria'
/

-- Table ACS_BANCO

CREATE TABLE "ACS_BANCO"(
  "ABA_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ABA_NOMBRE" Varchar2(100 ) NOT NULL,
  "ABA_TELEFONO" Varchar2(20 ),
  "ABA_ESTADO" Varchar2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT "CHK_ABA_ESTADO" CHECK (ABA_ESTADO IN ('ACTIVO', 'INACTIVO', 'ARCHIVADO', 'SUSPENDIDO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_BANCO

CREATE UNIQUE INDEX "UQ_ABA_NOMBRE" ON "ACS_BANCO" ("ABA_NOMBRE")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_BANCO

ALTER TABLE "ACS_BANCO" ADD CONSTRAINT "PK_ACS_BANCO" PRIMARY KEY ("ABA_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_BANCO" IS 'Tabla para representa, manejar y almacenar bamco que hay en el sistema'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_ID" IS 'ID unico de cada banco'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_NOMBRE" IS 'Nombre propio y unico de cada banco'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_TELEFONO" IS '+506 8888 8888'
/
COMMENT ON COLUMN "ACS_BANCO"."ABA_ESTADO" IS 'Estado: ACTIVO, INACTIVO. Para visibilidad '
/

-- Table ACS_PERSONA

CREATE TABLE "ACS_PERSONA"(
  "APE_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APE_CEDULA" Varchar2(20 ) NOT NULL,
  "APE_NOMBRE" Varchar2(200 ) NOT NULL,
  "APE_P_APELLIDO" Varchar2(100 ) NOT NULL,
  "APE_S_APELLIDO" Varchar2(100 ),
  "APE_FECHA_NACIMIENTO" Timestamp(6) NOT NULL,
  "APE_SEXO" Varchar2(10 ),
  "APE_ESTADO_CIVIL" Varchar2(15 ),
  "APE_NACIONALIDAD" Varchar2(10 ),
  "APE_TIPO_USUARIO" Varchar2(15 ) NOT NULL,
  "APE_ESTADO_REGISTRO" Varchar2(10 ) NOT NULL,
  "APE_EMAIL" Varchar2(255 ) NOT NULL,
  "APE_TELEFONO" Varchar2(20 ),
  "APE_RESIDENCIA" Varchar2(255 ),
  "APE_DIRECION_CASA" Varchar2(255 ),
  "APE_DIRECCION_TRABAJO" Varchar2(255 ),
  "APE_FECHA_CREACION" Timestamp(6) DEFAULT SYSDATE NOT NULL,
  "APE_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  CONSTRAINT "CHK_APE_ESTADO_REGISTRO" CHECK (APE_ESTADO_REGISTRO IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
  CONSTRAINT "CHK_APE_SEXO" CHECK (APE_SEXO IN ('MASCULINO', 'FEMENINO')),
  CONSTRAINT "CHK_APE_ESTADO_CIVIL" CHECK (APE_ESTADO_CIVIL IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO', 'UNION LIBRE')),
  CONSTRAINT "CHK_APE_NACIONALIDAD" CHECK (APE_NACIONALIDAD IN ('NACIONAL', 'EXTRANJERO')),
  CONSTRAINT "CHK_APE_TIPO_USUARIO" CHECK (APE_TIPO_USUARIO in ('MEDICO', 'ADMINISTRATIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_PERSONA

CREATE INDEX "IDX_APE_NOMBRE" ON "ACS_PERSONA" ("APE_NOMBRE","APE_P_APELLIDO","APE_S_APELLIDO")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE UNIQUE INDEX "UQ_APE_CEDULA" ON "ACS_PERSONA" ("APE_CEDULA")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE UNIQUE INDEX "UQ_APE_EMAIL" ON "ACS_PERSONA" ("APE_EMAIL")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_PERSONA

ALTER TABLE "ACS_PERSONA" ADD CONSTRAINT "PK_ACS_PERSONA" PRIMARY KEY ("APE_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PERSONA" IS 'Tabla para representa, manejar y almacenar personal que hay en el sistema'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_CEDULA" IS 'Unico'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_NOMBRE" IS 'Requerido'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_P_APELLIDO" IS 'Requerido'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_S_APELLIDO" IS 'Opcional'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_FECHA_NACIMIENTO" IS 'Requerido'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_SEXO" IS 'MASCULINO, FEMENINO, OTRO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_TIPO_USUARIO" IS 'Evalua para que puesto aplica el usuario, no cambia una vez definido
valores: MEDICO, ADMINISTRATIVO'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_ESTADO_REGISTRO" IS 'Estado para saber el tipo de estado de persona, si esta aceptado no se borra. Valores: PENDIENTE, ACEPTADO, RECHAZADO
'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_EMAIL" IS 'Unico'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_TELEFONO" IS '+506 8888 8888'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_RESIDENCIA" IS 'Lugar donde vive'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_DIRECION_CASA" IS 'Direccion exacta donde vive'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_DIRECCION_TRABAJO" IS 'Direccion exacta del lugar de trabajo'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_FECHA_CREACION" IS 'Automatico'
/
COMMENT ON COLUMN "ACS_PERSONA"."APE_FECHA_ACTUALIZACION" IS 'Automatico'
/

-- Table ACS_PERMISO

CREATE TABLE "ACS_PERMISO"(
  "APR_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APR_PANTALLA" Varchar2(100 ) NOT NULL,
  "APR_LEER" Number NOT NULL,
  "APR_CREAR" Number NOT NULL,
  "APR_EDITAR" Number NOT NULL,
  "APR_BORRAR" Number NOT NULL,
  CONSTRAINT "CHK_APR_PERMISO_LEER" CHECK (APR_LEER IN (0, 1)),
  CONSTRAINT "CHK_APR_PERMISO_CREAR" CHECK (APR_CREAR IN (0, 1)),
  CONSTRAINT "CHK_APR_PERMISO_EDITAR" CHECK (APR_EDITAR IN (0, 1)),
  CONSTRAINT "CHK_APR_PERMISO_BORRAR" CHECK (APR_BORRAR IN (0, 1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_PERMISO

CREATE UNIQUE INDEX "UQ_APR_PAN_TIU" ON "ACS_PERMISO" ("APR_PANTALLA")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_PERMISO

ALTER TABLE "ACS_PERMISO" ADD CONSTRAINT "PK_ACS_PERMISO" PRIMARY KEY ("APR_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PERMISO" IS 'Tabla para detallar los permisos que puede tener un usuario en las diferentes pantallas'
/

-- Table ACS_CLAVE

CREATE TABLE "ACS_CLAVE"(
  "ACL_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACL_CLAVE" Varchar2(500 ) NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_CLAVE

ALTER TABLE "ACS_CLAVE" ADD CONSTRAINT "PK_ACS_CLAVE" PRIMARY KEY ("ACL_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table ACS_TIPO_DOCUMENTO

CREATE TABLE "ACS_TIPO_DOCUMENTO"(
  "ATD_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATD_TIPO_USUARIO" Varchar2(15 ) NOT NULL,
  "ATD_DOCUMENTO_REQUERIDO" Varchar2(200 ) NOT NULL,
  "ATD_ESTADO" Varchar2(10 ) DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT "CHK_ATD_ESTADO" CHECK (ATD_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ATD_TIPO_USUARIO" CHECK (ATD_TIPO_USUARIO in ('MEDICO', 'ADMINISTRATIVO', 'TODOS'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_TIPO_DOCUMENTO

CREATE UNIQUE INDEX "UQ_ATD_TIPO_U_X_ATD_DOCU_R" ON "ACS_TIPO_DOCUMENTO" ("ATD_TIPO_USUARIO","ATD_DOCUMENTO_REQUERIDO")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_TIPO_DOCUMENTO

ALTER TABLE "ACS_TIPO_DOCUMENTO" ADD CONSTRAINT "PK_ACS_TIPO_DOCUMENTO" PRIMARY KEY ("ATD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_TIPO_DOCUMENTO" IS 'Tabla para representa, manejar y almacenar tipo de documento que hay en el sistema'
/
COMMENT ON COLUMN "ACS_TIPO_DOCUMENTO"."ATD_TIPO_USUARIO" IS 'MEDICO, ADMINISTRATIVO, TODOS'
/
COMMENT ON COLUMN "ACS_TIPO_DOCUMENTO"."ATD_DOCUMENTO_REQUERIDO" IS 'Nombre docuemnto solicitado'
/
COMMENT ON COLUMN "ACS_TIPO_DOCUMENTO"."ATD_ESTADO" IS 'Estado: ACTIVO, INACTIVO. Para visibilidad '
/

-- Table ACS_PUESTOXCENTRO

CREATE TABLE "ACS_PUESTOXCENTRO"(
  "APC_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ACM_ID" Number NOT NULL,
  "APM_ID" Number NOT NULL,
  "APC_ESTADO" Varchar2(10 ) NOT NULL,
  CONSTRAINT "CHK_APC_ESTADO" CHECK (APC_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PUESTOXCENTRO

ALTER TABLE "ACS_PUESTOXCENTRO" ADD CONSTRAINT "PK_ACS_PUESTOXCENTRO" PRIMARY KEY ("APC_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PUESTOXCENTRO" IS 'Tabla para relacionar los centros de salud con el puesto medico, ya que un centro puede tener muchos puestos y un puesto puede estar en mucho centros'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."APC_ID" IS 'ID propio de la tabla intermedia'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."ACM_ID" IS 'ID de relación con el centro medico
'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."APM_ID" IS 'ID de relación con el puesto medico
'
/
COMMENT ON COLUMN "ACS_PUESTOXCENTRO"."APC_ESTADO" IS 'Estado en el que se encuentra la relación de puesto con el centro medico'
/

-- Table ACS_PROCEDIMIENTOXCENTRO

CREATE TABLE "ACS_PROCEDIMIENTOXCENTRO"(
  "APRC_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APRC_COSTO" Number NOT NULL,
  "APRC_PAGO" Number NOT NULL,
  "APRC_ESTADO" Varchar2(30 ) NOT NULL,
  "ACM_ID" Number NOT NULL,
  "APD_ID" Number NOT NULL,
  CONSTRAINT "CHK_APRC_ESTADO" CHECK (APRC_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PROCEDIMIENTOXCENTRO

ALTER TABLE "ACS_PROCEDIMIENTOXCENTRO" ADD CONSTRAINT "PK_ACS_PROCEDIMIENTOXCENTRO" PRIMARY KEY ("APRC_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PROCEDIMIENTOXCENTRO" IS 'Tabla para relacionar los centros de salud con un los procedimientos medicos, ya que un centro puede tener muchos procedimientos y un procedimiento puede realizarce en mucho centros'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_ID" IS 'ID propio de la tabla intermedia'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_COSTO" IS 'Costo que supone para el centro medico'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_PAGO" IS 'Pago que se le hace al medico
'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APRC_ESTADO" IS 'Estado en el que se encuentra el prodecimiento aplicado en el centro medico
'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."ACM_ID" IS 'ID de relación con el centro medico'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTOXCENTRO"."APD_ID" IS 'ID de relación con el procedimiento
'
/

-- Table ACS_PERSONAL_TIPO_PLANILLA

CREATE TABLE "ACS_PERSONAL_TIPO_PLANILLA"(
  "APTP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APTP_ACTIVO" Number NOT NULL,
  "APTP_FECHA_ASIGNACION" Timestamp(6) NOT NULL,
  "AUS_ID" Number NOT NULL,
  "ATP_ID" Number NOT NULL,
  CONSTRAINT "CHK_APTP_ACTIVO" CHECK (APTP_ACTIVO IN (0,1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PERSONAL_TIPO_PLANILLA

ALTER TABLE "ACS_PERSONAL_TIPO_PLANILLA" ADD CONSTRAINT "PK_ACS_PERSONAL_TIPO_PLANILLA" PRIMARY KEY ("APTP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PERSONAL_TIPO_PLANILLA" IS 'Tabla para representa, manejar y almacenar personal del tipo de planilla que hay en el sistema'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."APTP_ID" IS 'Identificador único de la asignación'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."APTP_ACTIVO" IS 'Indica si la asignación está activa'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."APTP_FECHA_ASIGNACION" IS 'Fecha de asignación'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."AUS_ID" IS 'Usuario asignado al tipo de planilla'
/
COMMENT ON COLUMN "ACS_PERSONAL_TIPO_PLANILLA"."ATP_ID" IS 'Tipo de planilla asignado'
/

-- Table ACS_BITACORA_PLANILLA

CREATE TABLE "ACS_BITACORA_PLANILLA"(
  "ABP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ABP_ACCION" Varchar2(30 ) NOT NULL,
  "ABP_DETALLE" Varchar2(30 ),
  "ABP_FECHA_CREACION" Timestamp(6) NOT NULL,
  "APL_ID" Number NOT NULL,
  "AUS_ID" Number
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_BITACORA_PLANILLA

ALTER TABLE "ACS_BITACORA_PLANILLA" ADD CONSTRAINT "PK_ACS_BITACORA_PLANILLA" PRIMARY KEY ("ABP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_BITACORA_PLANILLA" IS 'Tabla para representa, manejar y almacenar bitacora de planilla que hay en el sistema'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_ID" IS 'Identificador de bitácora'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_ACCION" IS 'Acción (CREAR, APROBAR, etc.)'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_DETALLE" IS 'Observaciones'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."ABP_FECHA_CREACION" IS 'Fecha de creación del registro'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."APL_ID" IS 'Planilla relacionada'
/
COMMENT ON COLUMN "ACS_BITACORA_PLANILLA"."AUS_ID" IS 'Usuario que ejecutó la acción'
/

-- Table ACS_ENVIO_COMP

CREATE TABLE "ACS_ENVIO_COMP"(
  "AEC_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AEC_EMAIL" Varchar2(30 ) NOT NULL,
  "AEC_FECHA_ENVIO" Timestamp(6) NOT NULL,
  "AEC_ERROR" Varchar2(30 ),
  "ADP_ID" Number NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_ENVIO_COMP

ALTER TABLE "ACS_ENVIO_COMP" ADD CONSTRAINT "PK_ACS_ENVIO_COMP" PRIMARY KEY ("AEC_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_ENVIO_COMP" IS 'Tabla para representa, manejar y almacenar envios de comprobantes que hay en el sistema'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_ID" IS 'Identificador'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_EMAIL" IS 'Email destino'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_FECHA_ENVIO" IS 'Fecha de envío'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."AEC_ERROR" IS 'Error en el envío si aplica'
/
COMMENT ON COLUMN "ACS_ENVIO_COMP"."ADP_ID" IS 'Detalle de planilla notificado'
/

-- Table ACS_MOVIMIENTO_PLANILLA

CREATE TABLE "ACS_MOVIMIENTO_PLANILLA"(
  "AMP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    NOCACHE) NOT NULL,
  "AMP_FUENTE" Varchar2(20 ) NOT NULL,
  "AMP_MONTO" Number NOT NULL,
  "AMP_OBS" Varchar2(255 ),
  "AMP_CALC" Number NOT NULL,
  "AMP_FECHA_CREACION" Timestamp(6) NOT NULL,
  "APD_ID" Number NOT NULL,
  "ATM_ID" Number NOT NULL,
  CONSTRAINT "CHK_AMP_FUENTE" CHECK (AMP_FUENTE IN ('AUTOMATICO', 'MANUAL'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_MOVIMIENTO_PLANILLA

ALTER TABLE "ACS_MOVIMIENTO_PLANILLA" ADD CONSTRAINT "PK_ACS_MOVIMIENTO_PLANILLA" PRIMARY KEY ("AMP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_MOVIMIENTO_PLANILLA" IS 'Tabla para representa, manejar y almacenar movimientos de planillas que hay en el sistema'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_ID" IS 'Identificador'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_FUENTE" IS 'Fuente (AUTOMATICO o MANUAL)'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_MONTO" IS 'Monto aplicado'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_OBS" IS 'Observación'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_CALC" IS 'Traza de cálculo'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."AMP_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."APD_ID" IS 'Detalle de planilla al que aplica el movimiento'
/
COMMENT ON COLUMN "ACS_MOVIMIENTO_PLANILLA"."ATM_ID" IS 'Tipo de movimiento'
/

-- Table ACS_TIPO_MOV

CREATE TABLE "ACS_TIPO_MOV"(
  "ATM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATM_COD" Varchar2(40 ) NOT NULL,
  "ATM_NOMBRE" Varchar2(120 ) NOT NULL,
  "ATM_NATURALEZA" Varchar2(20 ) NOT NULL,
  "ATM_APLICA_A" Varchar2(20 ) NOT NULL,
  "ATM_MODO" Varchar2(20 ) NOT NULL,
  "ATM_BASE" Varchar2(20 ) NOT NULL,
  "ATM_PORC" Number,
  "ATM_MONTO_FIJO" Number,
  "ATM_ES_AUTOMATICO" Number NOT NULL,
  "ATM_PRIORIDAD" Number NOT NULL,
  "ATM_ESTADO" Varchar2(10 ) NOT NULL,
  "ATM_REGLA" Clob,
  "ATM_FECHA_CREACION" Timestamp(6) NOT NULL,
  "ATM_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  CONSTRAINT "CHK_ATM_APLICA_A" CHECK (ATM_APLICA_A IN ('MEDICO', 'ADMINISTRATIVO', 'AMBOS')),
  CONSTRAINT "CHK_ATM_BASE" CHECK (ATM_BASE IN ('BRUTO', 'SALARIO_BASE', 'HORAS', 'PROCEDIMIENTOS', 'PERSONALIZADA')),
  CONSTRAINT "CHK_ATM_ES_AUTOMATICO" CHECK (ATM_ES_AUTOMATICO IN (0,1)),
  CONSTRAINT "CHK_ATM_ESTADO" CHECK (ATM_ESTADO IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT "CHK_ATM_MODO" CHECK (ATM_MODO IN ('FIJO', 'PORCENTAJE')),
  CONSTRAINT "CHK_ATM_NATURALEZA" CHECK (ATM_NATURALEZA IN ('INGRESO', 'DEDUCCION'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_TIPO_MOV

ALTER TABLE "ACS_TIPO_MOV" ADD CONSTRAINT "PK_ACS_TIPO_MOV" PRIMARY KEY ("ATM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_TIPO_MOV" IS 'Tabla para representa, manejar y almacenar tipos de movimiento que hay en el sistema'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_ID" IS 'Identificador de movimiento'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_COD" IS 'Código corto (RENTA, CAJA, etc.)'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_NOMBRE" IS 'Nombre completo'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_NATURALEZA" IS 'Naturaleza: INGRESO/DEDUCCION'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_APLICA_A" IS 'Aplica a (MEDICO/ADMIN/AMBOS)'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_MODO" IS 'FIJO o PORCENTAJE'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_BASE" IS 'Base de cálculo'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_PORC" IS 'Porcentaje si aplica'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_MONTO_FIJO" IS 'Monto fijo si aplica'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_ES_AUTOMATICO" IS 'Automático (1) o manual (0)'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_PRIORIDAD" IS 'Orden de aplicación'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_ESTADO" IS 'Estado del tipo de movimiento.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_REGLA" IS 'Reglas JSON complejas para tramos.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_TIPO_MOV"."ATM_FECHA_ACTUALIZACION" IS 'Fecha de última actualización'
/

-- Table ACS_DETALLE_PLANILLA

CREATE TABLE "ACS_DETALLE_PLANILLA"(
  "ADP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADP_TIPO_PERSONA" Varchar2(30 ) NOT NULL,
  "ADP_SALARIO_BASE" Number NOT NULL,
  "ADP_BRUTO" Number NOT NULL,
  "ADP_DED" Number NOT NULL,
  "APD_NETO" Number NOT NULL,
  "ADP_FECHA_NOTIFICACION" Timestamp(6),
  "ADP_EMAIL_ENV" Number NOT NULL,
  "ADP_COMPROBANTE_HTML" Clob,
  "ADP_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  "ADP_FECHA_CREACION" Timestamp(6) NOT NULL,
  "APL_ID" Number NOT NULL,
  "AUS_ID" Number,
  "ACB_ID" Number,
  CONSTRAINT "CHK_ADP_TIPO_PERSONA" CHECK (ADP_TIPO_PERSONA IN ('MEDICO', 'ADMINISTRATIVO')),
  CONSTRAINT "CHL_ADP_EMAIL_ENV" CHECK (ADP_EMAIL_ENV IN (0,1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_DETALLE_PLANILLA

ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "PK_ACS_DETALLE_PLANILLA" PRIMARY KEY ("ADP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_DETALLE_PLANILLA" IS 'Tabla para representa, manejar y almacenar detalles de planillas que hay en el sistema'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_ID" IS 'Identificador del detalle'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_TIPO_PERSONA" IS 'Tipo de personal (MEDICO/ADMIN)'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_SALARIO_BASE" IS 'Salario base (admins)'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_BRUTO" IS 'Bruto generado'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_DED" IS 'Total deducciones'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."APD_NETO" IS 'Neto a pagar'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_FECHA_NOTIFICACION" IS 'Fecha de notificación'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_EMAIL_ENV" IS 'Indicador si se envió comprobante'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_COMPROBANTE_HTML" IS 'Comprobante HTML'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_FECHA_ACTUALIZACION" IS 'Fecha de última actualización'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ADP_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."APL_ID" IS 'Planilla a la que pertenece el detalle'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."AUS_ID" IS 'Identificador del usuario'
/
COMMENT ON COLUMN "ACS_DETALLE_PLANILLA"."ACB_ID" IS 'Cuenta bancaria principal para depósito'
/

-- Table ACS_PLANILLA

CREATE TABLE "ACS_PLANILLA"(
  "APL_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APL_ANIO" Number NOT NULL,
  "APL_MES" Number NOT NULL,
  "APL_ESTADO" Varchar2(20 ) NOT NULL,
  "APL_FEC_GEN" Timestamp(6),
  "APL_FEC_APR" Timestamp(6),
  "APL_FEC_PRO" Timestamp(6),
  "APL_FEC_NOT" Timestamp(6),
  "APL_TOT_BRUTO" Number NOT NULL,
  "APL_TOT_DED" Number NOT NULL,
  "APL_TOT_NETO" Number NOT NULL,
  "APL_FECHA_CREACION" Timestamp(6) NOT NULL,
  "APL_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  "ATP_ID" Number NOT NULL,
  CONSTRAINT "CHK_APL_ANIO" CHECK (APL_ANIO >= 2000),
  CONSTRAINT "CHK_APL_ESTADO" CHECK (APL_ESTADO IN ('CONSTRUCCION', 'APROBADA', 'PROCESADA', 'NOTIFICADA')),
  CONSTRAINT "CHK_APL_MES" CHECK (APL_MES BETWEEN 1 AND 12)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PLANILLA

ALTER TABLE "ACS_PLANILLA" ADD CONSTRAINT "PK_ACS_PLANILLA" PRIMARY KEY ("APL_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PLANILLA" IS 'Tabla para representa, manejar y almacenar planillas que hay en el sistema'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_ID" IS 'Identificador de la planilla'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_ANIO" IS 'Año de la planilla'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_MES" IS 'Mes de la planilla'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_ESTADO" IS 'Estado del ciclo'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_GEN" IS 'Fecha de generación'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_APR" IS 'Fecha de aprobación'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_PRO" IS 'Fecha de procesado'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FEC_NOT" IS 'Fecha de notificación'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_TOT_BRUTO" IS 'Total bruto'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_TOT_DED" IS 'Total deducciones'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_TOT_NETO" IS 'Total neto'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_PLANILLA"."APL_FECHA_ACTUALIZACION" IS 'Fecha de última actualización'
/
COMMENT ON COLUMN "ACS_PLANILLA"."ATP_ID" IS 'Tipo de planilla relacionada'
/

-- Table ACS_TIPO_PLANILLA

CREATE TABLE "ACS_TIPO_PLANILLA"(
  "ATP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATP_NOMBRE" Varchar2(80 ) NOT NULL,
  "ATP_APLICA_A" Varchar2(20 ) NOT NULL,
  "ATP_DESC" Varchar2(255 ) NOT NULL,
  "ATP_ESTADO" Varchar2(10 ) NOT NULL,
  "ATP_DESCRIPCION" Varchar2(255 ),
  CONSTRAINT "CHK_ATP_APLICA_A" CHECK (ATP_APLICA_A IN ('MEDICO', 'ADMINISTRATIVO', 'AMBOS')),
  CONSTRAINT "CHL_ATP_ESTADO" CHECK (ATP_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_TIPO_PLANILLA

ALTER TABLE "ACS_TIPO_PLANILLA" ADD CONSTRAINT "PK_ACS_TIPO_PLANILLA" PRIMARY KEY ("ATP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_TIPO_PLANILLA" IS 'Tabla para representa, manejar y almacenar tipos de planilla que hay en el sistema'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_ID" IS 'ID de la planilla'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_NOMBRE" IS 'Nombre de la planilla'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_APLICA_A" IS 'A quién aplica (MEDICO/ADMIN/AMBOS)'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_DESC" IS 'Descripción opcional'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_ESTADO" IS 'Estado del registro'
/
COMMENT ON COLUMN "ACS_TIPO_PLANILLA"."ATP_DESCRIPCION" IS 'Descripción de la planilla.'
/

-- Table ACS_TURNO_PLANILLA

CREATE TABLE "ACS_TURNO_PLANILLA"(
  "ATRP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ATRP_HORAS" Number NOT NULL,
  "ATRP_MONTO_COBRADO_CENTRO" Number NOT NULL,
  "ATRP_MONTO_PAGADO_MEDICO" Number NOT NULL,
  "ATRP_PROCESADO" Number NOT NULL,
  "ATRP_FECHA_PROCESAMIENTO" Timestamp(6),
  "ADP_ID" Number NOT NULL,
  "ADM_ID" Number NOT NULL,
  CONSTRAINT "CHK_ATRP_PROCESADO" CHECK (ATRP_PROCESADO IN (0,1))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_TURNO_PLANILLA

ALTER TABLE "ACS_TURNO_PLANILLA" ADD CONSTRAINT "PK_ACS_TURNO_PLANILLA" PRIMARY KEY ("ATRP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_TURNO_PLANILLA" IS 'Tabla para representa, manejar y almacenar turnos de planillas que hay en el sistema'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_ID" IS 'Identificador único del turno procesado en planilla'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_HORAS" IS 'Horas trabajadas'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_MONTO_COBRADO_CENTRO" IS 'Monto cobrado al centro de salud'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_MONTO_PAGADO_MEDICO" IS 'Monto pagado al médico'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_PROCESADO" IS 'Indica si fue procesado'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ATRP_FECHA_PROCESAMIENTO" IS 'Fecha de procesamiento'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ADP_ID" IS 'Detalle de planilla asociado'
/
COMMENT ON COLUMN "ACS_TURNO_PLANILLA"."ADM_ID" IS 'Turno mensual registrado'
/

-- Table ACS_PROCEDIMIENTO_PLANILLA

CREATE TABLE "ACS_PROCEDIMIENTO_PLANILLA"(
  "APRP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ADP_ID" Number NOT NULL,
  "APA_ID" Number NOT NULL,
  "ACM_ID" Number,
  "APRP_CANTIDAD" Number NOT NULL,
  "APRP_MONTO_COBRADO" Number NOT NULL,
  "APRP_MONTO_PAGADO_MEDICO" Number NOT NULL,
  "APRP_ESTADO" Varchar2(10 ) NOT NULL,
  "APRP_PROCESADO" Number NOT NULL,
  "APRP_FECHA_PROCESAMIENTO" Timestamp(6),
  CONSTRAINT "CHK_APRP_PROCESADO" CHECK (APRP_PROCESADO IN (0,1)),
  CONSTRAINT "CHK_APRP_ESTADO" CHECK (APRP_ESTADO IN ('ACTIVO', 'INACTIVO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PROCEDIMIENTO_PLANILLA

ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "PK_ACS_PROCEDIMIENTO_PLANILLA" PRIMARY KEY ("APRP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PROCEDIMIENTO_PLANILLA" IS 'Tabla para representa, manejar y almacenar procedimiento de planilla que hay en el sistema'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_ID" IS 'Identificador único del procedimiento procesado en planilla'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."ADP_ID" IS 'Detalle de planilla asociado'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APA_ID" IS 'Procedimiento aplicado'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."ACM_ID" IS 'Centro médico relacionado'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_CANTIDAD" IS 'Cantidad de procedimientos'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_MONTO_COBRADO" IS 'Monto cobrado al centro'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_MONTO_PAGADO_MEDICO" IS 'Monto pagado al médico'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_ESTADO" IS 'Estado en el que se encuentra '
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_PROCESADO" IS 'Indica si fue procesado'
/
COMMENT ON COLUMN "ACS_PROCEDIMIENTO_PLANILLA"."APRP_FECHA_PROCESAMIENTO" IS 'Fecha procesamiento.'
/

-- Table ACS_ASIENTO_FINANCIERO

CREATE TABLE "ACS_ASIENTO_FINANCIERO"(
  "AAF_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AAF_TIPO" Varchar2(10 ) NOT NULL,
  "AAF_FUENTE" Varchar2(30 ) NOT NULL,
  "AAF_FECHA" Timestamp(6) NOT NULL,
  "AAF_PERIODO_ANIO" Number NOT NULL,
  "AAF_PERIODO_MES" Number NOT NULL,
  "AAF_MONTO" Number NOT NULL,
  "AAF_REFERENCIA_ID" Number,
  "AAF_DETALLE" Varchar2(255 ),
  "AAF_FECHA_CREACION" Timestamp(6) NOT NULL,
  "AAF_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  "ACM_ID" Number,
  CONSTRAINT "CHK_AAF_FUENTE" CHECK (AAF_FUENTE IN ('TURNO', 'PROCEDIMIENTO', 'PLANILLA_ADMINISTRATIVA', 'PLANILLA_MEDICA', 'AJUSTE')),
  CONSTRAINT "CHK_AAF_PERIODO_MES" CHECK (AAF_PERIODO_MES BETWEEN 1 AND 12),
  CONSTRAINT "CHK_AAF_TIPO" CHECK (AAF_TIPO IN ('INGRESO', 'GASTO'))
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_ASIENTO_FINANCIERO

ALTER TABLE "ACS_ASIENTO_FINANCIERO" ADD CONSTRAINT "PK_ACS_ASIENTO_FINANCIERO" PRIMARY KEY ("AAF_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_ASIENTO_FINANCIERO" IS 'Tabla para representa, manejar y almacenar asientos financieros que hay en el sistema'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_ID" IS 'Identificador único del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_TIPO" IS 'Naturaleza del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FUENTE" IS 'Origen del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FECHA" IS 'Fecha y hora del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_PERIODO_ANIO" IS 'Año contable del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_PERIODO_MES" IS 'Mes contable del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_MONTO" IS 'Monto del asiento (positivo)'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_REFERENCIA_ID" IS 'Identificador de referencia al origen '
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_DETALLE" IS 'Descripción breve del asiento'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."AAF_FECHA_ACTUALIZACION" IS 'Fecha de última actualización'
/
COMMENT ON COLUMN "ACS_ASIENTO_FINANCIERO"."ACM_ID" IS 'Centro de salud asociado '
/

-- Table ACS_RESUMEN_FIN_MENSUAL

CREATE TABLE "ACS_RESUMEN_FIN_MENSUAL"(
  "ARM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ARM_PERIODO_ANIO" Number NOT NULL,
  "ARM_PERIODO_MES" Number NOT NULL,
  "ARM_INGRESOS" Number NOT NULL,
  "ARM_GASTOS" Number NOT NULL,
  "ARM_UTILIDAD" Number NOT NULL,
  "ARM_FECHA_CREACION" Timestamp(6) NOT NULL,
  "ARM_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  CONSTRAINT "CHK_ARM_PERIODO_ANIO" CHECK (ARM_PERIODO_ANIO >= 2000),
  CONSTRAINT "CHK_ARM_PERIODO_MES" CHECK (ARM_PERIODO_MES BETWEEN 1 AND 12)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_RESUMEN_FIN_MENSUAL

ALTER TABLE "ACS_RESUMEN_FIN_MENSUAL" ADD CONSTRAINT "PK_ACS_RESUMEN_FIN_MENSUAL" PRIMARY KEY ("ARM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_RESUMEN_FIN_MENSUAL" IS 'Tabla para representa, manejar y almacenar los resumenes de fin de mes que hay en el sistema'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_ID" IS 'Identificador del resumen mensual'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_PERIODO_ANIO" IS 'Año del resumen'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_PERIODO_MES" IS 'Mes del resumen'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_INGRESOS" IS 'Total de ingresos del mes'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_GASTOS" IS 'Total de gastos del mes'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_UTILIDAD" IS 'Ingresos − Gastos'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_MENSUAL"."ARM_FECHA_ACTUALIZACION" IS 'Fecha de última actualización'
/

-- Table ACS_RESUMEN_FIN_CENTRO_MES

CREATE TABLE "ACS_RESUMEN_FIN_CENTRO_MES"(
  "ARCM_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "ARCM_PERIODO_ANIO" Number NOT NULL,
  "ARCM_PERIODO_MES" Number NOT NULL,
  "ARCM_INGRESOS" Number NOT NULL,
  "ARCM_GASTOS" Number NOT NULL,
  "ARCM_UTILIDAD" Number NOT NULL,
  "ARCM_FECHA_CREACION" Timestamp(6) NOT NULL,
  "ARCM_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
  "ACM_ID" Number,
  CONSTRAINT "CHK_ARCM_PERIODO_ANIO" CHECK (ARCM_PERIODO_ANIO >= 2000),
  CONSTRAINT "CHK_ARCM_PERIODO_MES" CHECK (ARCM_PERIODO_MES BETWEEN 1 AND 12)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_RESUMEN_FIN_CENTRO_MES

ALTER TABLE "ACS_RESUMEN_FIN_CENTRO_MES" ADD CONSTRAINT "PK_ACS_RESUMEN_FIN_CENTRO_MES" PRIMARY KEY ("ARCM_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_RESUMEN_FIN_CENTRO_MES" IS 'Tabla para representa, manejar y almacenar los resumenes finales de centros mensuales que hay en el sistema'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_ID" IS 'Identificador del resumen por centro'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_PERIODO_ANIO" IS ' Año del resumen'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_PERIODO_MES" IS 'Mes del resumen'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_INGRESOS" IS 'Total de ingresos del centro en el mes'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_GASTOS" IS 'Total de gastos del centro en el mes'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_UTILIDAD" IS 'Gastos del centro, ingresos.'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_FECHA_CREACION" IS 'Fecha de creación'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ARCM_FECHA_ACTUALIZACION" IS 'Fecha de última actualización'
/
COMMENT ON COLUMN "ACS_RESUMEN_FIN_CENTRO_MES"."ACM_ID" IS 'Centro de salud'
/

-- Table ACS_AUDITORIA_CENTRAL

CREATE TABLE "ACS_AUDITORIA_CENTRAL"(
  "AUD_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "AUD_OBJETO" Varchar2(100 ) NOT NULL,
  "AUD_OBJ_ID" Varchar2(4000 ) NOT NULL,
  "AUD_CAMPO" Varchar2(100 ) NOT NULL,
  "AUD_VALOR_ANTERIOR" Clob,
  "AUD_VALOR_NUEVO" Clob,
  "AUD_USUARIO" Varchar2(100 ),
  "AUD_OPERACION" Varchar2(15 ) NOT NULL,
  "AUD_FECHA_CAMBIO" Timestamp(6) NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_AUDITORIA_CENTRAL

ALTER TABLE "ACS_AUDITORIA_CENTRAL" ADD CONSTRAINT "PK_ACS_AUDITORIA_CENTRAL" PRIMARY KEY ("AUD_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_AUDITORIA_CENTRAL" IS 'Tabla de auditoría general para tener un manejo de que se cambió, quien lo hizo y cuando lo hizo'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_ID" IS 'ID propio del registro'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_OBJETO" IS 'Nombre de la tabla afectada'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_OBJ_ID" IS 'ID del registro afectado '
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_CAMPO" IS 'Campo que cambió'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_VALOR_ANTERIOR" IS 'Valor anterior (CLOB para soportar textos largos)'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_VALOR_NUEVO" IS 'Valor nuevo'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_USUARIO" IS 'Usuario que hizo el cambio'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_OPERACION" IS '''INSERT'', ''UPDATE'', ''DELETE'' ...'
/
COMMENT ON COLUMN "ACS_AUDITORIA_CENTRAL"."AUD_FECHA_CAMBIO" IS 'Fecha en la que se realizó el cambio'
/

-- Table ACS_PADRON

CREATE TABLE "ACS_PADRON"(
  "APN_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APN_CEDULA" Varchar2(9 ) NOT NULL,
  "APN_CODELEC" Varchar2(6 ) NOT NULL,
  "APN_RELLENO" Varchar2(1 ) NOT NULL,
  "APN_FECHA_CADUC" Timestamp(6) NOT NULL,
  "APN_JUNTA" Varchar2(30 ) NOT NULL,
  "APN_NOMBRE" Varchar2(30 ) NOT NULL,
  "APN_P_APELLIDO" Varchar2(30 ) NOT NULL,
  "APN_S_APELLIDO" Varchar2(30 ) NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_PADRON

ALTER TABLE "ACS_PADRON" ADD CONSTRAINT "PK_ACS_PADRON" PRIMARY KEY ("APN_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON TABLE "ACS_PADRON" IS 'Tabla de padron para poder tener un listado de usuarios '
/
COMMENT ON COLUMN "ACS_PADRON"."APN_ID" IS 'ID propio del registro'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_CEDULA" IS 'Cedula del ciudadano '
/
COMMENT ON COLUMN "ACS_PADRON"."APN_CODELEC" IS 'Codigo Electoral donde est  inscrito'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_RELLENO" IS 'Campo que cambió'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_FECHA_CADUC" IS 'Fecha vencimiento de la cedula'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_JUNTA" IS 'Junta Receptora de Votos'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_NOMBRE" IS 'Nombre completo del ciudadano'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_P_APELLIDO" IS 'Primer apellido'
/
COMMENT ON COLUMN "ACS_PADRON"."APN_S_APELLIDO" IS 'Segundo apellido'
/

-- Table ACS_PERFIL

CREATE TABLE "ACS_PERFIL"(
  "APF_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APF_NOMBRE" Char(100 ) NOT NULL,
  "APF_DESCRIPCION" Char(400 ),
  "APF_PADRE_ID" Number
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_PERFIL

CREATE UNIQUE INDEX "UQ_APF_NOMBRE" ON "ACS_PERFIL" ("APF_NOMBRE")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "APF_X_APF" ON "ACS_PERFIL" ("APF_PADRE_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_PERFIL

ALTER TABLE "ACS_PERFIL" ADD CONSTRAINT "PK_ACS_PERFIL" PRIMARY KEY ("APF_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table ACS_PERFIL_PERMISO

CREATE TABLE "ACS_PERFIL_PERMISO"(
  "APP_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 20) NOT NULL,
  "APR_ID" Number NOT NULL,
  "APF_ID" Number NOT NULL
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Create indexes for table ACS_PERFIL_PERMISO

CREATE INDEX "APP_X_APR" ON "ACS_PERFIL_PERMISO" ("APR_ID")
TABLESPACE "TBS_ACS_INDICES"
/

CREATE INDEX "APP_X_APF" ON "ACS_PERFIL_PERMISO" ("APF_ID")
TABLESPACE "TBS_ACS_INDICES"
/

-- Add keys for table ACS_PERFIL_PERMISO

ALTER TABLE "ACS_PERFIL_PERMISO" ADD CONSTRAINT "PK_ACS_PERFIL_PERMISO" PRIMARY KEY ("APP_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table ACS_TIPO_MOV_RANGO

CREATE TABLE "ACS_TIPO_MOV_RANGO"(
  "ATMR_ID" Number GENERATED ALWAYS AS IDENTITY(
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 0) NOT NULL,
  "ATM_ID" Number NOT NULL,
  "ATMR_RANGO_MIN" Number,
  "ATMR_RANGO_MAX" Number,
  "ATMR_PORCENTAJE" Number,
  "ATMR_MONTO_FIJO" Number,
  "ATMR_ESTADO" Number,
  CONSTRAINT "CHK_ATMR_RANGOS_VALIDOS" CHECK (ATMR_RANGO_MAX > ATMR_RANGO_MIN),
  CONSTRAINT "CHK_RANGOS_POSITIVOS" CHECK (ATMR_RANGO >= 0 and ARMR_RANGO_MAX >= 0;),
  CONSTRAINT "CHK_ESTADO" CHECK (ATMR_ESTADO in ('Activo', 'Inactivo');)
)
TABLESPACE "TBS_ACS_DATOS"
/

-- Add keys for table ACS_TIPO_MOV_RANGO

ALTER TABLE "ACS_TIPO_MOV_RANGO" ADD CONSTRAINT "PK_ACS_TIPO_MOV_RANGO" PRIMARY KEY ("ATMR_ID")
   USING INDEX TABLESPACE "TBS_ACS_DATOS"
/

-- Table and Columns comments section

COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATMR_ID" IS 'Identificador único del rango.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATM_ID" IS 'Referencia al tipo de movimiento al que pertenece el rango (por ejemplo, renta, banco, caja, etc.).'
/
COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATMR_RANGO_MIN" IS 'Límite inferior del salario base para aplicar este rango.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATMR_RANGO_MAX" IS 'Límite superior del salario base para aplicar este rango.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATMR_PORCENTAJE" IS 'Porcentaje a aplicar sobre el salario base dentro del rango.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATMR_MONTO_FIJO" IS 'Monto fijo a aplicar si no depende de porcentaje.'
/
COMMENT ON COLUMN "ACS_TIPO_MOV_RANGO"."ATMR_ESTADO" IS 'Estado del rango (activo o inactivo).'
/


-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "APA_X_APD" FOREIGN KEY ("APD_ID") REFERENCES "ACS_PROCEDIMIENTO" ("APD_ID")
/



ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "APA_X_AME" FOREIGN KEY ("AME_ID") REFERENCES "ACS_MEDICO" ("AME_ID")
/



ALTER TABLE "ACS_ESCALA_MENSUAL" ADD CONSTRAINT "AEM_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_AEM" FOREIGN KEY ("AEM_ID") REFERENCES "ACS_ESCALA_MENSUAL" ("AEM_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_APM" FOREIGN KEY ("APM_ID") REFERENCES "ACS_PUESTO_MEDICO" ("APM_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_ATU" FOREIGN KEY ("ATU_ID") REFERENCES "ACS_TURNO" ("ATU_ID")
/



ALTER TABLE "ACS_DETALLE_MENSUAL" ADD CONSTRAINT "ADM_X_AME" FOREIGN KEY ("AME_ID") REFERENCES "ACS_MEDICO" ("AME_ID")
/



ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "ADU_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_CUENTA_BANCARIA" ADD CONSTRAINT "ACB_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_CUENTA_BANCARIA" ADD CONSTRAINT "ACB_X_ABA" FOREIGN KEY ("ABA_ID") REFERENCES "ACS_BANCO" ("ABA_ID")
/



ALTER TABLE "ACS_PUESTOXCENTRO" ADD CONSTRAINT "APC_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PUESTOXCENTRO" ADD CONSTRAINT "APC_X_APM" FOREIGN KEY ("APM_ID") REFERENCES "ACS_PUESTO_MEDICO" ("APM_ID")
/



ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "ADU_X_ATD" FOREIGN KEY ("ATD_ID") REFERENCES "ACS_TIPO_DOCUMENTO" ("ATD_ID")
/



ALTER TABLE "ACS_USUARIO" ADD CONSTRAINT "AUS_X_APE" FOREIGN KEY ("APE_ID") REFERENCES "ACS_PERSONA" ("APE_ID")
/



ALTER TABLE "ACS_ADMINISTRATIVO" ADD CONSTRAINT "AAD_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_MEDICO" ADD CONSTRAINT "AME_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_BITACORA_PLANILLA" ADD CONSTRAINT "ABP_X_APL" FOREIGN KEY ("APL_ID") REFERENCES "ACS_PLANILLA" ("APL_ID")
/



ALTER TABLE "ACS_PLANILLA" ADD CONSTRAINT "APL_X_ADP" FOREIGN KEY ("ATP_ID") REFERENCES "ACS_TIPO_PLANILLA" ("ATP_ID")
/



ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "ADP_X_APL" FOREIGN KEY ("APL_ID") REFERENCES "ACS_PLANILLA" ("APL_ID")
/



ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "ADP_X_ACB" FOREIGN KEY ("ACB_ID") REFERENCES "ACS_CUENTA_BANCARIA" ("ACB_ID")
/



ALTER TABLE "ACS_MOVIMIENTO_PLANILLA" ADD CONSTRAINT "AMP_X_ADP" FOREIGN KEY ("APD_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_MOVIMIENTO_PLANILLA" ADD CONSTRAINT "ATM_X_AMP" FOREIGN KEY ("ATM_ID") REFERENCES "ACS_TIPO_MOV" ("ATM_ID")
/



ALTER TABLE "ACS_ENVIO_COMP" ADD CONSTRAINT "AEC_X_ADP" FOREIGN KEY ("ADP_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_BITACORA_PLANILLA" ADD CONSTRAINT "AUS_X_ABP" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_PERSONAL_TIPO_PLANILLA" ADD CONSTRAINT "APTP_X_ATP" FOREIGN KEY ("ATP_ID") REFERENCES "ACS_TIPO_PLANILLA" ("ATP_ID")
/



ALTER TABLE "ACS_PERSONAL_TIPO_PLANILLA" ADD CONSTRAINT "APTP_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_TURNO_PLANILLA" ADD CONSTRAINT "ATRP_X_ADP" FOREIGN KEY ("ADP_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_TURNO_PLANILLA" ADD CONSTRAINT "ATRP_X_ADM" FOREIGN KEY ("ADM_ID") REFERENCES "ACS_DETALLE_MENSUAL" ("ADM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "APRP_X_ADP" FOREIGN KEY ("ADP_ID") REFERENCES "ACS_DETALLE_PLANILLA" ("ADP_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "APRP_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTO_PLANILLA" ADD CONSTRAINT "APRP_X_APA" FOREIGN KEY ("APA_ID") REFERENCES "ACS_PROC_APLICADO" ("APA_ID")
/



ALTER TABLE "ACS_ASIENTO_FINANCIERO" ADD CONSTRAINT "AAF_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_DETALLE_PLANILLA" ADD CONSTRAINT "ADP_X_AUS" FOREIGN KEY ("AUS_ID") REFERENCES "ACS_USUARIO" ("AUS_ID")
/



ALTER TABLE "ACS_RESUMEN_FIN_CENTRO_MES" ADD CONSTRAINT "ARM_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROC_APLICADO" ADD CONSTRAINT "APA_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTOXCENTRO" ADD CONSTRAINT "APRC_X_ACM" FOREIGN KEY ("ACM_ID") REFERENCES "ACS_CENTRO_MEDICO" ("ACM_ID")
/



ALTER TABLE "ACS_PROCEDIMIENTOXCENTRO" ADD CONSTRAINT "APRC_X_APD" FOREIGN KEY ("APD_ID") REFERENCES "ACS_PROCEDIMIENTO" ("APD_ID")
/



ALTER TABLE "ACS_DOCUMENTO_USUARIO" ADD CONSTRAINT "ADU_X_APF" FOREIGN KEY ("APF_ID") REFERENCES "ACS_PERFIL" ("APF_ID")
/



ALTER TABLE "ACS_PERFIL_PERMISO" ADD CONSTRAINT "APP_X_APR" FOREIGN KEY ("APR_ID") REFERENCES "ACS_PERMISO" ("APR_ID")
/



ALTER TABLE "ACS_PERFIL_PERMISO" ADD CONSTRAINT "APP_X_APF" FOREIGN KEY ("APF_ID") REFERENCES "ACS_PERFIL" ("APF_ID")
/



ALTER TABLE "ACS_PERFIL" ADD CONSTRAINT "APF_X_APF" FOREIGN KEY ("APF_PADRE_ID") REFERENCES "ACS_PERFIL" ("APF_ID")
/



ALTER TABLE "ACS_TURNO" ADD CONSTRAINT "ATU_X_APM" FOREIGN KEY ("APM_ID") REFERENCES "ACS_PUESTO_MEDICO" ("APM_ID")
/



ALTER TABLE "ACS_TURNO" ADD CONSTRAINT "ATU_X_AME" FOREIGN KEY ("AME_ID") REFERENCES "ACS_MEDICO" ("AME_ID")
/



ALTER TABLE "ACS_TIPO_MOV_RANGO" ADD CONSTRAINT "ATMR_X_ATM" FOREIGN KEY ("ATM_ID") REFERENCES "ACS_TIPO_MOV" ("ATM_ID")
/



-- Create roles section -------------------------------------------------

CREATE ROLE "MEDICO"
/
CREATE ROLE "ADMINISTRATIVO"
/
CREATE ROLE "ADMINISTRADOR"
/

-- Grant permissions section -------------------------------------------------


GRANT SELECT ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT UPDATE ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT INSERT ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT DELETE ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
GRANT READ ON "ACS_USUARIO" TO "ADMINISTRADOR"
/
