CREATE MATERIALIZED VIEW ACS_MV_SOLICITUDES_USUARIOS AS
SELECT 
    APE_CEDULA, 
    APE_NOMBRE, 
    APE_P_APELLIDO, 
    APE_S_APELLIDO, 
    -- EDAD EN AÑOS
    FLOOR(MONTHS_BETWEEN(SYSDATE, APE_FECHA_NACIMIENTO) / 12) AS APE_EDAD,
    APE_TIPO_USUARIO, 
    APE_FECHA_CREACION
FROM ACS_PERSONA
WHERE APE_ESTADO_REGISTRO = 'PENDIENTE'
ORDER BY APE_FECHA_CREACION;

SELECT * FROM ACS_MV_SOLICITUDES_USUARIOS;