/*
-- ! TABLA
CREATE TABLE "ACS_PERSONA"(
    "APE_ID" Number GENERATED ALWAYS AS IDENTITY(
        START WITH 1
        INCREMENT BY 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20) NOT NULL,
    "APE_CEDULA" Varchar2(20 ) NOT NULL,
    "APE_NOMBRE" Varchar2(200 ) NOT NULL,
    "APE_P_APELLIDO" Varchar2(100 ) NOT NULL,
    "APE_S_APELLIDO" Varchar2(100 ),
    "APE_FECHA_NACIMIENTO" Timestamp(6) NOT NULL,
    "APE_SEXO" Varchar2(10 ),
    "APE_ESTADO_CIVIL" Varchar2(15 ),
    "APE_NACIONALIDAD" Varchar2(10 ),
    "APE_TIPO_USUARIO" Varchar2(15 ) NOT NULL,
    "APE_ESTADO_REGISTRO" Varchar2(10 ) NOT NULL,
    "APE_EMAIL" Varchar2(255 ) NOT NULL,
    "APE_TELEFONO" Varchar2(20 ),
    "APE_RESIDENCIA" Varchar2(255 ),
    "APE_DIRECION_CASA" Varchar2(255 ),
    "APE_DIRECCION_TRABAJO" Varchar2(255 ),
    "APE_FECHA_CREACION" Timestamp(6) DEFAULT SYSDATE NOT NULL,
    "APE_FECHA_ACTUALIZACION" Timestamp(6) NOT NULL,
    CONSTRAINT "CHK_APE_ESTADO_REGISTRO" CHECK (APE_ESTADO_REGISTRO IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    CONSTRAINT "CHK_APE_SEXO" CHECK (APE_SEXO IN ('MASCULINO', 'FEMENINO')),
    CONSTRAINT "CHK_APE_ESTADO_CIVIL" CHECK (APE_ESTADO_CIVIL IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO', 'UNION LIBRE')),
    CONSTRAINT "CHK_APE_NACIONALIDAD" CHECK (APE_NACIONALIDAD IN ('NACIONAL', 'EXTRANJERO')),
    CONSTRAINT "CHK_APE_TIPO_USUARIO" CHECK (APE_TIPO_USUARIO in ('MEDICO', 'ADMINISTRATIVO'))
)
*/

-- ** Borrar registros de la tabla ACS_PERSONA **
/*
DELETE FROM ACS_PERSONA;
COMMIT;
*/

-- ** REGISTRAR DATOS
DECLARE
    V_LINE VARCHAR2(1000);
    V_PRIMERA_LINEA BOOLEAN := TRUE;
    
    CURSOR C_LINES IS
        SELECT COLUMN_VALUE AS LINE
        FROM TABLE(
            SYS.ODCIVARCHAR2LIST(
                'APE_CEDULA,APE_NOMBRE,APE_P_APELLIDO,APE_S_APELLIDO,APE_FECHA_NACIMIENTO,APE_SEXO,APE_ESTADO_CIVIL,APE_NACIONALIDAD,APE_TIPO_USUARIO,APE_EMAIL,APE_TELEFONO,APE_RESIDENCIA,APE_DIRECION_CASA,APE_DIRECCION_TRABAJO',
                'CED123456,Juan,Perez,Gomez,15/04/1985,MASCULINO,CASADO,NACIONAL,MEDICO,juan.perez@mail.com,555-1234,Ciudad A,Calle 123,Oficina 456',
                'CED234567,Maria,Lopez,Diaz,22/08/1990,FEMENINO,SOLTERO,EXTRANJERO,ADMINISTRATIVO,maria.lopez@mail.com,555-5678,Ciudad B,Calle 456,Oficina 789',
                'CED345678,Carlos,Ramirez,Suarez,10/12/1975,MASCULINO,DIVORCIADO,NACIONAL,MEDICO,carlos.ramirez@mail.com,555-9012,Ciudad C,Calle 789,Oficina 012',
                'CED456789,Ana,Martinez,Castro,05/03/1982,FEMENINO,CASADO,NACIONAL,ADMINISTRATIVO,ana.martinez@mail.com,555-3456,Ciudad D,Calle 234,Oficina 345',
                'CED567890,Jose,Gonzalez,Reyes,18/07/1988,MASCULINO,SOLTERO,EXTRANJERO,MEDICO,jose.gonzalez@mail.com,555-6789,Ciudad E,Calle 567,Oficina 678',
                'CED678901,Laura,Hernandez,Morales,25/11/1992,FEMENINO,UNION LIBRE,NACIONAL,ADMINISTRATIVO,laura.hernandez@mail.com,555-2345,Ciudad F,Calle 890,Oficina 901',
                'CED789012,Pedro,Alvarez,Rojas,30/09/1980,MASCULINO,VIUDO,NACIONAL,MEDICO,pedro.alvarez@mail.com,555-4567,Ciudad G,Calle 012,Oficina 123',
                'CED890123,Sofia,Jimenez,Ortiz,12/02/1987,FEMENINO,CASADO,EXTRANJERO,ADMINISTRATIVO,sofia.jimenez@mail.com,555-7890,Ciudad H,Calle 345,Oficina 456',
                'CED901234,Diego,Castillo,Padilla,08/06/1995,MASCULINO,SOLTERO,NACIONAL,MEDICO,diego.castillo@mail.com,555-0123,Ciudad I,Calle 678,Oficina 789',
                'CED012345,Valeria,Mendoza,Salas,19/01/1983,FEMENINO,DIVORCIADO,NACIONAL,ADMINISTRATIVO,valeria.mendoza@mail.com,555-3450,Ciudad J,Calle 901,Oficina 234',
                '118690700,Juan,Camacho,Solano,12/05/2000,MASCULINO,SOLTERO,NACIONAL,MEDICO,juancarlos19defebrero@gmail.com,3104567890,Bogota,Carrera 45 # 32-12,Empresa XYZ'
            )
        );
BEGIN
    FOR R_LINE IN C_LINES LOOP
        V_LINE := R_LINE.LINE;

        -- Saltar encabezado si existe
        IF V_PRIMERA_LINEA THEN
            V_PRIMERA_LINEA := FALSE;
            CONTINUE;
        END IF;
        
        BEGIN
            -- Llamar al procedimiento para insertar registro. UTIL_GET_FIELD(LINEA, POSICION)
            ACS_PRC_REGISTRO_PERSONA(
                P_APE_CEDULA => UTIL_GET_FIELD(V_LINE, 1),
                P_APE_NOMBRE => UTIL_GET_FIELD(V_LINE, 2),
                P_APE_P_APELLIDO => UTIL_GET_FIELD(V_LINE, 3),
                P_APE_S_APELLIDO => UTIL_GET_FIELD(V_LINE, 4),
                P_APE_FECHA_NACIMIENTO => TO_TIMESTAMP(UTIL_GET_FIELD(V_LINE, 5), 'DD/MM/YYYY'),
                P_APE_SEXO => UTIL_GET_FIELD(V_LINE, 6),
                P_APE_ESTADO_CIVIL => UTIL_GET_FIELD(V_LINE, 7),
                P_APE_NACIONALIDAD => UTIL_GET_FIELD(V_LINE, 8),
                P_APE_TIPO_USUARIO => UTIL_GET_FIELD(V_LINE, 9),
                P_APE_EMAIL => UTIL_GET_FIELD(V_LINE, 10),
                P_APE_TELEFONO => UTIL_GET_FIELD(V_LINE, 11),
                P_APE_RESIDENCIA => UTIL_GET_FIELD(V_LINE, 12),
                P_APE_DIRECION_CASA => UTIL_GET_FIELD(V_LINE, 13),
                P_APE_DIRECCION_TRABAJO => UTIL_GET_FIELD(V_LINE, 14)
            );
        COMMIT;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('[Error] insertar registro');
                ROLLBACK;
        END;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('[ok] Cargar datos: Proceso completado.');
END;
/

-- APROBAR O RECHAZAR. ACS_PRC_ACTUALIZAR_ESTADO_PERSONA(CEDULA, NEW_ESTADO)
BEGIN
    ACS_PRC_ACTUALIZAR_ESTADO_PERSONA('118690700', 'APROBADO');
    ACS_PRC_ACTUALIZAR_ESTADO_PERSONA('CED345678', 'APROBADO');
    ACS_PRC_ACTUALIZAR_ESTADO_PERSONA('CED678901', 'APROBADO');
    ACS_PRC_ACTUALIZAR_ESTADO_PERSONA('CED890123', 'APROBADO');

    ACS_PRC_ACTUALIZAR_ESTADO_PERSONA('CED234567', 'RECHAZADO');
END;
/

-- ** CONSULTAS **
select *
from ACS_MV_SOLICITUDES_USUARIOS;
/

select *
from ACS_PERSONA;
/