-- PRODECIMIENTO PARA CARGAR UNA SOLICITUD
CREATE OR REPLACE PROCEDURE ACS_PRC_REGISTRO_PERSONA (
    P_APE_CEDULA IN ACS_PERSONA.APE_CEDULA%TYPE,
    P_APE_NOMBRE IN ACS_PERSONA.APE_NOMBRE%TYPE,
    P_APE_P_APELLIDO IN ACS_PERSONA.APE_P_APELLIDO%TYPE,
    P_APE_S_APELLIDO IN ACS_PERSONA.APE_S_APELLIDO%TYPE,
    P_APE_FECHA_NACIMIENTO IN ACS_PERSONA.APE_FECHA_NACIMIENTO%TYPE,
    P_APE_SEXO IN ACS_PERSONA.APE_SEXO%TYPE,
    P_APE_ESTADO_CIVIL IN ACS_PERSONA.APE_ESTADO_CIVIL%TYPE,
    P_APE_NACIONALIDAD IN ACS_PERSONA.APE_NACIONALIDAD%TYPE,
    P_APE_TIPO_USUARIO IN ACS_PERSONA.APE_TIPO_USUARIO%TYPE,
    P_APE_EMAIL IN ACS_PERSONA.APE_EMAIL%TYPE,
    P_APE_TELEFONO IN ACS_PERSONA.APE_TELEFONO%TYPE,
    P_APE_RESIDENCIA IN ACS_PERSONA.APE_RESIDENCIA%TYPE,
    P_APE_DIRECION_CASA IN ACS_PERSONA.APE_DIRECION_CASA%TYPE,
    P_APE_DIRECCION_TRABAJO IN ACS_PERSONA.APE_DIRECCION_TRABAJO%TYPE
) AS
BEGIN
    INSERT INTO ACS_PERSONA (
        APE_CEDULA,
        APE_NOMBRE,
        APE_P_APELLIDO,
        APE_S_APELLIDO,
        APE_FECHA_NACIMIENTO,
        APE_SEXO,
        APE_ESTADO_CIVIL,
        APE_NACIONALIDAD,
        APE_TIPO_USUARIO,
        APE_ESTADO_REGISTRO,
        APE_EMAIL,
        APE_TELEFONO,
        APE_RESIDENCIA,
        APE_DIRECION_CASA,
        APE_DIRECCION_TRABAJO,
        APE_FECHA_ACTUALIZACION
    ) VALUES (
        P_APE_CEDULA,
        P_APE_NOMBRE,
        P_APE_P_APELLIDO,
        P_APE_S_APELLIDO,
        P_APE_FECHA_NACIMIENTO,
        P_APE_SEXO,
        P_APE_ESTADO_CIVIL,
        P_APE_NACIONALIDAD,
        P_APE_TIPO_USUARIO,
        'PENDIENTE',
        P_APE_EMAIL,
        P_APE_TELEFONO,
        P_APE_RESIDENCIA,
        P_APE_DIRECION_CASA,
        P_APE_DIRECCION_TRABAJO,
        SYSDATE
    );
END;
/

-- Aprobar o rechazar una solicitud de personal
CREATE OR REPLACE PROCEDURE ACS_PRC_ACTUALIZAR_ESTADO_PERSONA (
    P_APE_CEDULA IN ACS_PERSONA.APE_CEDULA%TYPE,
    P_NEW_ESTADO IN ACS_PERSONA.APE_ESTADO_REGISTRO%TYPE
) AS
BEGIN
    IF P_NEW_ESTADO NOT IN ('APROBADO', 'RECHAZADO') THEN
        RAISE_APPLICATION_ERROR(-20001, '[INFO] Estado inválido. Solo se permiten APROBADO o RECHAZADO.');
    END IF;

    UPDATE ACS_PERSONA
    SET APE_ESTADO_REGISTRO = P_NEW_ESTADO,
        APE_FECHA_ACTUALIZACION = SYSDATE
    WHERE APE_CEDULA = P_APE_CEDULA;
END;