/* 
TODO un trigger que actualice el ultimo acceso del usuario en  planillas, escalas o procedimiento
si hace algun movieminto ahi se actualiza la fecha de ultimo acceso en usuario
en total son 3 triggers, uno para cada tabla
*/

/*
CREATE TABLE "ACS_PROC_APLICADO"(
...
    "APA_FECHA" Timestamp(6) NOT NULL,
    "AME_ID" Number NOT NULL,
...
*/

-- ACS_PROC_APLICADO
CREATE OR REPLACE TRIGGER TRG_ACS_PRA_UPDATE
BEFORE UPDATE ON ACS_PROC_APLICADO
FOR EACH ROW
-- ACTUALIZAR ASC_USUARIO.AUS_ULTIMO_ACCESO POR EL CAMPO DE APA_FECHA DEL REGISTRO CREADO O MODIFICADO
BEGIN
    UPDATE ACS_USUARIO
    SET AUS_ULTIMO_ACCESO = :NEW.APA_FECHA
    WHERE AUS_ID = :NEW.AME_ID;
END;

-- ACS_DETALLE_MENSUAL
CREATE OR REPLACE TRIGGER TRG_ACS_DME_UPDATE
BEFORE UPDATE ON ACS_DETALLE_MENSUAL
FOR EACH ROW
-- ACTUALIZAR ASC_USUARIO.AUS_ULTIMO_ACCESO POR EL CAMPO DE ADM_FECHA_DEL_REGISTRO DEL REGISTRO CREADO O MODIFICADO
BEGIN
    UPDATE ACS_USUARIO
    SET AUS_ULTIMO_ACCESO = :NEW.ADM_FECHA
    WHERE AUS_ID = :NEW.AME_ID;
END;

-- TODO falta de planillas o Administrativo