-- ! GESTION DE PARÁMETROS


-- FUNCION
-- CREA UNA FUNCION DE OBTENER PARAMETROS DE LA TABLA ACS_PARAMETROS
CREATE OR REPLACE FUNCTION ACS_FUN_OBTENER_PARAMETRO(P_NOMBRE_PARAMETRO ACS_PARAMETROS.APA_NOMBRE_PARAMETRO%TYPE)
RETURN VARCHAR2 IS
    V_VALOR ACS_PARAMETROS.APA_VALOR_PARAMETRO%TYPE;
BEGIN
    SELECT APA_VALOR_PARAMETRO INTO V_VALOR
    FROM ACS_PARAMETROS
    WHERE APA_NOMBRE_PARAMETRO = P_NOMBRE_PARAMETRO;

    RETURN V_VALOR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('[ERROR] (ACS_FUN_OBTENER_PARAMETRO): NO EXISTE EL PARÁMETRO: ' || P_NOMBRE_PARAMETRO);
        RAISE_APPLICATION_ERROR(-20003, '[ERROR] (ACS_FUN_OBTENER_PARAMETRO): NO EXISTE EL PARÁMETRO: ' || P_NOMBRE_PARAMETRO);
END;
/

-- CÓDIGO PARA INSERCIÓN/ACTUALIZACIÓN DE DATOS, ESTOS SON LOS DATOS MINIMOS PARA LA BASE DE DATOS: CONFIGURACION DE CORREO Y EL CORREO DEL DBA
MERGE INTO ACS_PARAMETROS t
USING (
    -- Parametro global
    SELECT  'CORREO_DBA' APA_NOMBRE_PARAMETRO, 
            'cbcarlosm@gmail.com' APA_VALOR_PARAMETRO,
            'Correo del DBA' APA_DESCRIPCION,
            'CORREO_DBA' APA_TIPO_PARAMETRO FROM DUAL UNION ALL
    -- Configuracion SMTP
    SELECT 'SMTP_USE_TLS', 'N', 'Indica si se usa STARTTLS (Y/N), N no usa wallet', 'SMTP' FROM DUAL UNION ALL
    SELECT 'SMTP_ACL_FILE', 'brevo_acl.xml', 'Archivo ACL para SMTP', 'SMTP' FROM DUAL UNION ALL
    SELECT 'SMTP_HOST', 'smtp-relay.brevo.com', 'Servidor para envio de correos', 'SMTP' FROM DUAL UNION ALL
    SELECT 'SMTP_PORT', '587', 'Puerto del servidor SMTP', 'SMTP' FROM DUAL UNION ALL
    -- Datos Servidor SMTP
    SELECT 'SMTP_CORREO', 'juancarlos19defebrerohat@gmail.com', 'Correo registrado para el SMTP', 'SMTP' FROM DUAL UNION ALL
    SELECT 'SMTP_USUARIO', '9a1e38001@smtp-brevo.com', 'Usuario (login) del servidor SMTP', 'SMTP' FROM DUAL
) s
ON (t.APA_NOMBRE_PARAMETRO = s.APA_NOMBRE_PARAMETRO)
WHEN MATCHED THEN
    UPDATE SET
        t.APA_VALOR_PARAMETRO = s.APA_VALOR_PARAMETRO,
        t.APA_DESCRIPCION = s.APA_DESCRIPCION,
        t.APA_TIPO_PARAMETRO = s.APA_TIPO_PARAMETRO
WHEN NOT MATCHED THEN
    INSERT (APA_NOMBRE_PARAMETRO, APA_VALOR_PARAMETRO, APA_DESCRIPCION, APA_TIPO_PARAMETRO)
    VALUES (s.APA_NOMBRE_PARAMETRO, s.APA_VALOR_PARAMETRO, s.APA_DESCRIPCION, s.APA_TIPO_PARAMETRO);
COMMIT;
/