-- ** CONFIGURACIONES DE ENVÍO DE CORREO **

/*
!NOTAS:
    * ENTORNO: ORACLE19C. WINDOWS11

    * CONFIGURACIÓN BREVO:
        - YA CONFIGURADO PARA LOS SIGUIENTES PARAMETROS

    * VARIABLE:
        - USUARIO_PARA_CORREOS: JUAN
*/

-- ------------------------------------------------------------
-- ** Sección: Configuración ACL para envío de correos vía SMTP **

/*
    ACL (ACCESS CONTROL LIST) ES UN CONJUNTO DE REGLAS QUE DEFINEN LOS PERMISOS DE ACCESO A RECURSOS DE RED ESPECÍFICOS PARA USUARIOS O ROLES EN ORACLE DATABASE.
    ESTOS PERMISOS SON NECESARIOS PARA QUE LOS PROCEDIMIENTOS ALMACENADOS PUEDAN INTERACTUAR CON SERVICIOS EXTERNOS, COMO SERVIDORES SMTP PARA EL ENVÍO DE CORREOS ELECTRÓNICOS.
*/

DECLARE
    V_ACL_FILE VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_ACL_FILE');
BEGIN
    -- * PASO 1: LIMPIAR ACLS ANTERIORES *
    DBMS_NETWORK_ACL_ADMIN.DROP_ACL(ACL => V_ACL_FILE);
    DBMS_OUTPUT.PUT_LINE('[OK] ACL ANTERIOR ELIMINADO');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -46104 THEN
            DBMS_OUTPUT.PUT_LINE('[INFO] NO EXISTÍA ACL PREVIO');
        ELSE
            DBMS_OUTPUT.PUT_LINE('[WARN] ERROR ELIMINANDO ACL: ' || SQLERRM);
        END IF;
END;
/

DECLARE
    V_ACL_FILE VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_ACL_FILE');
    V_PORT NUMBER := TO_NUMBER(ACS_FUN_OBTENER_PARAMETRO('SMTP_PORT'));
    V_HOST VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_HOST');
BEGIN
-- * PASO 2: CREAR ACL Y ASIGNAR PRIVILEGIOS A UN USUARIO *
    DBMS_NETWORK_ACL_ADMIN.CREATE_ACL(
        acl         => V_ACL_FILE,
        description => 'Acceso SMTP ' || V_HOST || ':' || V_PORT,
        principal   => 'JUAN',
        is_grant    => TRUE,
        privilege   => 'connect'
    );
    DBMS_OUTPUT.PUT_LINE('[OK] ACL creado con privilegio CONNECT');

    DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE(
        acl       => V_ACL_FILE,
        principal => 'JUAN',
        is_grant  => TRUE,
        privilege => 'resolve'
    );
    DBMS_OUTPUT.PUT_LINE('[OK] Privilegio RESOLVE agregado');

    -- * PASO 3: ASIGNAR ACL A HOST SMTP *
    DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(
        acl  => V_ACL_FILE,
        host => V_HOST,
        lower_port => V_PORT,
        upper_port => V_PORT
    );
    DBMS_OUTPUT.PUT_LINE('[OK] ACL asignado a ' || V_HOST || ':' || V_PORT);
    COMMIT;
END;
/

-- ------------------------------------------------------------
-- ** Sección: Procedimiento almacenado para envío de correos vía SMTP **

-- *  PROCEDIMIENTO ALMACENADO DE ENVIO DE CORREO NOTIFICADOR*
CREATE OR REPLACE PROCEDURE ACS_PRC_CORREO_NOTIFICADOR (
    P_DESTINATARIO IN VARCHAR2,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2
) 
IS
    -- CONEXION
    MAIL_CONN UTL_SMTP.CONNECTION;
    -- COSTANTES
    CRLF CONSTANT VARCHAR2(2) := UTL_TCP.CRLF;
    -- PARAMETROS
    P_SMTP_USE_TLS VARCHAR2(1) := ACS_FUN_OBTENER_PARAMETRO('SMTP_USE_TLS');
    P_SMTP_HOST VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_HOST');
    P_SMTP_PORT NUMBER := TO_NUMBER(ACS_FUN_OBTENER_PARAMETRO('SMTP_PORT'));
    P_SMTP_USERNAME VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_USUARIO');
    P_REMITENTE VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_CORREO');
    P_CLAVE_SMTP VARCHAR2(100) := ACS_FUN_OBTENER_CLAVE('SMTP_CLAVE');
    -- VARIABLES
    V_LISTA_DESTINATARIOS SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST();
BEGIN
    -- CONTEO
    V_LISTA_DESTINATARIOS := SYS.ODCIVARCHAR2LIST();
    FOR i IN 1 .. REGEXP_COUNT(P_DESTINATARIO, '[^,]+') LOOP
        V_LISTA_DESTINATARIOS.EXTEND;
        V_LISTA_DESTINATARIOS(i) := TRIM(REGEXP_SUBSTR(P_DESTINATARIO, '[^,]+', 1, i));
    END LOOP;
    -- CHECK
    IF V_LISTA_DESTINATARIOS.COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('[ERROR] (ACS_PRC_CORREO_NOTIFICADOR): DEBE INDICAR AL MENOS UN DESTINATARIO.');
        RAISE_APPLICATION_ERROR(-20000, '[ERROR] (ACS_PRC_CORREO_NOTIFICADOR): DEBE INDICAR AL MENOS UN DESTINATARIO.');
    END IF;

    -- CONECTAR AL SERVIDOR SMTP
    MAIL_CONN := UTL_SMTP.OPEN_CONNECTION(P_SMTP_HOST, P_SMTP_PORT);
    UTL_SMTP.EHLO(MAIL_CONN, P_SMTP_HOST);

    -- STARTTLS OPCIONAL (POR DEFECTO DESACTIVADO PARA EVITAR ORA-29024 SI NO HAY WALLET CONFIGURADO)
    IF UPPER(P_SMTP_USE_TLS) = 'Y' THEN
        UTL_SMTP.STARTTLS(MAIL_CONN); -- REQUIERE WALLET/CA CONFIGURADO A NIVEL DE BASE
        UTL_SMTP.EHLO(MAIL_CONN, P_SMTP_HOST);
    END IF;

    -- Autenticación
    UTL_SMTP.AUTH(
        c        => MAIL_CONN,
        username => P_SMTP_USERNAME,
        password => P_CLAVE_SMTP,
        schemes  => UTL_SMTP.ALL_SCHEMES
    );

    -- DE: REMITENTE  A DESTINATARIO
    UTL_SMTP.MAIL(MAIL_CONN, P_REMITENTE);
    -- TO por cada destinatario
    FOR i IN 1 .. V_LISTA_DESTINATARIOS.COUNT LOOP
        UTL_SMTP.RCPT(MAIL_CONN, V_LISTA_DESTINATARIOS(i));
    END LOOP;

    -- CONTENIDO DEL CORREO
    UTL_SMTP.OPEN_DATA(MAIL_CONN);
    
    UTL_SMTP.WRITE_DATA(MAIL_CONN,
        'From: ' || P_REMITENTE || CRLF ||
        'To: ' || P_DESTINATARIO || CRLF ||
        'Subject: ' || P_ASUNTO || CRLF ||
        'MIME-Version: 1.0' || CRLF ||
        'Content-Type: text/html; charset=UTF-8' || CRLF ||
        'Content-Transfer-Encoding: 8bit' || CRLF ||
        CRLF ||
        P_MENSAJE
    );

    UTL_SMTP.CLOSE_DATA(MAIL_CONN);
    UTL_SMTP.QUIT(MAIL_CONN);

    DBMS_OUTPUT.PUT_LINE('[OK] CORREO(S) ENVIADO CORRECTAMENTE');
EXCEPTION
    WHEN OTHERS THEN
        BEGIN
            UTL_SMTP.QUIT(MAIL_CONN);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('[WARN] (ACS_PRC_CORREO_NOTIFICADOR): NO SE PUDO CERRAR LA CONEXIÓN SMTP: ' || SQLERRM);
        END;
        DBMS_OUTPUT.PUT_LINE('[ERROR] (ACS_PRC_CORREO_NOTIFICADOR): AL ENVIAR CORREO: ' || SQLERRM);
        RAISE_APPLICATION_ERROR(-20001, '[ERROR] (ACS_PRC_CORREO_NOTIFICADOR): AL ENVIAR CORREO: ' || SQLERRM);
END;
/