-- Consultas del módulo Centro Médico
-- Cada sección devuelve información relevante y legible.
-- Ajusta filtros (WHERE ...) según tus necesidades.

-- PROMPT === Consulta Centros Médicos ===
SELECT ACM_ID, ACM_NOMBRE, ACM_UBICACION, ACM_TELEFONO, ACM_EMAIL, ACM_ESTADO
FROM ACS_CENTRO_MEDICO
ORDER BY ACM_NOMBRE;

-- PROMPT === Consulta Escalas Mensuales (con total detalles y estado) ===
SELECT E.AEM_ID, E.ACM_ID, C.ACM_NOMBRE,
       E.AEM_MES, E.AEM_ANIO, E.AEM_ESTADO,
       (SELECT COUNT(*) FROM ACS_DETALLE_MENSUAL D WHERE D.AEM_ID = E.AEM_ID) AS DETALLES
FROM ACS_ESCALA_MENSUAL E
JOIN ACS_CENTRO_MEDICO C ON C.ACM_ID = E.ACM_ID
ORDER BY E.AEM_ANIO DESC, E.AEM_MES DESC, C.ACM_NOMBRE;

-- PROMPT === Consulta Procedimientos ===
SELECT APD_ID, APD_NOMBRE, APD_DESCRIPCION, APD_ESTADO
FROM ACS_PROCEDIMIENTO
ORDER BY APD_NOMBRE;

-- PROMPT === Procedimientos por Centro (configuración de costos) ===
SELECT PC.APRC_ID, C.ACM_NOMBRE, P.APD_NOMBRE,
       PC.APRC_COSTO, PC.APRC_PAGO, PC.APRC_ESTADO
FROM ACS_PROCEDIMIENTOXCENTRO PC
JOIN ACS_CENTRO_MEDICO C ON C.ACM_ID = PC.ACM_ID
JOIN ACS_PROCEDIMIENTO P ON P.APD_ID = PC.APD_ID
ORDER BY C.ACM_NOMBRE, P.APD_NOMBRE;

-- PROMPT === Puestos Médicos ===
SELECT APM_ID, APM_NOMBRE, APM_DESCRIPCION, APM_ESTADO
FROM ACS_PUESTO_MEDICO
ORDER BY APM_NOMBRE;

-- PROMPT === Puestos por Centro ===
SELECT PX.APC_ID, C.ACM_NOMBRE, PM.APM_NOMBRE, PX.APC_ESTADO
FROM ACS_PUESTOXCENTRO PX
JOIN ACS_CENTRO_MEDICO C ON C.ACM_ID = PX.ACM_ID
JOIN ACS_PUESTO_MEDICO PM ON PM.APM_ID = PX.APM_ID
ORDER BY C.ACM_NOMBRE, PM.APM_NOMBRE;

-- PROMPT === Turnos Médicos (con puesto y médico si existen) ===
SELECT T.ATU_ID, T.ATU_NOMBRE,
       TO_CHAR(T.ATU_HORA_INICIO, 'HH24:MI') AS HORA_INICIO,
       TO_CHAR(T.ATU_HORA_FIN, 'HH24:MI') AS HORA_FIN,
       T.ATU_TIPO_PAGO, T.ATU_COSTO, T.ATU_PAGO, T.ATU_ESTADO,
       PM.APM_NOMBRE AS PUESTO,
       M.AME_ID AS MEDICO_ID,
       PERS.APE_CEDULA AS MEDICO_CEDULA,
       TRIM(PERS.APE_NOMBRE || ' ' || PERS.APE_P_APELLIDO || ' ' || NVL(PERS.APE_S_APELLIDO, '')) AS MEDICO_NOMBRE,
       PERS.APE_EMAIL AS MEDICO_EMAIL
FROM ACS_TURNO T
LEFT JOIN ACS_PUESTO_MEDICO PM ON PM.APM_ID = T.APM_ID
LEFT JOIN ACS_MEDICO M ON M.AME_ID = T.AME_ID
LEFT JOIN ACS_USUARIO U ON U.AUS_ID = M.AME_ID
LEFT JOIN ACS_PERSONA PERS ON PERS.APE_ID = U.APE_ID
ORDER BY T.ATU_NOMBRE;

-- PROMPT === Procedimientos Aplicados (detalle básico) ===
SELECT A.APA_ID, A.APA_FECHA, C.ACM_NOMBRE, P.APD_NOMBRE,
       A.APA_COSTO, A.APA_PAGO, A.APA_ESTADO, A.AME_ID AS MEDICO_ID,
       PERS.APE_CEDULA AS MEDICO_CEDULA,
       TRIM(PERS.APE_NOMBRE || ' ' || PERS.APE_P_APELLIDO || ' ' || NVL(PERS.APE_S_APELLIDO, '')) AS MEDICO_NOMBRE,
       PERS.APE_EMAIL AS MEDICO_EMAIL
FROM ACS_PROC_APLICADO A
LEFT JOIN ACS_CENTRO_MEDICO C ON C.ACM_ID = A.ACM_ID
LEFT JOIN ACS_PROCEDIMIENTO P ON P.APD_ID = A.APD_ID
LEFT JOIN ACS_MEDICO M ON M.AME_ID = A.AME_ID
LEFT JOIN ACS_USUARIO U ON U.AUS_ID = M.AME_ID
LEFT JOIN ACS_PERSONA PERS ON PERS.APE_ID = U.APE_ID
ORDER BY A.APA_FECHA DESC;

-- PROMPT === Auditoría Detalle Mensual (últimos cambios) ===
SELECT A.AUM_ID, A.ADM_ID, A.AEM_ID, A.AME_ID, A.APM_ID, A.ATU_ID,
       A.AUM_ESTADO_TURNO, A.AUM_ACCION, A.AUM_CAMBIOS,
       TO_CHAR(A.AUM_FECHA,'YYYY-MM-DD HH24:MI') AS FECHA,
       A.AUM_USUARIO,
       PERS.APE_CEDULA AS MEDICO_CEDULA,
       TRIM(PERS.APE_NOMBRE || ' ' || PERS.APE_P_APELLIDO || ' ' || NVL(PERS.APE_S_APELLIDO, '')) AS MEDICO_NOMBRE,
       PERS.APE_EMAIL AS MEDICO_EMAIL
FROM ACS_AUDITORIA_DETALLE_MENSUAL A
LEFT JOIN ACS_MEDICO M ON M.AME_ID = A.AME_ID
LEFT JOIN ACS_USUARIO U ON U.AUS_ID = M.AME_ID
LEFT JOIN ACS_PERSONA PERS ON PERS.APE_ID = U.APE_ID
ORDER BY A.AUM_FECHA DESC FETCH FIRST 50 ROWS ONLY;

-- PROMPT === Resumen Financiero Mensual ===
SELECT ARM_ID, ARM_PERIODO_ANIO, ARM_PERIODO_MES,
       ARM_INGRESOS, ARM_GASTOS, ARM_UTILIDAD,
       TO_CHAR(ARM_FECHA_CREACION,'YYYY-MM-DD') FECHA_CREACION,
       TO_CHAR(ARM_FECHA_ACTUALIZACION,'YYYY-MM-DD') FECHA_ACTUALIZACION
FROM ACS_RESUMEN_FIN_MENSUAL
ORDER BY ARM_PERIODO_ANIO DESC, ARM_PERIODO_MES DESC;
