-- ===============================================================================================
-- Seed Data SIMPLIFICADO: Movimientos Automáticos y Rangos
-- ===============================================================================================

DELETE FROM ACS_TIPO_MOV_RANGO;
DELETE FROM ACS_TIPO_MOV;
COMMIT;

-- CCSS (9%)
INSERT INTO ACS_TIPO_MOV (ATM_COD, ATM_NOMBRE, ATM_NATURALEZA, ATM_APLICA_A, ATM_MODO, ATM_BASE, ATM_PORC, ATM_MONTO_FIJO, ATM_ES_AUTOMATICO, ATM_PRIORIDAD, ATM_ESTADO, ATM_FECHA_CREACION, ATM_FECHA_ACTUALIZACION)
VALUES ('CCSS', 'Caja Costarricense Seguro Social', 'DEDUCCION', 'AMBOS', 'PORCENTAJE', 'BRUTO', 9.00, NULL, 1, 1, 'ACTIVO', SYSTIMESTAMP, SYSTIMESTAMP);

-- Renta (con rangos)
INSERT INTO ACS_TIPO_MOV (ATM_COD, ATM_NOMBRE, ATM_NATURALEZA, ATM_APLICA_A, ATM_MODO, ATM_BASE, ATM_PORC, ATM_MONTO_FIJO, ATM_ES_AUTOMATICO, ATM_PRIORIDAD, ATM_ESTADO, ATM_FECHA_CREACION, ATM_FECHA_ACTUALIZACION)
VALUES ('RENTA', 'Impuesto sobre la Renta', 'DEDUCCION', 'AMBOS', 'PORCENTAJE', 'BRUTO', NULL, NULL, 1, 2, 'ACTIVO', SYSTIMESTAMP, SYSTIMESTAMP);

-- Caja (2.5%)
INSERT INTO ACS_TIPO_MOV (ATM_COD, ATM_NOMBRE, ATM_NATURALEZA, ATM_APLICA_A, ATM_MODO, ATM_BASE, ATM_PORC, ATM_MONTO_FIJO, ATM_ES_AUTOMATICO, ATM_PRIORIDAD, ATM_ESTADO, ATM_FECHA_CREACION, ATM_FECHA_ACTUALIZACION)
VALUES ('CAJA', 'Aporte Caja de Ande', 'DEDUCCION', 'ADMINISTRATIVO', 'PORCENTAJE', 'BRUTO', 2.50, NULL, 1, 3, 'ACTIVO', SYSTIMESTAMP, SYSTIMESTAMP);

-- Banco Popular (1.5%)
INSERT INTO ACS_TIPO_MOV (ATM_COD, ATM_NOMBRE, ATM_NATURALEZA, ATM_APLICA_A, ATM_MODO, ATM_BASE, ATM_PORC, ATM_MONTO_FIJO, ATM_ES_AUTOMATICO, ATM_PRIORIDAD, ATM_ESTADO, ATM_FECHA_CREACION, ATM_FECHA_ACTUALIZACION)
VALUES ('BANCO_POPULAR', 'Cuota Banco Popular', 'DEDUCCION', 'AMBOS', 'PORCENTAJE', 'BRUTO', 1.50, NULL, 1, 4, 'ACTIVO', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;

-- Rangos de Renta (usando subquery para obtener ATM_ID)
INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_MONTO_FIJO, ATMR_ESTADO)
SELECT ATM_ID, 0, 941000, 0, NULL, 1 FROM ACS_TIPO_MOV WHERE ATM_COD = 'RENTA';

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_MONTO_FIJO, ATMR_ESTADO)
SELECT ATM_ID, 941001, 1381000, 10, NULL, 1 FROM ACS_TIPO_MOV WHERE ATM_COD = 'RENTA';

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_MONTO_FIJO, ATMR_ESTADO)
SELECT ATM_ID, 1381001, 2423000, 15, NULL, 1 FROM ACS_TIPO_MOV WHERE ATM_COD = 'RENTA';

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_MONTO_FIJO, ATMR_ESTADO)
SELECT ATM_ID, 2423001, 4845000, 20, NULL, 1 FROM ACS_TIPO_MOV WHERE ATM_COD = 'RENTA';

INSERT INTO ACS_TIPO_MOV_RANGO (ATM_ID, ATMR_RANGO_MIN, ATMR_RANGO_MAX, ATMR_PORCENTAJE, ATMR_MONTO_FIJO, ATMR_ESTADO)
SELECT ATM_ID, 4845001, 999999999, 25, NULL, 1 FROM ACS_TIPO_MOV WHERE ATM_COD = 'RENTA';

COMMIT;

-- Verificación
SELECT 'Movimientos cargados:' AS INFO FROM DUAL;
SELECT ATM_COD, ATM_NOMBRE, ATM_PRIORIDAD FROM ACS_TIPO_MOV ORDER BY ATM_PRIORIDAD;

SELECT 'Rangos de RENTA:' AS INFO FROM DUAL;
SELECT r.ATMR_RANGO_MIN, r.ATMR_RANGO_MAX, r.ATMR_PORCENTAJE 
FROM ACS_TIPO_MOV_RANGO r
JOIN ACS_TIPO_MOV t ON r.ATM_ID = t.ATM_ID
WHERE t.ATM_COD = 'RENTA'
ORDER BY r.ATMR_RANGO_MIN;
