-- ! procedimientos

CREATE OR REPLACE PROCEDURE PRC_Actualizar_Resumen_Finanzas(
p_mes IN NUMBER,
p_anio IN NUMBER,
p_monto IN NUMBER,
p_fuente IN VARCHAR2
) AS
v_existente NUMBER;
v_ingresos  NUMBER := 0;
v_gastos    NUMBER := 0;
BEGIN
-- Definir si el monto es ingreso o gasto
IF p_fuente = 'PLANILLA_MEDICOS' OR p_fuente = 'PLANILLA_ADMIN' THEN
    v_gastos := p_monto;
ELSE
    v_ingresos := p_monto;
END IF;

-- Verificar si ya existe el registro mensual
SELECT COUNT(*) INTO v_existente
FROM ACS_RESUMEN_FIN_MENSUAL
WHERE ARM_PERIODO_ANIO = p_anio
    AND ARM_PERIODO_MES  = p_mes;

IF v_existente = 0 THEN
    INSERT INTO ACS_RESUMEN_FIN_MENSUAL (
    ARM_PERIODO_ANIO, ARM_PERIODO_MES, ARM_INGRESOS, ARM_GASTOS, ARM_UTILIDAD,
    ARM_FECHA_CREACION, ARM_FECHA_ACTUALIZACION
    )
    VALUES (
    p_anio, p_mes,
    v_ingresos, v_gastos,
    v_ingresos - v_gastos,
    SYSTIMESTAMP, SYSTIMESTAMP
    );
ELSE
    UPDATE ACS_RESUMEN_FIN_MENSUAL
    SET ARM_INGRESOS = ARM_INGRESOS + v_ingresos,
        ARM_GASTOS    = ARM_GASTOS + v_gastos,
        ARM_UTILIDAD  = (ARM_INGRESOS + v_ingresos) - (ARM_GASTOS + v_gastos),
        ARM_FECHA_ACTUALIZACION = SYSTIMESTAMP
    WHERE ARM_PERIODO_ANIO = p_anio
    AND ARM_PERIODO_MES  = p_mes;
END IF;

COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/


-- =============================================
-- Procedimiento: PRC_ACTUALIZAR_RESUMEN_FINANZAS
-- Actualiza el resumen financiero mensual (ACS_RESUMEN_FIN_MENSUAL)
-- Clasifica montos como ingresos o gastos según la fuente
-- Es llamado automáticamente por el trigger TRG_PLANILLA_TO_MOVIM
-- Fecha: 2025-11-09
-- =============================================
CREATE OR REPLACE PROCEDURE PRC_ACTUALIZAR_RESUMEN_FINANZAS (
p_mes IN NUMBER,
p_anio IN NUMBER,
p_monto IN NUMBER,
p_fuente IN VARCHAR2
) AS
v_existente NUMBER;
v_ingresos  NUMBER := 0;
v_gastos    NUMBER := 0;
BEGIN
-- Definir si el monto es ingreso o gasto según la fuente
-- Fuentes de GASTO: Planillas (pagos a personal)
-- Fuentes de INGRESO: Turnos, Procedimientos (cobros a centros de salud)
IF p_fuente IN ('PLANILLA_MEDICOS', 'PLANILLA_ADMIN') THEN
    v_gastos := p_monto;
ELSE
    -- Asumir que otras fuentes son ingresos
    v_ingresos := p_monto;
END IF;

-- Verificar si ya existe el registro mensual
SELECT COUNT(*) INTO v_existente
FROM ACS_RESUMEN_FIN_MENSUAL
WHERE ARM_PERIODO_ANIO = p_anio
    AND ARM_PERIODO_MES  = p_mes;

IF v_existente = 0 THEN
    -- Crear nuevo registro para el mes
    INSERT INTO ACS_RESUMEN_FIN_MENSUAL (
    ARM_PERIODO_ANIO,
    ARM_PERIODO_MES,
    ARM_INGRESOS,
    ARM_GASTOS,
    ARM_UTILIDAD,
    ARM_FECHA_CREACION,
    ARM_FECHA_ACTUALIZACION
    )
    VALUES (
    p_anio,
    p_mes,
    v_ingresos,
    v_gastos,
    v_ingresos - v_gastos,
    SYSTIMESTAMP,
    SYSTIMESTAMP
    );
ELSE
    -- Actualizar registro existente acumulando valores
    UPDATE ACS_RESUMEN_FIN_MENSUAL
    SET ARM_INGRESOS = ARM_INGRESOS + v_ingresos,
        ARM_GASTOS    = ARM_GASTOS + v_gastos,
        ARM_UTILIDAD  = (ARM_INGRESOS + v_ingresos) - (ARM_GASTOS + v_gastos),
        ARM_FECHA_ACTUALIZACION = SYSTIMESTAMP
    WHERE ARM_PERIODO_ANIO = p_anio
    AND ARM_PERIODO_MES  = p_mes;
END IF;

COMMIT;

EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20060, 'Error al actualizar resumen financiero: ' || SQLERRM);
END PRC_ACTUALIZAR_RESUMEN_FINANZAS;
/

-- ! triggers

CREATE OR REPLACE TRIGGER TRG_AF_TURNO_PLANILLA_AI
AFTER INSERT ON ACS_TURNO_PLANILLA
FOR EACH ROW
DECLARE
V_ANIO NUMBER;
V_MES  NUMBER;
V_ACM  NUMBER;
BEGIN
SELECT P.APL_PERIODO_ANIO, P.APL_PERIODO_MES
    INTO V_ANIO, V_MES
    FROM ACS_DETALLE_PLANILLA D
    JOIN ACS_PLANILLA P ON P.APL_ID = D.APL_ID
WHERE D.ADP_ID = :NEW.ADP_ID;

INSERT INTO ACS_ASIENTO_FINANCIERO (AAF_TIPO, AAF_FUENTE, AAF_MONTO, AAF_PERIODO_ANIO, AAF_PERIODO_MES, ACM_ID, AAF_CREADO_EN)
VALUES ('INGRESO','TURNO', NVL(:NEW.MONTO_COBRADO_CENTRO,0), V_ANIO, V_MES, V_ACM, SYSTIMESTAMP);

INSERT INTO ACS_ASIENTO_FINANCIERO (AAF_TIPO, AAF_FUENTE, AAF_MONTO, AAF_PERIODO_ANIO, AAF_PERIODO_MES, ACM_ID, AAF_CREADO_EN)
VALUES ('GASTO','TURNO', NVL(:NEW.MONTO_PAGADO_MEDICO,0), V_ANIO, V_MES, V_ACM, SYSTIMESTAMP);
END;
/



CREATE OR REPLACE TRIGGER TRG_AF_PROC_PLANILLA_AI
AFTER INSERT ON ACS_PROCEDIMIENTO_PLANILLA
FOR EACH ROW
DECLARE
V_ANIO NUMBER;
V_MES  NUMBER;
BEGIN
SELECT P.APL_PERIODO_ANIO, P.APL_PERIODO_MES
    INTO V_ANIO, V_MES
    FROM ACS_DETALLE_PLANILLA D
    JOIN ACS_PLANILLA P ON P.APL_ID = D.APL_ID
WHERE D.ADP_ID = :NEW.ADP_ID;

INSERT INTO ACS_ASIENTO_FINANCIERO (AAF_TIPO, AAF_FUENTE, AAF_MONTO, AAF_PERIODO_ANIO, AAF_PERIODO_MES, ACM_ID, AAF_CREADO_EN)
VALUES ('INGRESO','PROCEDIMIENTO', NVL(:NEW.MONTO_COBRADO,0), V_ANIO, V_MES, :NEW.ACM_ID, SYSTIMESTAMP);

INSERT INTO ACS_ASIENTO_FINANCIERO (AAF_TIPO, AAF_FUENTE, AAF_MONTO, AAF_PERIODO_ANIO, AAF_PERIODO_MES, ACM_ID, AAF_CREADO_EN)
VALUES ('GASTO','PROCEDIMIENTO', NVL(:NEW.MONTO_PAGADO_MEDICO,0), V_ANIO, V_MES, :NEW.ACM_ID, SYSTIMESTAMP);
END;
/



CREATE OR REPLACE TRIGGER TRG_AF_PLANILLA_PROCESADA_AU
AFTER UPDATE OF APL_ESTADO ON ACS_PLANILLA
FOR EACH ROW
DECLARE
V_MONTO NUMBER;
V_FUENTE VARCHAR2(20);
V_APLICA VARCHAR2(20);
BEGIN
IF :NEW.APL_ESTADO = 'PROCESADA' THEN
    SELECT NVL(SUM(NETO),0) INTO V_MONTO
    FROM ACS_DETALLE_PLANILLA
    WHERE APL_ID = :NEW.APL_ID;

    SELECT TP.ATP_APLICA_A INTO V_APLICA
    FROM ACS_TIPO_PLANILLA TP
    WHERE TP.ATP_ID = :NEW.ATP_ID;

    V_FUENTE := CASE WHEN V_APLICA='ADMINISTRATIVO' THEN 'PLANILLA_ADMIN' ELSE 'PLANILLA_MEDICA' END;

    INSERT INTO ACS_ASIENTO_FINANCIERO (AAF_TIPO, AAF_FUENTE, AAF_MONTO, AAF_PERIODO_ANIO, AAF_PERIODO_MES, ACM_ID, AAF_CREADO_EN)
    VALUES ('GASTO', V_FUENTE, V_MONTO, :NEW.APL_PERIODO_ANIO, :NEW.APL_PERIODO_MES, NULL, SYSTIMESTAMP);
END IF;
END;
/



CREATE OR REPLACE TRIGGER TRG_RESUMEN_FIN_CENTRO_AI
AFTER INSERT ON ACS_ASIENTO_FINANCIERO
FOR EACH ROW
BEGIN
IF :NEW.ACM_ID IS NOT NULL THEN
    MERGE INTO ACS_RESUMEN_FIN_CENTRO_MES T
    USING (SELECT :NEW.ACM_ID ACM_ID, :NEW.AAF_PERIODO_ANIO ANIO, :NEW.AAF_PERIODO_MES MES FROM DUAL) S
    ON (T.ACM_ID = S.ACM_ID AND T.ARCM_PERIODO_ANIO = S.ANIO AND T.ARCM_PERIODO_MES = S.MES)
    WHEN NOT MATCHED THEN
    INSERT (ACM_ID, ARCM_PERIODO_ANIO, ARCM_PERIODO_MES, ARCM_INGRESOS, ARCM_GASTOS, ARCM_UTILIDAD)
    VALUES (S.ACM_ID, S.ANIO, S.MES, 0, 0, 0)
    WHEN MATCHED THEN
    UPDATE SET
        ARCM_INGRESOS = NVL(ARCM_INGRESOS,0) + CASE WHEN :NEW.AAF_TIPO='INGRESO' THEN :NEW.AAF_MONTO ELSE 0 END,
        ARCM_GASTOS   = NVL(ARCM_GASTOS,0)   + CASE WHEN :NEW.AAF_TIPO='GASTO'   THEN :NEW.AAF_MONTO ELSE 0 END,
        ARCM_UTILIDAD = (NVL(ARCM_INGRESOS,0) + CASE WHEN :NEW.AAF_TIPO='INGRESO' THEN :NEW.AAF_MONTO ELSE 0 END)
                    - (NVL(ARCM_GASTOS,0)   + CASE WHEN :NEW.AAF_TIPO='GASTO'   THEN :NEW.AAF_MONTO ELSE 0 END);
END IF;
END;
/



CREATE OR REPLACE TRIGGER TRG_RESUMEN_FIN_MENSUAL_AI
AFTER INSERT ON ACS_ASIENTO_FINANCIERO
FOR EACH ROW
BEGIN
MERGE INTO ACS_RESUMEN_FIN_MENSUAL T
USING (SELECT :NEW.AAF_PERIODO_ANIO ANIO, :NEW.AAF_PERIODO_MES MES FROM DUAL) S
    ON (T.ARM_PERIODO_ANIO = S.ANIO AND T.ARM_PERIODO_MES = S.MES)
WHEN NOT MATCHED THEN
    INSERT (ARM_PERIODO_ANIO, ARM_PERIODO_MES, ARM_INGRESOS, ARM_GASTOS, ARM_UTILIDAD)
    VALUES (S.ANIO, S.MES, 0, 0, 0)
WHEN MATCHED THEN
    UPDATE SET
    ARM_INGRESOS = NVL(ARM_INGRESOS,0) + CASE WHEN :NEW.AAF_TIPO='INGRESO' THEN :NEW.AAF_MONTO ELSE 0 END,
    ARM_GASTOS   = NVL(ARM_GASTOS,0)   + CASE WHEN :NEW.AAF_TIPO='GASTO'   THEN :NEW.AAF_MONTO ELSE 0 END,
    ARM_UTILIDAD = (NVL(ARM_INGRESOS,0) + CASE WHEN :NEW.AAF_TIPO='INGRESO' THEN :NEW.AAF_MONTO ELSE 0 END)
                - (NVL(ARM_GASTOS,0)   + CASE WHEN :NEW.AAF_TIPO='GASTO'   THEN :NEW.AAF_MONTO ELSE 0 END);
END;
/

CREATE OR REPLACE TRIGGER TRG_PLANILLA_TO_MOVIM
AFTER UPDATE OF APL_ESTADO ON ACS_PLANILLA
FOR EACH ROW
WHEN (NEW.APL_ESTADO = 'PROCESADA')
DECLARE
v_fuente VARCHAR2(20);
BEGIN
-- Determinar fuente del movimiento según tipo de planilla
SELECT CASE
        WHEN UPPER(t.ATP_APLICA_A) = 'MEDICO' THEN 'PLANILLA_MEDICOS'
        ELSE 'PLANILLA_ADMIN'
        END
INTO v_fuente
FROM ACS_TIPO_PLANILLA t
WHERE t.ATP_ID = :NEW.ATP_ID;

-- Insertar un movimiento por cada detalle de la planilla
FOR r IN (
    SELECT ADP_ID, APD_NETO
    FROM ACS_DETALLE_PLANILLA
    WHERE APL_ID = :NEW.APL_ID
) LOOP
    INSERT INTO ACS_MOVIMIENTO_PLANILLA (
    AMP_FUENTE,
    AMP_MONTO,
    AMP_OBS,
    AMP_CALC,
    AMP_FECHA_CREACION,
    APD_ID,
    ATM_ID
    )
    VALUES (
    v_fuente,
    r.APD_NETO,
    'Movimiento generado automáticamente (planilla ' || :NEW.APL_ID || ', detalle ' || r.ADP_ID || ')',
    1,
    SYSTIMESTAMP,
    r.ADP_ID,
    1 -- por ahora dejamos ATM_ID fijo o lo ajustamos luego
    );

    -- Actualizar resumen financiero mensual
    PRC_Actualizar_Resumen_Finanzas(:NEW.APL_MES, :NEW.APL_ANIO, r.APD_NETO, v_fuente);
END LOOP;
END;
/
