CREATE OR REPLACE PROCEDURE PRC_Resumen_Financiero_Mensual(
  p_mes IN NUMBER, p_anio IN NUMBER
) AS
  v_ingresos NUMBER := 0; v_gastos NUMBER := 0;
BEGIN
  SELECT NVL(SUM(CASE WHEN AMP_MONTO>0 THEN AMP_MONTO END),0),
         NVL(SUM(CASE WHEN AMP_MONTO<0 THEN -AMP_MONTO END),0)
  INTO v_ingresos, v_gastos
  FROM ACS_MOVIMIENTO_PLANILLA mp
  JOIN ACS_DETALLE_PLANILLA dp ON dp.APD_ID = mp.APD_ID
  JOIN ACS_PLANILLA pl ON pl.APL_ID = dp.APL_ID
  WHERE pl.APL_MES = p_mes AND pl.APL_ANIO = p_anio;

  MERGE INTO ACS_RESUMEN_FIN_MENSUAL r
  USING (SELECT p_mes MES, p_anio ANIO FROM DUAL) s
  ON (r.RFM_MES = s.MES AND r.RFM_ANIO = s.ANIO)
  WHEN MATCHED THEN UPDATE SET r.RFM_INGRESOS = v_ingresos, r.RFM_GASTOS = v_gastos
  WHEN NOT MATCHED THEN INSERT (RFM_ID, RFM_MES, RFM_ANIO, RFM_INGRESOS, RFM_GASTOS)
       VALUES (NULL, p_mes, p_anio, v_ingresos, v_gastos);

  COMMIT;
END;
/
