-- CREAR 2 TABLESPACES PARA EL PROYECTO, UNO PARA DATOS ( TBS_ACS_DATOS ) Y OTRO PARA INDICES ( TBS_ACS_INDICES ) --
CREATE TABLESPACE TBS_ACS_DATOS
DATAFILE 'C:\INSTALADORES\Oracle19c\ORADATA\UNA\ORCLPDB\TBS_ACS_DATOS.DBF'
SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLESPACE TBS_ACS_INDICES 
DATAFILE 'C:\INSTALADORES\Oracle19c\ORADATA\UNA\ORCLPDB\TBS_ACS_INDICES.DBF'
SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

