-- ** Configuraciones de Envio de correo **

/*
!Notas:
    * Entorno: Oracle19c. Windows11

    * Configuración Brevo:
        1. Auntentificar un correo y dominio
        2. Generar clave SMTP desde el panel de Brevo
        2. Configurar aplicación:
            Server: smtp-relay.brevo.com
            Puerto: 587 (TLS)
            Login: usuario-generado@smtp-brevo.com
            Password: clave-generada

    * Valores:
        Ubicacion Wallet: C:/instaladores/wallet

        Usuario Oracle: USER, con role XXX (con permiso para UTL_SMTP, UTL_TCP, acceso al wallet(de ser requerido)
        Correo origen: correo notificador
*/

-- ** Seccion: Preconfiguración de parametros en la tabla ACS_PARAMETROS **
/*
CREATE TABLE ACS_PARAMETROS (
    APA_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    APA_NOMBRE_PARAMETRO   VARCHAR2(100) UNIQUE NOT NULL,
    APA_VALOR_PARAMETRO   VARCHAR2(4000),
    APA_DESCRIPCION       VARCHAR2(200),
    APA_TIPO_PARAMETRO    VARCHAR2(20) DEFAULT 'SISTEMA',  -- Opcional: SISTEMA, EMAIL, SMTP, OTRO
);
*/
-- !DATOS TABLA ACS_PARAMETROS
INSERT INTO ACS_PARAMETROS VALUES ('CORREO_DBA', 'dba@acs.com', 'Correo del DBA', 'CORREO');

INSERT INTO ACS_PARAMETROS VALUES ('SMTP_CORREO', 'juancarlos19defebrerohat@gmail.com', 'Correo para notificaciones automaticas', 'SMTP');
INSERT INTO ACS_PARAMETROS VALUES ('SMTP_HOST', 'smtp-relay.brevo.com', 'Servidor para envio de correos', 'SMTP');
INSERT INTO ACS_PARAMETROS VALUES ('SMTP_PORT', '587', 'Puerto del servidor SMTP', 'SMTP');
INSERT INTO ACS_PARAMETROS VALUES ('SMPT_USUARIO', 'a1e38001@smtp-brevo.com', 'Usuario del servidor', 'SMPT');
INSERT INTO ACS_PARAMETROS VALUES ('SMTP_CLAVE', 'bskiTLMr8wV26Rp', 'Clave servidor', 'SMPT');
INSERT INTO ACS_PARAMETROS VALUES ('SMP_ACL_FILe', 'brevo_acl.xml', 'archivo acl', 'SMPT');
INSERT INTO ACS_PARAMETROS VALUES ('', '', '', '');
COMMIT;
/

-- ** Seccion: Configuracion ACL para envio de correos via SMTP **

/*
ACL (Access Control List) es un conjunto de reglas que definen los permisos de acceso a recursos de red específicos para usuarios o roles en Oracle Database.
Estos permisos son necesarios para que los procedimientos almacenados puedan interactuar con servicios externos, como servidores SMTP para el envío de correos electrónicos.

* se puede editar el arhivo XML del ACL para agregar o modificar reglas de acceso, como se muestra en el ejemplo al inicio de este archivo.
* Control deacceso se gestiona mediante el paquete DBMS_NETWORK_ACL_ADMIN.
* Pasos para configurar ACL para el envío de correos:
    1. Eliminar ACLs previos (si existen).
    2. Crear un nuevo ACL y asignar privilegios al usuario o rol que ejecutará el procedimiento de envío de correo.
    3. Asignar el ACL al host y puerto del servidor SMTP.
    4. Verificar que el ACL se haya configurado correctamente.
    5. (Opcional) Crear un directorio para el wallet si se utiliza SSL/TLS y asignar permisos adecuados.
*/

DECLARE
    V_ACL_FILE VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMP_ACL_FILe');
BEGIN
-- * PASO 1: LIMPIAR ACLs ANTERIORES *
    DBMS_NETWORK_ACL_ADMIN.DROP_ACL(acl => V_ACL_FILE);
    DBMS_OUTPUT.PUT_LINE('[OK] ACL anterior eliminado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -46104 THEN
            DBMS_OUTPUT.PUT_LINE('[INFO] No existía ACL previo');
        ELSE
            DBMS_OUTPUT.PUT_LINE('[WARN] Error eliminando ACL: ' || SQLERRM);
        END IF;
END;
/

DECLARE
    V_ACL_FILE VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMP_ACL_FILe');
    V_HOST VARCHAR2(100) := ACS_FUN_OBTENER_PARAMETRO('SMTP_HOST');
    V_PORT NUMBER := TO_NUMBER(ACS_FUN_OBTENER_PARAMETRO('SMTP_PORT'));

BEGIN
-- * PASO 2: CREAR NUEVO ACL PARA USUARIO USER *
    DBMS_NETWORK_ACL_ADMIN.CREATE_ACL(
        acl         => V_ACL_FILE,
        description => 'Acceso SMTP' || ' ' || V_HOST || ':' || V_PORT,
        principal   => 'USER',
        is_grant    => TRUE,
        privilege   => 'connect'
    );
    DBMS_OUTPUT.PUT_LINE('[OK] ACL creado con privilegio CONNECT');

    DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE(
        acl       => V_ACL_FILE,
        principal => 'USER',
        is_grant  => TRUE,
        privilege => 'resolve'
    );
    DBMS_OUTPUT.PUT_LINE('[OK] Privilegio RESOLVE agregado');

-- * PASO 3: ASIGNAR ACL A HOST SMTP (PUERTO 587) *
    DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(
        acl  => V_ACL_FILE,
        host => V_HOST,
        lower_port => V_PORT,
        upper_port => V_PORT
    );
    DBMS_OUTPUT.PUT_LINE('[OK] ACL asignado al puerto: ' || V_PORT);
    COMMIT;
END;
/

-- * PASO 4: VERIFICAR ACL CONFIGURADO *
/*
SELECT acl, principal, privilege, is_grant
FROM dba_network_acl_privileges
WHERE acl = 'brevo_acl.xml';

SELECT host, lower_port, upper_port, acl
FROM dba_network_acls
WHERE host = 'smtp-relay.brevo.com';
/
*/

-- * PASO 5: CREAR DIRECTORIO PARA WALLET (OPCIONAL, SOLO SI USA SSL/TLS) Y ROL *
/*
CREATE OR REPLACE DIRECTORY WALLET_DIR AS 'C:/instaladores/wallet';

CREATE OR REPLACE ROLE WALLET_ACCESS_ROLE;
GRANT WALLET_ACCESS_ROLE TO USER;

-- No se asgina al usuario actual, si no al rol que se usara para tener acceso al wallet
GRANT READ ON DIRECTORY WALLET_DIR TO WALLET_ACCESS_ROLE; 
/
*/

-- ** Seccion: Procedimiento almacenado para envio de correos via SMTP **

-- * PASO 6: PROCEDIMIENTO ALMACENADO DE ENVIO DE CORREO NOTIFICADOR *
CREATE OR REPLACE PROCEDURE ENVIAR_CORREO_NOTIFICADOR (
    P_DESTINATARIO IN VARCHAR2,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2
) 
IS
DECLARE
    -- COSTANTES
    CRLF CONSTANT VARCHAR2(2) := UTL_TCP.CRLF;
    -- CONEXION
    MAIL_CONN UTL_SMTP.CONNECTION;
    -- VARIABLES
    V_REMITENTE VARCHAR2(100) := ACS_FN_OBTENER_PARAMETRO('SMTP_CORREO');
    V_SMTP_HOST VARCHAR2(100) := ACS_FN_OBTENER_PARAMETRO('SMTP_HOST');
    V_SMTP_PORT NUMBER := TO_NUMBER(ACS_FN_OBTENER_PARAMETRO('SMTP_PORT'));
BEGIN
    -- OBTENER PARAMETROS
    -- CONECTAR CON Brevo, LOCAL SIN TLS
    MAIL_CONN := UTL_SMTP.OPEN_CONNECTION(V_SMTP_HOST, V_SMTP_PORT);
    UTL_SMTP.HELO(MAIL_CONN, V_SMTP_HOST);
    -- DE: REMITENTE  A DESTINATARIO
    UTL_SMTP.MAIL(MAIL_CONN, V_REMITENTE);
    UTL_SMTP.RCPT(MAIL_CONN, P_DESTINATARIO);
    -- CONTENIDO DEL CORREO
    UTL_SMTP.OPEN_DATA(MAIL_CONN);
    UTL_SMTP.WRITE_DATA(MAIL_CONN, 
        'From: ' || V_REMITENTE || CRLF ||
        'To: ' || P_DESTINATARIO || CRLF ||
        'Subject: ' || P_ASUNTO || CRLF ||
        'Content-Type: text/html; charset=UTF-8' || CRLF ||
        CRLF ||
        P_MENSAJE);
    UTL_SMTP.CLOSE_DATA(MAIL_CONN);
    UTL_SMTP.QUIT(MAIL_CONN);
    DBMS_OUTPUT.PUT_LINE('[OK] Correo enviado correctamente a ' || P_DESTINATARIO);
EXCEPTION
    WHEN OTHERS THEN
        BEGIN
            IF MAIL_CONN IS NOT NULL THEN
                UTL_SMTP.QUIT(MAIL_CONN);
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
        DBMS_OUTPUT.PUT_LINE('[ERROR] al enviar correo (ACS_PRC_CORREO_NOTIFICADOR): ' || SQLERRM);
        RAISE_APPLICATION_ERROR(-20001, '[ERROR] al enviar correo (ACS_PRC_CORREO_NOTIFICADOR): ' || SQLERRM);
END;
/