CREATE OR REPLACE PROCEDURE PRC_Escalas_Procesar_Por_Mes(
  p_mes  IN NUMBER,
  p_anio IN NUMBER
) AS
BEGIN
  UPDATE ACS_ESCALA_MENSUAL
  SET AEM_ESTADO = 'PROCESADA'
  WHERE AEM_MES = p_mes
    AND AEM_ANIO = p_anio
    AND AEM_ESTADO = 'LISTA PARA PAGO';
  COMMIT;
END;
/
