-- tablas
/*
create table ACS_PERSONA
(
    ape_id                  NUMBER generated always as identity,
    ape_cedula              VARCHAR2(20) not null,
    ape_nombre              VARCHAR2(200) not null,
    ape_p_apellido          VARCHAR2(100) not null,
    ape_s_apellido          VARCHAR2(100),
    ape_fecha_nacimiento    TIMESTAMP(6) not null,
    ape_sexo                VARCHAR2(10),
    ape_estado_civil        VARCHAR2(15),
    ape_nacionalidad        VARCHAR2(10),
    ape_tipo_usuario        VARCHAR2(15) not null,
    ape_estado_registro     VARCHAR2(10) not null,
    ape_email               VARCHAR2(255) not null,
    ape_telefono            VARCHAR2(20),
    ape_residencia          VARCHAR2(255),
    APE_DIRECCION_CASA       VARCHAR2(255),
    ape_direccion_trabajo   VARCHAR2(255),
    ape_fecha_creacion      TIMESTAMP(6) default SYSDATE not null,
    ape_fecha_actualizacion TIMESTAMP(6) not null
)

create table ACS_USUARIO
(
    aus_id             NUMBER generated by default on null as identity,
    aus_estado         VARCHAR2(10) default 'ACTIVO' not null,
    aus_fecha_creacion TIMESTAMP(6) default SYSDATE not null,
    aus_ultimo_acceso  TIMESTAMP(6) default SYSDATE not null,
    ape_id             NUMBER not null
)
*/

-- * modificar fecha de ultimo acceso de un usuario mediante cedula
begin
    UPDATE ACS_USUARIO u
    SET u.aus_ultimo_acceso = TO_TIMESTAMP('2024-06-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS')
    WHERE u.ape_id = (
        SELECT p.ape_id
        FROM ACS_PERSONA p
        WHERE p.ape_cedula = 'CED678901'
    );
    commit;
end;
/
-- * verificar cambio
SELECT 
    p.ape_cedula,
    p.ape_nombre,
    u.aus_ultimo_acceso
FROM ACS_USUARIO u
JOIN ACS_PERSONA p ON u.ape_id = p.ape_id
WHERE p.ape_cedula = 'CED678901';
/


/*
-- DEFINICIÓN DEL JOB MENSUAL
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'ACS_JOB_CHK_CUENTAS_INACTIVAS',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'ACS_PRC_CHK_CUENTAS_INACTIVAS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=2;BYMINUTE=0;BYSECOND=0',
        enabled         => TRUE,
        comments        => 'Job para inactivar cuentas de usuarios (ACS_USUARIO) con más de 3 meses de inactividad'
    );
END;
/
*/

-- * ejecutar job de control de actividad
BEGIN
    DBMS_SCHEDULER.RUN_JOB('ACS_JOB_CHK_CUENTAS_INACTIVAS', use_current_session => TRUE);
END;
/

-- * verificar estado de la cuenta despues de ejecutar el job
SELECT 
    p.ape_cedula,
    p.ape_nombre,
    u.aus_estado,
    u.aus_ultimo_acceso
FROM ACS_USUARIO u
JOIN ACS_PERSONA p ON u.ape_id = p.ape_id