
SET SERVEROUTPUT ON;
PROMPT ============================================================
PROMPT  🔹 INICIO DE PRUEBAS - MÓDULO CENTROS DE SALUD
PROMPT ============================================================

-- 1️⃣ LIMPIEZA DE DATOS PREVIOS
PROMPT → Limpiando tablas previas...
DELETE FROM ACS_DETALLE_MENSUAL;
DELETE FROM ACS_ESCALA_MENSUAL;
DELETE FROM ACS_TURNO;
DELETE FROM ACS_MEDICO;
DELETE FROM ACS_USUARIO;
DELETE FROM ACS_PERSONA;
DELETE FROM ACS_PUESTO_MEDICO;
DELETE FROM ACS_CENTRO_MEDICO;
COMMIT;

PROMPT Tablas limpiadas correctamente.

-- 2️⃣ CREACIÓN DE DATOS BASE
PROMPT → Insertando datos base...

INSERT INTO ACS_CENTRO_MEDICO (ACM_NOMBRE, ACM_UBICACION, ACM_TELEFONO, ACM_EMAIL, ACM_ESTADO)
VALUES ('Centro Prueba', 'San José', '2222-2222', 'centro@prueba.com', 'ACTIVO');

INSERT INTO ACS_PUESTO_MEDICO (APM_NOMBRE, APM_DESCRIPCION, APM_ESTADO)
VALUES ('Pediatría', 'Atención infantil', 'ACTIVO');

INSERT INTO ACS_PERSONA (APE_CEDULA, APE_NOMBRE, APE_P_APELLIDO, APE_FECHA_NACIMIENTO, 
                         APE_TIPO_USUARIO, APE_ESTADO_REGISTRO, APE_EMAIL, APE_FECHA_ACTUALIZACION)
VALUES ('888888888', 'Carlos', 'Mora', SYSDATE, 'MEDICO', 'APROBADO', 'carlos@una.cr', SYSDATE);

INSERT INTO ACS_USUARIO (APE_ID, AUS_ESTADO, AUS_FECHA_CREACION, AUS_ULTIMO_ACCESO)
VALUES ((SELECT MAX(APE_ID) FROM ACS_PERSONA), 'ACTIVO', SYSDATE, SYSDATE);

INSERT INTO ACS_MEDICO (AUS_ID, AME_ESTADO)
VALUES ((SELECT MAX(AUS_ID) FROM ACS_USUARIO), 'ACTIVO');

INSERT INTO ACS_TURNO (ATU_NOMBRE, ATU_HORA_INICIO, ATU_HORA_FIN, ATU_TIPO_PAGO, 
                       ATU_COSTO, ATU_PAGO, ATU_ESTADO)
VALUES ('Mañana', TIMESTAMP '2025-11-01 07:00:00', TIMESTAMP '2025-11-01 13:00:00', 
        'HORAS', 5000, 8000, 'ACTIVO');

COMMIT;

PROMPT Datos base insertados correctamente.

-- 3️⃣ VERIFICACIÓN DE DATOS BASE
PROMPT → Verificando IDs base:
SELECT ACM_ID, ACM_NOMBRE FROM ACS_CENTRO_MEDICO;
SELECT AME_ID FROM ACS_MEDICO;
SELECT APM_ID FROM ACS_PUESTO_MEDICO;
SELECT ATU_ID FROM ACS_TURNO;

-- 4️⃣ GENERACIÓN DE ESCALA MENSUAL
PROMPT → Ejecutando procedimiento PRC_GENERAR_ESCALA_MENSUAL...
DECLARE
  v_centro NUMBER;
BEGIN
  SELECT MIN(ACM_ID) INTO v_centro FROM ACS_CENTRO_MEDICO;
  PRC_GENERAR_ESCALA_MENSUAL(v_centro, 11, 2025);
END;
/

-- 5️⃣ CONSULTA DE ESCALAS
PROMPT → Consultando la escala mensual generada...
DECLARE
  v_centro NUMBER;
BEGIN
  SELECT MIN(ACM_ID) INTO v_centro FROM ACS_CENTRO_MEDICO;
  PRC_Consultar_Escalas(v_centro, 11, 2025);
END;
/

-- 6️⃣ REASIGNACIÓN DE MÉDICO EN UN TURNO
PROMPT → Reasignando médico al primer turno del mes...
DECLARE
  v_adm_id NUMBER;
  v_med_id NUMBER;
BEGIN
  SELECT MIN(ADM_ID) INTO v_adm_id FROM ACS_DETALLE_MENSUAL;
  SELECT MIN(AME_ID) INTO v_med_id FROM ACS_MEDICO;
  PRC_Asignar_Medico_Turno(v_adm_id, v_med_id);
END;
/

-- 7️⃣ CONSULTA POST-REASIGNACIÓN
PROMPT → Consultando escala tras la reasignación...
DECLARE
  v_centro NUMBER;
BEGIN
  SELECT MIN(ACM_ID) INTO v_centro FROM ACS_CENTRO_MEDICO;
  PRC_Consultar_Escalas(v_centro, 11, 2025);
END;
/

-- 8️⃣ VALIDACIÓN FINAL
PROMPT → Mostrando 10 registros de detalle:
SELECT ADM_ID, ADM_FECHA, AME_ID, APM_ID, ATU_ID, ADM_ESTADO_TURNO
FROM ACS_DETALLE_MENSUAL
WHERE ROWNUM <= 10;

PROMPT ============================================================
PROMPT  ✅ PRUEBAS COMPLETADAS CORRECTAMENTE
PROMPT ============================================================

COMMIT;
